<script setup lang="ts">
import { computed, onMounted, onUnmounted, reactive, ref, watch, toRaw } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { LayoutDashboard, LibraryBig, BookOpen, GraduationCap, FileText, Users, CreditCard, Sparkles, Settings2, ScrollText, Search, Plus, Upload, Download, ArrowUpRight, ArrowRight, ChevronRight, LogOut, RefreshCw, ShieldCheck, CalendarDays, Check, X, Menu, SlidersHorizontal, ClipboardList, Bell, HelpCircle, Eye, Pencil, CircleCheck, CircleAlert, Activity } from 'lucide-vue-next'
import { request, send } from './api'

const token=ref(sessionStorage.getItem('sxb-admin-token')||'')
const identity=ref<any>(null)
const loginForm=reactive({phone:'',password:''})
const loginError=ref(''); const loginBusy=ref(false)
const navigation=[
  {section:'总览',items:[{id:'dashboard',name:'工作台',icon:LayoutDashboard}]},
  {section:'教学内容',items:[{id:'exams',name:'考试与考期',icon:CalendarDays},{id:'knowledge',name:'知识点结构',icon:LibraryBig},{id:'question',name:'题库管理',icon:BookOpen},{id:'course',name:'课程管理',icon:GraduationCap},{id:'handout',name:'讲义资料',icon:FileText},{id:'article',name:'考试须知',icon:ClipboardList}]},
  {section:'用户与服务',items:[{id:'users',name:'用户管理',icon:Users},{id:'orders',name:'订单与会员',icon:CreditCard},{id:'records',name:'学习记录',icon:Activity},{id:'announcement',name:'公告管理',icon:Bell},{id:'faq',name:'常见问题',icon:HelpCircle}]},
  {section:'系统管理',items:[{id:'ai',name:'AI 配置中心',icon:Sparkles},{id:'audit',name:'操作日志',icon:ScrollText}]}
]
const view=ref(location.hash.slice(1)||'dashboard')
const currentNav=computed(()=>navigation.flatMap(g=>g.items).find(x=>x.id===view.value)||navigation[0].items[0])
const mobileNav=ref(false)
const busy=ref(false);const error=ref('');const saving=ref(false)
const dashboard=ref<any>(null);const rows=ref<any[]>([]);const total=ref(0);const page=ref(1);const search=ref('');const treeKind=ref('knowledge')
const exams=ref<any[]>([]);const contentOptions=ref<any[]>([]);const aiFeatures=ref<any[]>([]);const prices=ref<any[]>([])
const labels:Record<string,string>={subject:'科目',chapter:'章',section:'节',knowledge:'知识点',question:'题目',course:'课程',handout:'讲义',article:'考试须知',announcement:'公告',faq:'常见问题',draft:'草稿',review:'审核中',published:'已发布',offline:'已下架',pending_payment:'待支付',paid:'支付成功',closed:'已关闭',refunding:'退款中',refunded:'已退款',vip:'VIP',svip:'SVIP',trial:'VIP 24小时体验',upgrade:'VIP 升 SVIP',superadmin:'最高管理员',student:'学生',success:'成功',failed:'失败',note:'笔记',favorite:'收藏',plan:'学习计划',courseProgress:'课程进度',recite:'背诵',announcementRead:'公告已读'}
const contentViews=['knowledge','question','course','handout','article','announcement','faq']
const isContent=computed(()=>contentViews.includes(view.value))
const kind=computed(()=>view.value==='knowledge'?treeKind.value:view.value)
const formatDate=(v:any)=>v?new Date(v).toLocaleString('zh-CN',{hour12:false}):'—'
const money=(v:any)=>'¥'+Number(v||0).toFixed(2)
const tokenNumber=(v:any)=>v===null||v===undefined?'未返回':Number(v).toLocaleString('zh-CN')
const stateColor=(s:string)=>['published','paid','success'].includes(s)?'success':['review','pending_payment','refunding'].includes(s)?'warning':['failed'].includes(s)?'danger':'info'
async function login(){loginBusy.value=true;loginError.value='';try{const r=await send('/auth/admin',loginForm);token.value=r.token;identity.value=r.user;sessionStorage.setItem('sxb-admin-token',r.token);loginForm.password='';await load()}catch(e:any){loginError.value=e.message}finally{loginBusy.value=false}}
async function logout(){try{await send('/auth/logout',{})}finally{token.value='';sessionStorage.removeItem('sxb-admin-token');identity.value=null}}
function unauthorized(){token.value='';identity.value=null}
function navigate(id:string){view.value=id;location.hash=id;mobileNav.value=false;page.value=1;search.value=''}
function hashChange(){view.value=location.hash.slice(1)||'dashboard'}
let revision=0
async function load(){
  if(!token.value)return
  const rev=++revision;busy.value=true;error.value=''
  try{
    if(!exams.value.length)exams.value=await request('/exams')
    if(view.value==='dashboard')dashboard.value=await request('/admin/dashboard')
    else if(view.value==='ai'){const r=await request('/admin/ai');aiFeatures.value=r.features;prices.value=r.prices}
    else if(isContent.value){const r=await request(`/admin/content?kind=${kind.value}&search=${encodeURIComponent(search.value)}&page=${page.value}`);if(rev===revision){rows.value=r.items;total.value=r.total}}
    else {const r=await request('/admin/'+view.value);if(rev===revision)rows.value=r}
  }catch(e:any){if(rev===revision)error.value=e.message}finally{if(rev===revision)busy.value=false}
}
watch([view,page,treeKind],load)
onMounted(async()=>{window.addEventListener('sxb-unauthorized',unauthorized);window.addEventListener('hashchange',hashChange);if(token.value){try{identity.value=await request('/me');await load()}catch(e:any){error.value=e.message}}})
onUnmounted(()=>{window.removeEventListener('sxb-unauthorized',unauthorized);window.removeEventListener('hashchange',hashChange)})

const editor=ref(false);const edit=ref<any>({});const editError=ref('');const optionText=ref('');const answerText=ref('');const advanced=ref(false);const payloadText=ref('')
const parentOptions=computed(()=>contentOptions.value.filter(x=>x.exam_id===edit.value.exam_id && ({chapter:['subject'],section:['chapter'],knowledge:['section'],question:['knowledge'],course:['section','knowledge'],handout:['course']} as any)[edit.value.kind]?.includes(x.kind)))
async function openEditor(row?:any){
  contentOptions.value=await request('/admin/content-options')
  edit.value=row?structuredClone(toRaw(row)):{id:crypto.randomUUID(),kind:kind.value,exam_id:['article','announcement','faq'].includes(kind.value)?null:exams.value[0]?.id,parent_id:null,title:'',status:'draft',payload:{stars:3,type:kind.value==='course'?'article':'single',options:[],answer:[],requiredLevel:'vip'},source:'test',is_test_data:true}
  optionText.value=(edit.value.payload.options||[]).join('\n');answerText.value=(edit.value.payload.answer||[]).map((i:number)=>String.fromCharCode(65+i)).join(',')
  payloadText.value=JSON.stringify(edit.value.payload,null,2);advanced.value=false;editError.value='';editor.value=true
}
async function saveContent(){
  saving.value=true;editError.value=''
  try{
    const row=structuredClone(toRaw(edit.value))
    if(advanced.value)row.payload=JSON.parse(payloadText.value)
    if(row.kind==='question'){
      row.payload={...row.payload,stem:row.title,knowledgePointId:row.parent_id,options:optionText.value.split('\n').map(s=>s.trim()).filter(Boolean),answer:answerText.value?answerText.value.toUpperCase().split(/[,，\s]+/).join('').split('').map((s:string)=>s.charCodeAt(0)-65):[]}
    }
    if(row.kind==='knowledge')row.payload.title=row.title
    if(row.kind==='course')row.payload.sectionName=row.title
    await send('/admin/content/'+row.id,row,'PUT');editor.value=false;ElMessage.success('内容已保存');await load()
  }catch(e:any){editError.value=e.message}finally{saving.value=false}
}
const dateDialog=ref(false);const dateEdit=ref<any>({});const dateError=ref('')
function openDate(row:any){dateEdit.value={...row,endsAt:row.ends_at};dateError.value='';dateDialog.value=true}
async function saveDate(){saving.value=true;try{await send('/admin/exams/'+dateEdit.value.id,{endsAt:new Date(dateEdit.value.endsAt).toISOString()},'PUT');dateDialog.value=false;await load();ElMessage.success('考试日期已更新')}catch(e:any){dateError.value=e.message}finally{saving.value=false}}

const aiDialog=ref(false);const aiEdit=ref<any>({});const aiError=ref('');const aiTest=ref<Record<string,any>>({});const testing=ref('')
function configure(row:any){aiEdit.value={...structuredClone(toRaw(row)),apiKey:''};aiError.value='';aiDialog.value=true}
async function saveAI(){saving.value=true;aiError.value='';try{await send('/admin/ai/'+aiEdit.value.id,aiEdit.value,'PUT');aiDialog.value=false;await load();ElMessage.success('AI配置已保存')}catch(e:any){aiError.value=e.message}finally{saving.value=false}}
async function toggleAI(row:any,value:any){try{await send('/admin/ai/'+row.id,{enabled:Boolean(value),config:row.config},'PUT');row.enabled=Boolean(value)}catch(e:any){ElMessage.error(e.message)}}
async function testAI(row:any){
  if(row.config.mode==='live'){try{await ElMessageBox.confirm('将向中转商发送一条固定测试请求，可能产生少量费用。是否继续？','测试真实接口',{confirmButtonText:'发送测试',cancelButtonText:'取消',type:'warning'})}catch{return}}
  testing.value=row.id
  try{aiTest.value[row.id]=await send('/admin/ai/'+row.id+'/test',{});const r=aiTest.value[row.id];r.status==='success'?ElMessage.success(r.mode==='mock'?'本地测试适配器连通，未调用中转商':'真实接口测试成功'):ElMessage.error(r.error)}catch(e:any){ElMessage.error(e.message)}finally{testing.value=''}
}
const usageDialog=ref(false);const usageFeature=ref<any>(null);const usageDay=ref(new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'}));const usage=ref<any>({rows:[],summary:{}});const usageLoading=ref(false)
async function loadUsage(){if(!usageFeature.value||!usageDay.value)return;usageLoading.value=true;try{usage.value=await request('/admin/ai/'+usageFeature.value.id+'/usage?day='+usageDay.value)}catch(e:any){ElMessage.error(e.message)}finally{usageLoading.value=false}}
function openUsage(row:any){usageFeature.value=row;usageDialog.value=true;loadUsage()}
watch(usageDay,loadUsage)
const inspect=ref<any>(null)

const importDialog=ref(false);const importExam=ref('junior-social-worker');const importPreview=ref<any>(null);const importTest=ref(true);const importError=ref('');const importBusy=ref(false)
async function downloadTemplate(){try{const r=await fetch('/api/admin/import/template',{headers:{Authorization:'Bearer '+token.value}});if(!r.ok)throw new Error('模板下载失败');const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='题库导入模板.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e:any){ElMessage.error(e.message)}}
async function uploadFile(event:Event){
  const file=(event.target as HTMLInputElement).files?.[0];if(!file)return
  importBusy.value=true;importError.value='';importPreview.value=null
  try{if(file.size>8*1024*1024)throw new Error('文件不能超过8MB');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)});importPreview.value=await send('/admin/import/preview',{examId:importExam.value,filename:file.name,data})}catch(e:any){importError.value=e.message}finally{importBusy.value=false;(event.target as HTMLInputElement).value=''}
}
async function commit(){importBusy.value=true;try{const r=await send('/admin/import/'+importPreview.value.id+'/commit',{isTest:importTest.value});ElMessage.success(`${r.count} 道题已导入草稿`);importDialog.value=false;await load()}catch(e:any){importError.value=e.message}finally{importBusy.value=false}}
const orderDialog=ref(false);const orderEdit=ref<any>({});const orderError=ref('')
function openOrder(row:any){orderEdit.value={...row,amountYuan:row.amount_cents/100,nextStatus:'',reason:''};orderError.value='';orderDialog.value=true}
async function saveOrder(){saving.value=true;try{const o=orderEdit.value;await send('/admin/orders/'+o.id,{...(o.product==='upgrade'&&o.status==='pending_payment'?{amountCents:Math.round(o.amountYuan*100)}:{}),...(o.nextStatus?{status:o.nextStatus}:{}),reason:o.reason},'PATCH');orderDialog.value=false;await load();ElMessage.success('订单已更新并记录操作日志')}catch(e:any){orderError.value=e.message}finally{saving.value=false}}
</script>

<template>
  <div v-if="!token" class="login-screen">
    <header class="login-header"><span class="brand-icon"><GraduationCap :size="25" /></span><strong>上行宝</strong><span>管理后台</span></header>
    <main class="login-main">
      <span class="login-symbol"><ShieldCheck :size="30" /></span><h1>登录管理后台</h1><p>欢迎回来，请使用管理员账号登录</p>
      <el-form label-position="top" @submit.prevent="login">
        <el-form-item label="管理员手机号"><el-input v-model="loginForm.phone" autocomplete="username" inputmode="tel" size="large" placeholder="请输入手机号" maxlength="11" /></el-form-item>
        <el-form-item label="登录密码"><el-input v-model="loginForm.password" type="password" autocomplete="current-password" show-password size="large" placeholder="请输入密码" /></el-form-item>
        <el-alert v-if="loginError" :title="loginError" type="error" :closable="false" show-icon class="form-error" />
        <el-button type="primary" native-type="submit" size="large" class="login-submit" :loading="loginBusy">登录<ArrowRight :size="18" /></el-button>
      </el-form>
      <div class="login-security"><ShieldCheck :size="15" />仅限授权管理员访问</div>
    </main><footer class="login-footer">上行宝 · 本地测试环境</footer>
  </div>
  <div v-else class="admin-shell">
    <a class="skip-link" href="#workspace">跳至主要内容</a>
    <div v-if="mobileNav" class="nav-scrim" @click="mobileNav=false"></div>
    <aside class="sidebar" :class="{open:mobileNav}">
      <a href="#dashboard" class="brand" @click.prevent="navigate('dashboard')"><span class="brand-icon"><GraduationCap :size="24" /></span><span><strong>上行宝</strong><small>管理工作空间</small></span></a>
      <nav aria-label="后台导航"><section v-for="group in navigation" :key="group.section"><h2>{{ group.section }}</h2><button v-for="item in group.items" :key="item.id" :class="{active:view===item.id}" :aria-current="view===item.id?'page':undefined" @click="navigate(item.id)"><component :is="item.icon" :size="18" aria-hidden="true" /><span>{{ item.name }}</span><span v-if="item.id==='ai'" class="nav-dot"></span></button></section></nav>
      <div class="sidebar-foot"><span class="environment-dot"></span>本地测试环境<span>v0.2</span></div>
    </aside>
    <div class="shell-main">
      <header class="topbar"><div class="breadcrumb"><button class="icon-button mobile-toggle" aria-label="打开菜单" @click="mobileNav=true"><Menu :size="20" /></button><span>管理后台</span><ChevronRight :size="14" /><strong>{{ currentNav.name }}</strong></div><div class="topbar-actions"><span class="test-indicator">测试环境</span><span class="avatar">管</span><div class="account"><strong>{{ identity?.nickname||'最高管理员' }}</strong><small>{{ identity?.phone }}</small></div><el-tooltip content="退出登录"><button class="icon-button" aria-label="退出登录" @click="logout"><LogOut :size="18" /></button></el-tooltip></div></header>
      <main id="workspace" class="workspace" tabindex="-1">
        <div class="page-heading"><div><div class="eyebrow">{{ view==='dashboard'?'WORKSPACE OVERVIEW':view==='ai'?'AI OPERATIONS':'SXB CONSOLE' }}</div><h1>{{ currentNav.name }}</h1><p v-if="view==='dashboard'">{{ new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}) }} · 内容与业务概况</p><p v-else-if="view==='ai'">模型连接、功能权限与调用用量</p><p v-else-if="view==='orders'">会员按考试独立生效 · VIP ¥599 · SVIP ¥799</p></div><div class="heading-actions"><el-tooltip content="刷新数据"><el-button circle :loading="busy" aria-label="刷新数据" @click="load"><RefreshCw :size="17" /></el-button></el-tooltip><el-button v-if="isContent" type="primary" @click="openEditor()"><Plus :size="17" />新增{{ labels[kind] }}</el-button></div></div>
        <el-alert v-if="error" type="error" :closable="false" :title="error" show-icon class="form-error" />
        <div v-loading="busy" class="view-content">
          <template v-if="view==='dashboard'&&dashboard">
            <div class="metric-strip"><article><span>注册学生</span><strong>{{ dashboard.counts.users.toLocaleString() }}<small>人</small></strong><span class="metric-detail">独立账号，按考试记录权益</span><Users class="metric-icon" :size="23" /></article><article><span>题库内容</span><strong>{{ dashboard.counts.questions.toLocaleString() }}<small>题</small></strong><span class="metric-detail">{{ dashboard.counts.knowledge }} 个知识点</span><BookOpen class="metric-icon teal" :size="23" /></article><article><span>模拟支付金额</span><strong>{{ money(dashboard.counts.paid_cents/100) }}</strong><span class="metric-detail">{{ dashboard.counts.orders }} 笔测试订单 · 未实际扣款</span><CreditCard class="metric-icon amber" :size="23" /></article><article><span>AI 累计估算费用</span><strong>{{ money(dashboard.counts.ai_cost) }}</strong><span class="metric-detail">含测试调用，以中转账单为准</span><Sparkles class="metric-icon violet" :size="23" /></article></div>
            <div class="dashboard-grid"><section class="section-band"><div class="section-title"><h2>内容资源</h2><button class="text-button" @click="navigate('question')">管理题库<ArrowUpRight :size="16" /></button></div><div class="resource-list"><div v-for="item in dashboard.content" :key="item.kind"><span>{{ labels[item.kind]||item.kind }}</span><div class="resource-track"><span :style="{width:Math.max(3,item.count/Math.max(...dashboard.content.map((x:any)=>x.count))*100)+'%'}"></span></div><strong>{{ item.count }}</strong></div></div></section><section class="section-band"><div class="section-title"><h2>待办与快捷入口</h2></div><button class="quick-row" @click="navigate('question')"><span class="quick-icon"><ClipboardList :size="21" /></span><span><strong>待审核内容</strong><small>{{ dashboard.counts.drafts }} 条草稿待完善</small></span><ChevronRight :size="18" /></button><button class="quick-row" @click="navigate('ai')"><span class="quick-icon green"><Sparkles :size="21" /></span><span><strong>AI 服务配置</strong><small>10 个功能点独立配置</small></span><ChevronRight :size="18" /></button><button class="quick-row" @click="navigate('exams')"><span class="quick-icon gold"><CalendarDays :size="21" /></span><span><strong>考试日期</strong><small>初级、中级 · 暂定 5 月 31 日</small></span><ChevronRight :size="18" /></button></section></div>
            <section class="section-band activity-section"><div class="section-title"><h2>最近操作</h2><button class="text-button" @click="navigate('audit')">全部日志<ArrowUpRight :size="16" /></button></div><el-table :data="dashboard.recent" empty-text="暂无操作记录"><el-table-column prop="action" label="操作" width="200" /><el-table-column prop="target_id" label="关联记录" show-overflow-tooltip /><el-table-column label="时间" width="205"><template #default="{row}">{{ formatDate(row.created_at) }}</template></el-table-column></el-table></section>
          </template>
          <template v-else-if="view==='ai'">
            <div class="ai-overview"><div><span class="subtle-label">功能启用</span><strong>{{ aiFeatures.filter(x=>x.enabled).length }}<small>/ {{ aiFeatures.length }}</small></strong></div><div><span class="subtle-label">真实接口</span><strong>{{ aiFeatures.filter(x=>x.config.mode==='live').length }}<small>个功能</small></strong></div><div class="ai-note"><ShieldCheck :size="20" /><span>密钥加密保存，仅服务端调用<br /><small>价格单位：人民币 / 百万 Token</small></span></div></div>
            <div class="table-toolbar"><h2>功能与模型</h2><span class="subtle-label">默认关闭，配置后按需启用</span></div>
            <el-table :data="aiFeatures" row-key="id"><el-table-column label="功能点" min-width="160"><template #default="{row}"><button class="table-title" @click="openUsage(row)">{{ row.name }}</button><small class="cell-sub">{{ row.id }}</small></template></el-table-column><el-table-column label="服务与模型" min-width="200"><template #default="{row}"><span>{{ row.config.model }}</span><small class="cell-sub">{{ row.config.provider }}</small></template></el-table-column><el-table-column label="运行模式" width="115"><template #default="{row}"><el-tag :type="row.config.mode==='live'?'success':'info'" effect="plain">{{ row.config.mode==='live'?'真实接口':'本地测试' }}</el-tag></template></el-table-column><el-table-column label="启用" width="90"><template #default="{row}"><el-switch :model-value="row.enabled" :aria-label="'启用'+row.name" @change="toggleAI(row,$event)" /></template></el-table-column><el-table-column label="操作" min-width="225"><template #default="{row}"><div class="row-actions"><el-button link type="primary" @click="configure(row)"><Settings2 :size="15" />配置</el-button><el-button link type="primary" :loading="testing===row.id" @click="testAI(row)">测试连接</el-button><el-button link type="primary" @click="openUsage(row)">用量</el-button></div><small v-if="aiTest[row.id]" class="cell-sub">{{ aiTest[row.id].status==='success'?'最近测试成功':'最近测试失败' }} · {{ aiTest[row.id].durationMs }}ms</small></template></el-table-column></el-table>
          </template>
          <template v-else-if="isContent">
            <div class="table-toolbar"><el-radio-group v-if="view==='knowledge'" v-model="treeKind"><el-radio-button value="subject">科目</el-radio-button><el-radio-button value="chapter">章</el-radio-button><el-radio-button value="section">节</el-radio-button><el-radio-button value="knowledge">知识点</el-radio-button></el-radio-group><span v-else class="table-count">全部{{ labels[kind] }} <b>{{ total }}</b></span><div class="filter-tools"><el-input v-model="search" clearable placeholder="搜索标题" class="search-input" @keyup.enter="page=1;load()" @clear="page=1;load()"><template #prefix><Search :size="16" /></template></el-input><el-button v-if="view==='question'" @click="importDialog=true;importPreview=null;importError=''" ><Upload :size="16" />导入题库</el-button><el-button aria-label="执行搜索" @click="page=1;load()"><Search :size="16" /></el-button></div></div>
            <el-table :data="rows" row-key="id"><el-table-column label="标题" min-width="340"><template #default="{row}"><button class="table-title" @click="openEditor(row)">{{ row.title }}</button><small class="cell-sub">{{ row.id }}</small></template></el-table-column><el-table-column label="考试" width="140"><template #default="{row}">{{ exams.find(x=>x.id===row.exam_id)?.name||'全平台' }}</template></el-table-column><el-table-column label="状态" width="105"><template #default="{row}"><el-tag :type="stateColor(row.status)" effect="light">{{ labels[row.status] }}</el-tag></template></el-table-column><el-table-column label="数据来源" width="105"><template #default="{row}"><span :class="row.is_test_data?'test-label':'source-label'">{{ row.is_test_data?'测试内容':'真实资料' }}</span></template></el-table-column><el-table-column label="更新时间" width="180"><template #default="{row}">{{ formatDate(row.updated_at) }}</template></el-table-column><el-table-column label="操作" width="75" fixed="right"><template #default="{row}"><el-tooltip content="编辑内容"><el-button link type="primary" aria-label="编辑内容" @click="openEditor(row)"><Pencil :size="17" /></el-button></el-tooltip></template></el-table-column></el-table>
            <div class="pagination"><span>共 {{ total }} 条内容</span><el-pagination v-model:current-page="page" :total="total" :page-size="20" layout="prev,pager,next" /></div>
          </template>
          <template v-else-if="view==='exams'"><div class="table-toolbar"><h2>考期配置</h2><span class="subtle-label">北京时间 · 结束时间变更将影响会员有效期</span></div><el-table :data="rows"><el-table-column prop="name" label="考试名称" min-width="180" /><el-table-column prop="year" label="考试年度" width="140" /><el-table-column label="考试结束时间" min-width="220"><template #default="{row}">{{ formatDate(row.ends_at) }}</template></el-table-column><el-table-column label="配置状态" width="150"><template #default><el-tag type="warning" effect="plain">暂定日期</el-tag></template></el-table-column><el-table-column label="操作" width="110"><template #default="{row}"><el-button link type="primary" @click="openDate(row)"><Pencil :size="15" />修改</el-button></template></el-table-column></el-table></template>
          <template v-else-if="view==='users'"><el-table :data="rows" empty-text="暂无学生注册"><el-table-column prop="nickname" label="用户" min-width="140" /><el-table-column prop="phone" label="手机号" width="150" /><el-table-column label="角色" width="130"><template #default="{row}">{{ labels[row.role]||row.role }}</template></el-table-column><el-table-column prop="invite_code" label="推荐码" width="130" /><el-table-column prop="inviter" label="邀请人" min-width="130" /><el-table-column label="注册时间" width="190"><template #default="{row}">{{ formatDate(row.created_at) }}</template></el-table-column><el-table-column label="首次购买" width="190"><template #default="{row}">{{ formatDate(row.first_paid_at) }}</template></el-table-column></el-table></template>
          <template v-else-if="view==='orders'"><div class="table-toolbar"><h2>订单记录</h2><el-tag type="warning" effect="plain">本地模拟支付，无真实扣款</el-tag></div><el-table :data="rows" empty-text="暂无订单，请在用户端购买会员测试"><el-table-column label="订单" min-width="230"><template #default="{row}"><button class="table-title" @click="openOrder(row)">{{ labels[row.product] }}</button><small class="cell-sub">{{ row.id }}</small></template></el-table-column><el-table-column prop="phone" label="用户手机号" width="150" /><el-table-column prop="exam_name" label="考试" width="160" /><el-table-column label="金额" width="120"><template #default="{row}">{{ money(row.amount_cents/100) }}</template></el-table-column><el-table-column label="状态" width="115"><template #default="{row}"><el-tag :type="stateColor(row.status)">{{ labels[row.status] }}</el-tag></template></el-table-column><el-table-column label="创建时间" width="190"><template #default="{row}">{{ formatDate(row.created_at) }}</template></el-table-column><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="openOrder(row)">详情</el-button></template></el-table-column></el-table></template>
          <template v-else-if="view==='records'"><el-table :data="rows" empty-text="暂无学习记录"><el-table-column prop="phone" label="学生手机号" width="155" /><el-table-column label="记录类型" width="140"><template #default="{row}">{{ labels[row.kind]||row.kind }}</template></el-table-column><el-table-column prop="source_id" label="关联内容" min-width="180" /><el-table-column label="更新于" width="200"><template #default="{row}">{{ formatDate(row.updated_at) }}</template></el-table-column><el-table-column label="详情" width="80"><template #default="{row}"><el-button link type="primary" @click="inspect=row"><Eye :size="17" /></el-button></template></el-table-column></el-table></template>
          <template v-else-if="view==='audit'"><el-table :data="rows" empty-text="暂无操作日志"><el-table-column prop="action" label="操作" width="180" /><el-table-column prop="phone" label="操作人" width="150" /><el-table-column prop="target_id" label="关联记录" min-width="230" show-overflow-tooltip /><el-table-column label="时间" width="190"><template #default="{row}">{{ formatDate(row.created_at) }}</template></el-table-column><el-table-column label="详情" width="85"><template #default="{row}"><el-button link type="primary" aria-label="查看日志详情" @click="inspect=row"><Eye :size="17" /></el-button></template></el-table-column></el-table></template>
        </div>
        <footer class="workspace-footer"><span>上行宝管理后台</span><span>本地测试 · 所有模拟交易不产生实际扣款</span></footer>
      </main>
    </div>
  </div>

  <el-drawer v-model="editor" :title="'编辑'+(labels[edit.kind]||'内容')" size="680px" class="editor-drawer" :close-on-click-modal="false">
    <el-form label-position="top" class="editor-form">
      <el-form-item label="标题" required><el-input v-model="edit.title" type="textarea" :rows="2" maxlength="2000" /></el-form-item>
      <div class="form-columns"><el-form-item label="所属考试"><el-select v-model="edit.exam_id" :disabled="Boolean(edit.version)" clearable @clear="edit.exam_id=null"><el-option v-for="e in exams" :key="e.id" :label="e.name" :value="e.id" /></el-select></el-form-item><el-form-item label="发布状态"><el-select v-model="edit.status"><el-option v-for="s in ['draft','review','published','offline']" :key="s" :label="labels[s]" :value="s" /></el-select></el-form-item></div>
      <el-form-item v-if="!['subject','article','announcement','faq'].includes(edit.kind)" :label="edit.kind==='course'?'关联节 / 知识点':'所属父级'" required><el-select v-model="edit.parent_id" filterable><el-option v-for="p in parentOptions" :key="p.id" :label="`${labels[p.kind]} · ${p.title}`" :value="p.id" /></el-select></el-form-item>
      <el-form-item v-if="['knowledge','chapter','section'].includes(edit.kind)" label="排序"><el-input-number v-model="edit.payload.no" :min="1" :max="999" /></el-form-item>
      <el-form-item v-if="edit.kind==='knowledge'" label="知识点星级"><el-rate v-model="edit.payload.stars" show-score /></el-form-item>
      <template v-if="edit.kind==='question'"><el-form-item label="题型"><el-radio-group v-model="edit.payload.type"><el-radio-button value="single">单选题</el-radio-button><el-radio-button value="multiple">多选题</el-radio-button><el-radio-button value="subjective">主观题</el-radio-button></el-radio-group></el-form-item><template v-if="edit.payload.type!=='subjective'"><el-form-item label="选项，每行一个，按 A、B、C 顺序" required><el-input v-model="optionText" type="textarea" :rows="5" /></el-form-item><el-form-item label="正确答案，例如 A 或 A,C" required><el-input v-model="answerText" /></el-form-item></template><template v-else><el-form-item label="参考答案" required><el-input v-model="edit.payload.referenceAnswer" type="textarea" :rows="4" /></el-form-item><el-form-item label="评分标准" required><el-input v-model="edit.payload.rubric" type="textarea" :rows="4" /></el-form-item><el-form-item label="满分" required><el-input-number v-model="edit.payload.maxScore" :min="1" :max="200" /></el-form-item></template><el-form-item label="答案解析"><el-input v-model="edit.payload.explanation" type="textarea" :rows="5" /></el-form-item><div class="form-columns"><el-form-item label="真题年份"><el-input v-model="edit.payload.year" placeholder="非真题留空" /></el-form-item><el-form-item label="真题标签"><el-switch :model-value="edit.payload.source==='真题'" @change="edit.payload.source=$event?'真题':''" /></el-form-item></div></template>
      <template v-else-if="edit.kind==='course'"><div class="form-columns"><el-form-item label="课程类型"><el-select v-model="edit.payload.type"><el-option label="图文" value="article" /><el-option label="视频" value="video" /><el-option label="音频" value="audio" /></el-select></el-form-item><el-form-item label="所需会员"><el-select v-model="edit.payload.requiredLevel"><el-option label="VIP" value="vip" /><el-option label="SVIP" value="svip" /></el-select></el-form-item></div><el-form-item label="课程介绍"><el-input v-model="edit.payload.intro" type="textarea" :rows="5" /></el-form-item><el-form-item label="媒体地址（HTTPS）"><el-input v-model="edit.payload.mediaUrl" /></el-form-item><el-form-item label="时长（分钟）"><el-input-number v-model="edit.payload.totalMinutes" :min="1" /></el-form-item></template>
      <template v-else-if="edit.kind==='handout'"><el-form-item label="版本号"><el-input-number v-model="edit.payload.version" :min="1" /></el-form-item><el-form-item label="下载地址（HTTPS）"><el-input v-model="edit.payload.downloadUrl" /></el-form-item></template>
      <el-form-item v-else label="正文"><el-input v-model="edit.payload.content" type="textarea" :rows="7" /></el-form-item>
      <div class="form-columns"><el-form-item label="来源"><el-input v-model="edit.source" /></el-form-item><el-form-item label="测试内容标记"><el-switch v-model="edit.is_test_data" /></el-form-item></div>
      <el-checkbox v-model="advanced" @change="payloadText=JSON.stringify(edit.payload,null,2)">高级结构字段</el-checkbox><el-input v-if="advanced" v-model="payloadText" class="json-field" type="textarea" :rows="12" />
      <el-alert v-if="editError" :title="editError" type="error" :closable="false" show-icon class="form-error" />
    </el-form><template #footer><el-button @click="editor=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveContent">保存内容</el-button></template>
  </el-drawer>
  <el-dialog v-model="dateDialog" title="修改考试日期" width="480px"><p class="dialog-context">{{ dateEdit.name }} · {{ dateEdit.year }} 年</p><el-form label-position="top"><el-form-item label="考试结束时间（北京时间）"><el-date-picker v-model="dateEdit.endsAt" type="datetime" format="YYYY-MM-DD HH:mm:ss" /></el-form-item></el-form><el-alert v-if="dateError" :title="dateError" type="error" :closable="false" /><template #footer><el-button @click="dateDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveDate">保存日期</el-button></template></el-dialog>
  <el-drawer v-model="aiDialog" :title="aiEdit.name+' · 接口配置'" size="660px" :close-on-click-modal="false"><el-form v-if="aiEdit.config" label-position="top"><div class="form-columns"><el-form-item label="运行模式"><el-select v-model="aiEdit.config.mode"><el-option label="本地测试适配器" value="mock" /><el-option label="真实中转接口" value="live" /></el-select></el-form-item><el-form-item label="功能启用"><el-switch v-model="aiEdit.enabled" /></el-form-item></div><el-form-item label="服务商名称"><el-input v-model="aiEdit.config.provider" /></el-form-item><el-form-item label="API Base URL（包含 /v1）"><el-input v-model="aiEdit.config.baseUrl" placeholder="https://api.apikey.fun/v1" /></el-form-item><el-form-item label="接口协议"><el-radio-group v-model="aiEdit.config.protocol"><el-radio-button value="responses">Responses</el-radio-button><el-radio-button value="chat">Chat Completions</el-radio-button></el-radio-group></el-form-item><el-form-item label="API Key"><el-input v-model="aiEdit.apiKey" type="password" show-password autocomplete="new-password" :placeholder="aiEdit.has_key?'已加密保存，留空保持不变':'请输入中转商密钥'" /></el-form-item><el-form-item label="模型 ID"><el-select v-model="aiEdit.config.model" filterable allow-create default-first-option @change="Object.assign(aiEdit.config,prices.find(p=>p.model===$event)||{})"><el-option v-for="p in prices" :key="p.model" :value="p.model" :label="p.model" /></el-select></el-form-item><h3 class="form-section-title">费用标准 <small>人民币 / 1M Tokens</small></h3><div class="form-columns three"><el-form-item label="输入单价"><el-input-number v-model="aiEdit.config.inputPrice" :min="0" :precision="4" :controls="false" /></el-form-item><el-form-item label="输出单价"><el-input-number v-model="aiEdit.config.outputPrice" :min="0" :precision="4" :controls="false" /></el-form-item><el-form-item label="缓存读取"><el-input-number v-model="aiEdit.config.cachedPrice" :min="0" :precision="4" :controls="false" /></el-form-item></div><h3 class="form-section-title">用量限制</h3><div class="form-columns three"><el-form-item label="每日次数 / 用户"><el-input-number v-model="aiEdit.config.dailyLimit" :min="1" :max="100000" :controls="false" /></el-form-item><el-form-item label="最大输出 Token"><el-input-number v-model="aiEdit.config.maxTokens" :min="32" :max="16000" :controls="false" /></el-form-item><el-form-item label="超时（秒）"><el-input-number v-model="aiEdit.config.timeoutSeconds" :min="5" :max="120" :controls="false" /></el-form-item></div><el-form-item label="系统提示词"><el-input v-model="aiEdit.config.prompt" type="textarea" :rows="5" /></el-form-item><el-alert v-if="aiError" :title="aiError" type="error" :closable="false" show-icon /></el-form><template #footer><el-button @click="aiDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveAI">保存配置</el-button></template></el-drawer>
  <el-drawer v-model="usageDialog" :title="usageFeature?.name+' · 每日调用详情'" size="90%"><div class="usage-filter"><el-date-picker v-model="usageDay" value-format="YYYY-MM-DD" type="date" :clearable="false" /><span>北京时间</span><el-button :loading="usageLoading" @click="loadUsage"><RefreshCw :size="16" />刷新</el-button></div><div class="usage-metrics"><div><span>调用 / 成功</span><strong>{{ usage.summary.calls||0 }} / {{ usage.summary.successes||0 }}</strong></div><div><span>输入 / 输出 Token</span><strong>{{ tokenNumber(usage.summary.input_tokens||0) }} / {{ tokenNumber(usage.summary.output_tokens||0) }}</strong></div><div><span>估算费用</span><strong>¥{{ Number(usage.summary.cost||0).toFixed(6) }}</strong></div><div><span>测试 / 未知费用</span><strong>{{ usage.summary.tests||0 }} / {{ usage.summary.unpriced||0 }}</strong></div></div><el-table v-loading="usageLoading" :data="usage.rows" empty-text="当天尚无AI调用"><el-table-column label="时间" width="185"><template #default="{row}">{{ formatDate(row.created_at) }}</template></el-table-column><el-table-column label="接口 / 模型" min-width="250"><template #default="{row}"><span>{{ row.model }}</span><small class="cell-sub">{{ row.endpoint }}</small></template></el-table-column><el-table-column label="输入 / 输出 / 缓存" min-width="190"><template #default="{row}">{{ tokenNumber(row.input_tokens) }} / {{ tokenNumber(row.output_tokens) }} / {{ tokenNumber(row.cached_tokens) }}</template></el-table-column><el-table-column label="费用（元）" width="130"><template #default="{row}">{{ row.cost_yuan===null?'未知':Number(row.cost_yuan).toFixed(8) }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="stateColor(row.status)">{{ labels[row.status] }}</el-tag></template></el-table-column><el-table-column label="类型" width="85"><template #default="{row}">{{ row.is_test?'测试':'业务' }}</template></el-table-column><el-table-column label="详情" width="80"><template #default="{row}"><el-button link type="primary" aria-label="查看调用详情" @click="inspect=row"><Eye :size="17" /></el-button></template></el-table-column></el-table></el-drawer>
  <el-dialog v-model="importDialog" title="导入题库" width="760px" :close-on-click-modal="false"><el-form label-position="top"><el-form-item label="所属考试"><el-select v-model="importExam" :disabled="Boolean(importPreview)"><el-option v-for="e in exams" :key="e.id" :label="e.name" :value="e.id" /></el-select></el-form-item><div class="import-actions"><el-button @click="downloadTemplate"><Download :size="16" />下载标准模板</el-button><label class="upload-label"><Upload :size="16" />选择 Excel<input type="file" accept=".xlsx" :disabled="importBusy" @change="uploadFile" /></label></div><el-progress v-if="importBusy" :percentage="50" :indeterminate="true" :show-text="false" /><el-alert v-if="importError" :title="importError" type="error" :closable="false" class="form-error" /><template v-if="importPreview"><div class="import-summary"><strong>{{ importPreview.rows.length }} 道有效题目</strong><span>{{ importPreview.errors.length }} 项错误</span><el-checkbox v-model="importTest">标记为测试内容</el-checkbox></div><el-table v-if="importPreview.errors.length" :data="importPreview.errors" max-height="250"><el-table-column prop="line" label="行" width="60" /><el-table-column prop="id" label="题目ID" width="180" /><el-table-column prop="message" label="错误原因" /></el-table><el-table :data="importPreview.rows.slice(0,10)" max-height="260"><el-table-column prop="line" label="行" width="60" /><el-table-column prop="payload.stem" label="题目预览" /><el-table-column prop="payload.knowledgePointId" label="知识点ID" width="160" /></el-table></template></el-form><template #footer><el-button @click="importDialog=false">取消</el-button><el-button type="primary" :loading="importBusy" :disabled="!importPreview||importPreview.errors.length>0" @click="commit">确认导入草稿</el-button></template></el-dialog>
  <el-dialog v-model="orderDialog" title="订单详情" width="600px"><el-descriptions :column="1" border><el-descriptions-item label="订单号">{{ orderEdit.id }}</el-descriptions-item><el-descriptions-item label="用户 / 考试">{{ orderEdit.phone }} · {{ orderEdit.exam_name }}</el-descriptions-item><el-descriptions-item label="商品 / 状态">{{ labels[orderEdit.product] }} · {{ labels[orderEdit.status] }}</el-descriptions-item><el-descriptions-item label="支付金额">{{ money(orderEdit.amount_cents/100) }}</el-descriptions-item><el-descriptions-item label="支付时间">{{ formatDate(orderEdit.paid_at) }}</el-descriptions-item><el-descriptions-item label="关闭原因">{{ orderEdit.close_reason||'—' }}</el-descriptions-item></el-descriptions><el-form label-position="top" class="order-form"><el-form-item v-if="orderEdit.product==='upgrade'&&orderEdit.status==='pending_payment'" label="调整补差价（元，最低100）"><el-input-number v-model="orderEdit.amountYuan" :min="100" :precision="2" /></el-form-item><el-form-item label="订单操作"><el-select v-model="orderEdit.nextStatus" clearable><el-option v-if="orderEdit.status==='pending_payment'" label="关闭订单" value="closed" /><el-option v-if="orderEdit.status==='paid'" label="客服发起退款（测试）" value="refunding" /><el-option v-if="orderEdit.status==='refunding'" label="确认已退款（测试）" value="refunded" /></el-select></el-form-item><el-form-item label="操作原因（必填）"><el-input v-model="orderEdit.reason" type="textarea" :rows="3" /></el-form-item><el-alert v-if="orderError" :title="orderError" type="error" :closable="false" /></el-form><template #footer><el-button @click="orderDialog=false">关闭</el-button><el-button type="primary" :loading="saving" @click="saveOrder">保存操作</el-button></template></el-dialog>
  <el-dialog :model-value="Boolean(inspect)" title="记录详情" width="720px" @close="inspect=null"><pre class="record-json">{{ JSON.stringify(inspect,null,2) }}</pre></el-dialog>
</template>
