<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import ImportWizard from './ImportWizard.vue'
import { ElMessage } from 'element-plus'
import { Download, Upload, FileSpreadsheet } from 'lucide-vue-next'
import { flattenFields } from '../../shared/question-types'
import { request, send } from './api'
const importer=ref<InstanceType<typeof ImportWizard>>()
const props=defineProps<{exams:any[]}>(),emit=defineEmits(['saved'])
const visible=ref(false),mode=ref('import'),types=ref<any[]>([]),examId=ref(''),typeId=ref(''),version=ref(1),versions=ref<any[]>([]),busy=ref(false),error=ref(''),preview=ref<any>(null),isTest=ref(false),fileInput=ref<HTMLInputElement|null>(null)
const selected=computed(()=>types.value.find(t=>t.id===typeId.value))
const optionRules=computed(()=>selected.value?flattenFields(selected.value.definition.fields).filter(f=>f.kind==='options'||(['single','multiple'].includes(f.kind)&&!f.optionsSource)).map(f=>`${f.label}：${f.minOptions}～${f.maxOptions} 个选项，前 ${f.minOptions} 列必填`).join('；'):'')
async function open(next='import'){if(next==='import'){await importer.value?.open({kind:'question'});return}mode.value=next;visible.value=true;error.value='';preview.value=null;busy.value=true;try{types.value=await request('/admin/question-types');examId.value=props.exams[0]?.id||'';typeId.value=types.value.find(t=>t.enabled)?.id||'';await selectType()}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function selectType(){preview.value=null;if(!selected.value)return;version.value=selected.value.version;versions.value=await request('/admin/question-types/'+typeId.value+'/versions')}
watch([examId,typeId,version],()=>{preview.value=null;error.value=''})
async function file(mode:'template'|'export'){if(!typeId.value||!examId.value)return;busy.value=true;error.value='';try{const r=await fetch(`/api/admin/question-type-imports/file?typeId=${encodeURIComponent(typeId.value)}&version=${version.value}&examId=${encodeURIComponent(examId.value)}&mode=${mode}`,{headers:{Authorization:'Bearer '+sessionStorage.getItem('sxb-admin-token')}});if(!r.ok)throw new Error((await r.json()).message);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`${selected.value.name}-v${version.value}-${mode==='template'?'导入模板':'题目导出'}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e:any){error.value=e.message}finally{busy.value=false}}
async function upload(event:Event){const input=event.target as HTMLInputElement,f=input.files?.[0];if(!f)return;preview.value=null;error.value='';busy.value=true;try{if(f.size>8*1024*1024)throw new Error('文件不能超过8MB');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(f)});preview.value=await send('/admin/question-type-imports/preview',{examId:examId.value,typeId:typeId.value,filename:f.name,data})}catch(e:any){error.value=e.message}finally{busy.value=false;input.value=''}}
async function commit(){if(!preview.value||busy.value)return;busy.value=true;error.value='';try{const r=await send('/admin/import/'+preview.value.id+'/commit',{isTest:isTest.value});ElMessage.success(`已导入 ${r.count} 道题，状态为草稿`);visible.value=false;emit('saved')}catch(e:any){error.value=e.message}finally{busy.value=false}}
defineExpose({open})
</script>
<template><ImportWizard ref="importer" :exams="exams" @saved="emit('saved')"/><el-dialog v-model="visible" :title="mode==='import'?'按题型导入题目':'按题型导出题目'" width="700px" :close-on-click-modal="false" :close-on-press-escape="!busy" :before-close="(done:()=>void)=>{if(!busy)done()}"><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-form label-position="top"><div class="form-columns"><el-form-item label="考试项目" required><el-select v-model="examId" :disabled="busy" filterable><el-option v-for="e in exams" :key="e.id" :label="e.name" :value="e.id"/></el-select></el-form-item><el-form-item label="题型" required><el-select v-model="typeId" :disabled="busy" @change="selectType"><el-option v-for="t in types" :key="t.id" :label="t.name" :value="t.id" :disabled="mode==='import'&&!t.enabled"/></el-select></el-form-item></div><el-form-item v-if="mode==='export'" label="题型版本"><el-select v-model="version" :disabled="busy"><el-option v-for="v in versions" :key="v.version" :value="v.version" :label="'v'+v.version+(v.version===selected?.version?'（当前版本）':'（历史版本）')"/></el-select></el-form-item><template v-if="mode==='import'"><div class="qti-guide"><FileSpreadsheet :size="32"/><div><b>先下载模板，再填写题目</b><p>当前 v{{version}} · 一行一道完整题，组合题各小题分别填入对应列。</p><p v-if="optionRules">{{optionRules}}。每个选项单独一列。</p><p>判断题答案填“正确”或“错误”。知识点 ID 必填，多个用逗号分隔。</p><p>不同题型分别导入；导入不会覆盖已有题目。</p></div></div><div class="qti-actions"><el-button :disabled="busy||!typeId||!examId" @click="file('template')"><Download :size="16"/>下载对应模板</el-button><el-button type="primary" :disabled="busy||!typeId||!examId" @click="fileInput?.click()"><Upload :size="16"/>上传 Excel 并预览</el-button><input ref="fileInput" hidden type="file" accept=".xlsx" @change="upload"/></div><div v-if="preview" class="qti-preview"><el-alert :title="`校验通过 ${preview.rows.length} 道，错误 ${preview.errors.length} 条`" :type="preview.errors.length?'error':'success'" :closable="false"/><el-table v-if="preview.errors.length" :data="preview.errors" max-height="240"><el-table-column prop="line" label="行号" width="70"/><el-table-column prop="message" label="需要修正"/></el-table><el-table v-else :data="preview.rows.slice(0,10)" max-height="240"><el-table-column prop="line" label="行号" width="70"/><el-table-column prop="payload.stem" label="题目标题"/></el-table><p>预览最多显示前10道题；全部通过校验后才能确认导入。</p></div><el-form-item label="标记为测试内容"><el-switch v-model="isTest" :disabled="busy"/></el-form-item></template><p v-else class="qti-muted">导出所选考试、题型及版本下的全部题目，保留题目ID、知识点关联、等级、正确答案和解析。</p></el-form><template #footer><el-button :disabled="busy" @click="visible=false">取消</el-button><el-button v-if="mode==='export'" type="primary" :loading="busy" :disabled="!typeId||!examId" @click="file('export')">导出 Excel</el-button><el-button v-else type="primary" :loading="busy" :disabled="!preview||preview.errors.length>0||!preview.rows.length" @click="commit">确认导入</el-button></template></el-dialog></template>
<style scoped>.qti-guide{display:flex;gap:16px;padding:20px;background:var(--el-color-primary-light-9);border-radius:8px;color:var(--primary)}.qti-guide p,.qti-muted{font-size:13px;color:var(--muted);line-height:1.8;margin-top:6px}.qti-guide svg{flex:none}.qti-actions{display:flex;gap:12px;margin:20px 0}.qti-preview{margin-bottom:20px}.qti-preview p{font-size:12px;color:var(--muted);margin-top:10px}</style>
