import 'dotenv/config'
import assert from 'node:assert/strict'
import {mkdir,mkdtemp} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {chromium,expect} from '@playwright/test'
import express from 'express'
import {ZodError} from 'zod'
process.env.APP_MODE='test';process.env.DATABASE_URL='';process.env.LOCAL_DATABASE_DIR=await mkdtemp(join(tmpdir(),'sxb-cheatsheet-'));process.env.MEDIA_DIR=await mkdtemp(join(tmpdir(),'sxb-cheatsheet-media-'));process.env.SECRET_KEY='f'.repeat(64);process.env.ADMIN_PHONE='18600000000';process.env.ADMIN_PASSWORD='Cheatsheet-Tests-42!'
const {db,closeDatabase}=await import('../apps/api/src/db.ts'),{seed}=await import('../apps/api/src/seed.ts'),{initSecrets,session}=await import('../apps/api/src/security.ts'),{api}=await import('../apps/api/src/routes.ts'),{rights}=await import('../apps/api/src/membership.ts')
await initSecrets();await seed()
const admin=(await db.query("SELECT id FROM users WHERE account_kind='admin' LIMIT 1")).rows[0],token=await session(admin.id,'admin'),student=await session('test-student-001'),free=await session('test-student-003')
const app=express();app.use(express.json({limit:'40mb'}));app.use('/api',api);app.use((e,_q,r,_n)=>r.status(e instanceof ZodError?400:e.status||500).json({message:e.message}))
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const origin='http://127.0.0.1:'+server.address().port
async function call(path,body,method='GET',auth=token,expected=200){const r=await fetch(origin+'/api'+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+auth},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return data}
const current=async id=>(await db.query('SELECT * FROM content WHERE id=$1',[id])).rows[0],exam='junior-social-worker',day=86400000
const doc={type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'考前核心知识与应试提醒'}]}]},opens=new Date(Date.now()+day).toISOString(),closes=new Date(Date.now()+3*day).toISOString()
for(const [id,status,close]of [['sheet-open','published',closes],['sheet-draft','draft',closes],['sheet-offline','offline',closes],['sheet-expired','published',new Date(Date.now()-day).toISOString()]]){
 await call('/admin/content/'+id,{id,kind:'cheatsheet',exam_id:exam,parent_id:null,title:{'sheet-open':'回归小抄：社会工作核心考点','sheet-draft':'回归草稿小抄','sheet-offline':'回归停用小抄','sheet-expired':'回归已关闭小抄'}[id],status:status==='published'?'review':status,payload:{intro:'考试复习资料',document:doc,opensAt:id==='sheet-expired'?new Date(Date.now()-3*day).toISOString():opens,closesAt:close},source:'test',is_test_data:true},'PUT');if(status==='published')await call('/admin/content/'+id,{...await current(id),status},'PUT')
}
await call('/admin/cheatsheets',undefined,'GET',student,403)
for(const id of ['sheet-draft','sheet-offline','sheet-expired'])await call('/admin/cheatsheets/'+id+'/push',{version:(await current(id)).version},'POST',token,400)
assert.equal((await call('/admin/cheatsheets?search=回归&pushed=no')).total,4)
assert.equal((await call('/admin/cheatsheets?search=回归&status=offline')).total,1)
assert.equal((await call('/admin/cheatsheets?search=回归&'+new URLSearchParams({from:new Date(Date.now()+2*day).toISOString(),to:new Date(Date.now()+4*day).toISOString()}))).total,3)
const expected=[];for(const u of (await db.query("SELECT id FROM users WHERE account_kind='student' AND enabled")).rows)if((await rights(u.id,exam)).permissions['cheatsheet.read'])expected.push(u.id);assert(expected.includes('test-student-001'));assert(!expected.includes('test-student-003'))
const output='.local/qa/cheatsheet-management';await mkdir(output,{recursive:true});const browser=await chromium.launch({channel:'chrome',headless:true})
try{
 const page=await browser.newPage({viewport:{width:2097,height:1272},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message))
 const proxy=async route=>{const u=new URL(route.request().url());if(!u.pathname.startsWith('/api/'))return route.continue();const response=await route.fetch({url:origin+u.pathname+u.search});await route.fulfill({response})}
 await page.route('**/api/**',proxy);await page.addInitScript(t=>sessionStorage.setItem('sxb-admin-token',t),token);await page.goto('http://127.0.0.1:5180/#cheatsheet')
 const manager=page.locator('.cheatsheet-management');await expect(manager).toBeVisible();await manager.getByRole('textbox',{name:'筛选标题'}).fill('回归');await manager.getByRole('button',{name:'查询',exact:true}).click();await expect(manager.locator('tbody tr')).toHaveCount(4)
 assert.deepEqual(await manager.locator('thead th').allTextContents(),['标题','考试项目','状态','开放时间至关闭时间','推送状态','更新时间','操作'])
 const row=manager.locator('tbody tr').filter({hasText:'回归小抄：社会工作核心考点'}),offline=manager.locator('tbody tr').filter({hasText:'回归停用小抄'})
 await expect(offline.getByRole('button',{name:'推送小抄'})).toBeDisabled();await page.screenshot({path:output+'/list.png',animations:'disabled'})
 await row.getByRole('button',{name:'推送小抄'}).click();await expect(page.locator('.el-message-box')).toContainText('开放时间会改为本次推送时间');await page.screenshot({path:output+'/push-confirm.png',animations:'disabled'});await page.locator('.el-message-box').getByRole('button',{name:'取消',exact:true}).click();assert.equal((await current('sheet-open')).payload.opensAt,opens)
 const version=(await current('sheet-open')).version;await row.getByRole('button',{name:'推送小抄'}).click();await page.locator('.el-message-box').getByRole('button',{name:'确认推送',exact:true}).click();await expect(row.locator('td').nth(4)).toHaveText('是')
 const pushed=await current('sheet-open');assert(Date.parse(pushed.payload.opensAt)<Date.parse(opens));assert.equal(pushed.payload.closesAt,closes);await call('/admin/cheatsheets/sheet-open/push',{version},'POST',token,409)
 const record=(await db.query("SELECT * FROM cheatsheet_pushes WHERE content_id='sheet-open'")).rows[0];assert.equal(record.recipient_count,expected.length)
 const delivered=(await db.query('SELECT user_id FROM message_deliveries WHERE message_id=$1',[record.message_id])).rows.map(x=>x.user_id).sort();assert.deepEqual(delivered,expected.sort())
 const messages=await call('/messages?examId='+exam,undefined,'GET',student);assert(messages.some(m=>m.id===record.message_id&&m.schedule.contentId==='sheet-open'));assert(!(await call('/messages?examId='+exam,undefined,'GET',free)).some(m=>m.id===record.message_id))
 await row.getByRole('button',{name:'停用',exact:true}).click();await page.locator('.el-message-box').getByRole('button',{name:'停用',exact:true}).click();await expect(row.getByRole('button',{name:'推送小抄'})).toBeDisabled();await row.getByRole('button',{name:'启用',exact:true}).click();await page.locator('.el-message-box').getByRole('button',{name:'启用',exact:true}).click();await expect(row.getByRole('button',{name:'推送小抄'})).toBeEnabled();assert.equal((await current('sheet-open')).payload.opensAt,pushed.payload.opensAt)
 await manager.locator('.el-select').filter({has:page.getByRole('combobox',{name:'筛选推送状态',exact:true})}).click();await page.getByRole('option',{name:'已推送',exact:true}).click();await expect(manager.locator('tbody tr')).toHaveCount(1)
 const fixture=await browser.newPage({viewport:{width:640,height:240}});await fixture.setContent('<div style="box-sizing:border-box;width:640px;height:240px;padding:32px;background:#edf4ff;color:#244c85;font:22px sans-serif"><strong>考前复习 · 三步梳理</strong><div style="display:flex;gap:16px;margin-top:32px;font-size:18px"><span style="padding:24px;background:#fff">01 核心概念</span><span style="padding:24px;background:#fff">02 服务流程</span><span style="padding:24px;background:#fff">03 案例应用</span></div></div>');const png=await fixture.locator('body>div').screenshot();await fixture.close()
 async function insertImage(scope){await scope.getByRole('button',{name:'插入图片',exact:true}).click();const dialog=page.getByRole('dialog',{name:'插入资源',exact:true});await dialog.locator('input[type=file]').first().setInputFiles({name:'回归图片.png',mimeType:'image/png',buffer:png});await dialog.getByRole('button',{name:'插入正文',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(scope.locator('.rich-editor img').first()).toBeVisible()}
 await row.getByRole('button',{name:'编辑小抄'}).click();const edit=page.locator('.editor-drawer:visible');try{await expect(edit.getByRole('button',{name:'插入图片',exact:true})).toBeVisible()}catch(e){await page.screenshot({path:output+'/editor-failure.png'});console.log('EDITOR',await edit.innerText(),errors);throw e}await insertImage(edit);await edit.getByRole('button',{name:'保存内容',exact:true}).click();await expect(edit).toHaveCount(0);const body=await current('sheet-open');assert(body.payload.document.content.some(n=>n.type==='resource'))
 await page.goto('http://127.0.0.1:5180/#exam-categories');await page.getByRole('button',{name:'新增分类',exact:true}).click();const category=page.getByRole('dialog',{name:'新增分类',exact:true});await category.locator('.el-form-item').filter({has:page.getByText('分类名称',{exact:true})}).getByRole('textbox').fill('全站图片回归');await insertImage(category);await category.getByRole('button',{name:'保存',exact:true}).click();await expect(category).toHaveCount(0)
 const cat=(await db.query("SELECT * FROM exam_categories WHERE name='全站图片回归'")).rows[0],image=JSON.parse(cat.intro).content.find(n=>n.type==='image');assert.match(image.attrs.src,/\/api\/message-images\//);const assetId=image.attrs.src.split('/').pop();assert.equal((await fetch(origin+image.attrs.src)).status,200)
 await call('/admin/resources/'+assetId,{},'DELETE',token,409)
 const template={id:'image-template',name:'带图片消息模板',title:'测试模板',status:'draft',content:'模板文字',document:{type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'模板文字'}]},image]},variables:[]};await call('/admin/message-templates/image-template',template,'PUT')
 await page.goto('http://127.0.0.1:5180/#message-template');await page.locator('tbody tr').filter({hasText:'带图片消息模板'}).getByRole('button',{name:'编辑',exact:true}).click();const tpl=page.getByRole('dialog',{name:'编辑消息模板'});await expect(tpl.locator('.rich-editor img')).toBeVisible();await insertImage(tpl);await tpl.getByRole('button',{name:'保存模板'}).click();await expect(tpl).toHaveCount(0)
 const savedTemplate=(await db.query("SELECT * FROM message_templates WHERE id='image-template'")).rows[0];assert.equal(savedTemplate.document.content.filter(n=>n.type==='image').length,2)
 await call('/admin/messages',{id:'image-message',title:'带图片的通知',document:savedTemplate.document,content:'模板文字',channels:['h5'],l1Ids:[],l2Ids:[exam],permissionLevels:['svip'],schedule:{},sendType:'manual',status:'draft',userIds:['test-student-001']},'POST');await call('/admin/messages/image-message/send',{},'POST')
 const mobile=await browser.newPage({viewport:{width:390,height:844}});await mobile.route('**/api/**',proxy);await mobile.addInitScript(t=>{localStorage.setItem('sxb-api-token',t);localStorage.setItem('sxb-current-exam',JSON.stringify({type:'object',data:{id:'junior-social-worker',name:'初级社会工作师'}}))},student)
 await mobile.goto('http://127.0.0.1:5174/#/pages/profile-center/index?mode=announcements');await mobile.getByText('带图片的通知',{exact:true}).click();await expect(mobile.locator('.fold-content img')).toHaveCount(2);await mobile.getByText('考前小抄已开放：回归小抄：社会工作核心考点',{exact:true}).click();await mobile.getByText('查看资料',{exact:true}).click();await expect(mobile).toHaveURL(/cheatsheet-detail/);await expect(mobile.locator('.study-image')).toBeVisible();await expect.poll(()=>mobile.locator('.study-image img').evaluateAll(imgs=>imgs.every(img=>img.complete&&img.naturalWidth>0))).toBe(true);await mobile.screenshot({path:output+'/mobile-sheet.png',fullPage:true});await mobile.close()
 // A failed delivery rolls back the message, push record, and opening time together.
 const beforeFailure=await current('sheet-open'),countBefore=(await db.query('SELECT count(*)::int n FROM messages')).rows[0].n
 await db.query("CREATE FUNCTION push_test_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'simulated delivery failure'; END $$");await db.query('CREATE TRIGGER push_test_fail BEFORE INSERT ON message_deliveries FOR EACH ROW EXECUTE FUNCTION push_test_fail()')
 await call('/admin/cheatsheets/sheet-open/push',{version:beforeFailure.version},'POST',token,500);assert.equal((await current('sheet-open')).version,beforeFailure.version);assert.equal((await current('sheet-open')).payload.opensAt,beforeFailure.payload.opensAt);assert.equal((await db.query('SELECT count(*)::int n FROM messages')).rows[0].n,countBefore)
 await db.query('DROP TRIGGER push_test_fail ON message_deliveries');await db.query('DROP FUNCTION push_test_fail()')
 const simultaneous=await Promise.all([1,2].map(()=>fetch(origin+'/api/admin/cheatsheets/sheet-open/push',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({version:beforeFailure.version})})));assert.deepEqual(simultaneous.map(r=>r.status).sort(),[200,409])
 // No recipients: no message and no opening-time change.
 await db.query("UPDATE users SET enabled=false WHERE account_kind='student'");const previous=await current('sheet-open');await call('/admin/cheatsheets/sheet-open/push',{version:previous.version},'POST',token,400);assert.equal((await current('sheet-open')).version,previous.version)
 // Deleted generic image cannot be reintroduced by a stale editor.
 const form=new FormData();form.append('file',new Blob([png]),'unused.png');const uploaded=await(await fetch(origin+'/api/admin/media/upload?contentId=unbound&kind=image',{method:'POST',headers:{Authorization:'Bearer '+token},body:form})).json();await call('/admin/resources/'+uploaded.id,{},'DELETE');await call('/admin/message-templates/image-template',{...template,document:{type:'doc',content:[{type:'image',attrs:{src:'/api/message-images/'+uploaded.id}}]}},'PUT',token,400)
 await page.goto('http://127.0.0.1:5180/#cheatsheet');await expect(manager).toBeVisible();await page.setViewportSize({width:1280,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:output+'/1280.png',animations:'disabled'})
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',filters:true,pushRecipients:true,pushCancel:true,openingTime:true,toggleStatus:true,duplicateRejected:true,concurrentPush:true,rollback:true,noRecipients:true,editorImages:['cheatsheet','category','message-template','message'],mobileImages:true,resourceProtection:true,liveMessages:0}))
}finally{await browser.close();await new Promise(r=>server.close(r));await closeDatabase()}
