import assert from 'node:assert/strict'
import { mkdtemp, mkdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, resolve } from 'node:path'
import express from 'express'
import { chromium, expect } from '@playwright/test'
import { ZodError } from 'zod'

// All writes go to a fresh database, never the developer's running backend.
process.env.APP_MODE = 'test'
process.env.DATABASE_URL = ''
process.env.LOCAL_DATABASE_DIR = await mkdtemp(join(tmpdir(), 'sxb-exam-browser-'))
process.env.MEDIA_DIR = await mkdtemp(join(tmpdir(), 'sxb-exam-media-'))
process.env.SECRET_KEY = '1'.repeat(64)
process.env.ADMIN_PHONE = '18600000000'
process.env.ADMIN_PASSWORD = 'Isolated-browser-test-42!'
const { db, closeDatabase } = await import('../apps/api/src/db.ts')
const { seed } = await import('../apps/api/src/seed.ts')
const { initSecrets, session } = await import('../apps/api/src/security.ts')
const { api } = await import('../apps/api/src/routes.ts')
const output = resolve('.local/qa/exam-projects')
await mkdir(output, { recursive: true })
let browser, server
const checks = []
try {
  await initSecrets()
  await seed()
  await db.query("INSERT INTO exam_categories(id,name,sort_order,enabled) VALUES('qa-category','测试分类',0,true)")
  const admin = (await db.query("SELECT id FROM users WHERE phone=$1 AND account_kind='admin'", [process.env.ADMIN_PHONE])).rows[0]
  const token = await session(admin.id, 'admin')
  const app = express()
  app.use(express.json({ limit: '40mb' }))
  app.use('/api', api)
  app.use((error, req, res, next) => res.status(error instanceof ZodError ? 400 : error.status || 500).json({ message: error.message }))
  app.use(express.static(resolve('apps/admin/dist')))
  server = app.listen(0, '127.0.0.1')
  await new Promise(done => server.once('listening', done))
  const origin = 'http://127.0.0.1:' + server.address().port
  browser = await chromium.launch({ channel: 'chrome', headless: true })
  const page = await browser.newPage({ viewport: { width: 1657, height: 1272 } })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setContent('<html><body style="margin:0;background:#126d58;width:120px;height:90px">QA</body></html>')
  const jpeg = await page.screenshot({ type: 'jpeg', clip: { x: 0, y: 0, width: 120, height: 90 } })
  const png = await page.screenshot({ type: 'png', clip: { x: 0, y: 0, width: 120, height: 90 } })
  await page.addInitScript(token => sessionStorage.setItem('sxb-admin-token', token), token)
  await page.goto(origin + '/#exam-projects')
  const create = page.getByRole('button', { name: '新增考试项目', exact: true })
  const drawer = page.locator('.el-drawer:visible')
  const picker = () => drawer.locator('input[type=file]')
  const preview = () => drawer.getByAltText('封面预览')
  async function closeDrawer() {
    await drawer.getByRole('button', { name: '返回', exact: true }).click()
    await expect(drawer).toHaveCount(0)
  }
  await create.click()
  await expect(drawer.getByRole('heading')).toHaveText('新增考试项目')
  await expect(drawer.getByLabel('考试名称', { exact: false })).toHaveValue('')
  await drawer.getByLabel('考试名称', { exact: false }).fill('封面回归测试')
  await drawer.locator('.el-select').click()
  await page.getByRole('option', { name: '测试分类', exact: true }).click()
  await drawer.getByRole('textbox', { name: '图文正文编辑器' }).fill('保存后仍然存在的简介')
  const chooser = page.waitForEvent('filechooser')
  await drawer.getByRole('button', { name: '选择图片', exact: true }).click()
  const fileChooser = await chooser
  const longName = '_cgi-bin_mmwebwx-bin_webwxgetmsgimg__&MsgID=1490103149024835166&skey=@crypt_' + '6408'.repeat(30) + '.jpg'
  await fileChooser.setFiles({ name: longName, mimeType: '', buffer: jpeg })
  await expect(preview()).toBeVisible()
  assert(await preview().evaluate(img => img.complete && img.naturalWidth > 0))
  assert(await drawer.evaluate(el => el.scrollWidth <= el.clientWidth + 1))
  assert(await drawer.locator('.el-drawer__body').evaluate(el => el.scrollWidth <= el.clientWidth + 1))
  assert.equal(await drawer.getByRole('button', { name: '选择图片', exact: true }).evaluate(el => el.getBoundingClientRect().height), 40)
  await page.screenshot({ path: join(output, 'desktop-cover.png'), fullPage: true })
  checks.push('native chooser; empty MIME JPEG; preview; 40px button; long filename without overflow')
  await drawer.getByRole('tab',{name:'考期',exact:true}).click()
  await drawer.getByPlaceholder('选择开始时间').fill('2090-01-01 00:00:00')
  await drawer.getByPlaceholder('选择开始时间').press('Tab')
  await drawer.getByPlaceholder('选择结束时间').fill('2090-12-31 23:59:59')
  await drawer.getByPlaceholder('选择结束时间').press('Tab')
  const saved = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().includes('/admin/exam-projects/'))
  await drawer.getByRole('button', { name: '保存', exact: true }).click()
  const response = await saved
  assert.equal(response.status(), 200, await response.text())
  await expect(drawer).toHaveCount(0)
  const records = (await db.query("SELECT * FROM exams WHERE name='封面回归测试'")).rows
  assert.equal(records.length, 1)
  assert(records[0].cover_url.startsWith('/api/message-images/'));assert.equal((await db.query('SELECT mime FROM media_assets WHERE id=$1',[records[0].cover_url.split('/').pop()])).rows[0].mime,'image/jpeg')
  assert.equal(JSON.parse(records[0].intro).content[0].content[0].text, '保存后仍然存在的简介')
  checks.push('create persists cover and serialized rich text through real API/database')
  const row = page.getByRole('row').filter({ hasText: '封面回归测试' })
  await row.getByTitle('编辑', { exact: true }).click()
  await expect(drawer.getByRole('heading')).toHaveText('编辑考试项目')
  await expect(preview()).toBeVisible()
  await expect(drawer.getByRole('textbox', { name: '图文正文编辑器' })).toContainText('保存后仍然存在的简介')
  await picker().setInputFiles({ name: 'replacement.png', mimeType: 'image/png', buffer: png })
  await expect(preview()).toHaveAttribute('src', /^\/api\/message-images\//)
  await picker().setInputFiles({ name: 'fake.jpg', mimeType: 'image/jpeg', buffer: Buffer.from('not an image') })
  await expect(drawer.getByRole('alert')).toContainText('仅支持有效的JPG、PNG图片')
  await expect(preview()).toHaveAttribute('src', /^\/api\/message-images\//)
  checks.push('PNG replacement; invalid content rejected while retaining last valid cover')
  await closeDrawer()
  await create.click()
  await expect(drawer.getByRole('heading')).toHaveText('新增考试项目')
  await expect(drawer.getByRole('alert')).toHaveCount(0)
  await expect(preview()).toHaveCount(0)
  await expect(drawer.locator('.selected-filename')).toHaveCount(0)
  await expect(drawer.getByRole('textbox', { name: '图文正文编辑器' })).toHaveText('')
  await picker().setInputFiles({ name: 'large.jpg', mimeType: 'image/jpeg', buffer: Buffer.alloc(20 * 1024 * 1024 + 1) })
  await expect(drawer.getByRole('alert')).toContainText('图片不能超过20MB')
  await picker().setInputFiles({ name: 'recovery.png', mimeType: 'image/png', buffer: png })
  await expect(preview()).toBeVisible()
  await expect(drawer.getByRole('alert')).toHaveCount(0)
  checks.push('edit-to-create resets editor, filename, image and errors; oversized image rejected; retry works')
  await closeDrawer()
  await row.getByTitle('编辑', { exact: true }).click()
  await picker().setInputFiles({ name: 'final.png', mimeType: 'image/png', buffer: png })
  await expect(preview()).toHaveAttribute('src', /^\/api\/message-images\//)
  const updated = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().includes('/admin/exam-projects/'))
  await drawer.getByRole('button', { name: '保存', exact: true }).click()
  assert.equal((await updated).status(), 200)
  await expect(drawer).toHaveCount(0)
  await page.reload()
  await row.getByTitle('编辑', { exact: true }).click()
  await expect(preview()).toHaveAttribute('src', /^\/api\/message-images\//)
  checks.push('edit save and full reload restore correct cover')
  await page.setViewportSize({ width: 390, height: 844 })
  await picker().setInputFiles({ name: longName, mimeType: '', buffer: jpeg })
  await expect(preview()).toHaveAttribute('src', /^\/api\/message-images\//)
  assert(await drawer.evaluate(el => el.scrollWidth <= el.clientWidth + 1))
  assert(await drawer.locator('.el-drawer__body').evaluate(el => el.scrollWidth <= el.clientWidth + 1))
  await page.screenshot({ path: join(output, 'mobile-cover.png'), fullPage: true })
  checks.push('390px mobile drawer with long filename has no horizontal overflow')
  await closeDrawer()
  await page.setViewportSize({ width: 1883, height: 1272 })
  await page.goto(origin + '/#exam-categories')
  const newCategory = page.getByRole('button', { name: '新增分类', exact: true })
  await newCategory.click()
  await expect(drawer.getByRole('heading')).toHaveText('新增分类')
  await expect(drawer.getByLabel('分类名称', { exact: false })).toHaveValue('')
  await drawer.getByRole('button', { name: '保存', exact: true }).click()
  await expect(drawer.getByRole('alert')).toContainText('请输入分类名称')
  await closeDrawer()
  await newCategory.click()
  await expect(drawer.getByRole('alert')).toHaveCount(0)
  await drawer.getByLabel('分类名称', { exact: false }).fill('分类新增回归')
  await drawer.getByRole('textbox', { name: '图文正文编辑器' }).fill('分类简介回归')
  const categoryChooser = page.waitForEvent('filechooser')
  await drawer.getByRole('button', { name: '选择图片', exact: true }).click()
  await (await categoryChooser).setFiles({ name: 'category.png', mimeType: 'image/png', buffer: png })
  await expect(preview()).toBeVisible()
  const categorySave = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().includes('/exam-management/categories/'))
  await drawer.getByRole('button', { name: '保存', exact: true }).click()
  assert.equal((await categorySave).status(), 200)
  await expect(drawer).toHaveCount(0)
  const categoryRow = page.getByRole('row').filter({ hasText: '分类新增回归' })
  await categoryRow.getByTitle('编辑', { exact: true }).click()
  await expect(drawer.getByRole('heading')).toHaveText('编辑分类')
  await expect(drawer.getByLabel('分类名称', { exact: false })).toHaveValue('分类新增回归')
  await expect(drawer.getByRole('textbox', { name: '图文正文编辑器' })).toContainText('分类简介回归')
  await expect(preview()).toBeVisible()
  await drawer.getByLabel('分类名称', { exact: false }).fill('分类编辑回归')
  await picker().setInputFiles({ name: 'bad.png', mimeType: 'image/png', buffer: Buffer.from('bad') })
  await expect(drawer.getByRole('alert')).toContainText('仅支持有效的JPG、PNG图片')
  await closeDrawer()
  await newCategory.click()
  await expect(drawer.getByRole('heading')).toHaveText('新增分类')
  await expect(drawer.getByLabel('分类名称', { exact: false })).toHaveValue('')
  await expect(drawer.getByRole('textbox', { name: '图文正文编辑器' })).toHaveText('')
  await expect(preview()).toHaveCount(0)
  await expect(drawer.getByRole('alert')).toHaveCount(0)
  await expect(drawer.locator('.selected-filename')).toHaveCount(0)
  await page.screenshot({ path: join(output, 'category-create.png'), fullPage: true })
  await closeDrawer()
  await categoryRow.getByTitle('编辑', { exact: true }).click()
  await expect(drawer.getByLabel('分类名称', { exact: false })).toHaveValue('分类新增回归')
  await drawer.getByLabel('分类名称', { exact: false }).fill('分类编辑回归')
  const categoryUpdate = page.waitForResponse(r => r.request().method() === 'PUT' && r.url().includes('/exam-management/categories/'))
  await drawer.getByRole('button', { name: '保存', exact: true }).click()
  assert.equal((await categoryUpdate).status(), 200)
  await expect(drawer).toHaveCount(0)
  await page.reload()
  await page.getByRole('row').filter({ hasText: '分类编辑回归' }).getByTitle('编辑', { exact: true }).click()
  await expect(drawer.getByRole('heading')).toHaveText('编辑分类')
  await expect(drawer.getByLabel('分类名称', { exact: false })).toHaveValue('分类编辑回归')
  await page.screenshot({ path: join(output, 'category-edit.png'), fullPage: true })
  checks.push('category header opens blank create drawer; create/save closes drawer and persists image and rich text')
  checks.push('category edit title and populated fields; cancel does not mutate record; create resets errors, filename, cover and rich text')
  checks.push('category edit save and reload persist changes')
  assert.deepEqual(errors, [])
  console.log(JSON.stringify({ passed: checks, screenshots: output, consoleErrors: errors }, null, 2))
} catch (error) {
  if (browser) await browser.contexts()[0]?.pages()[0]?.screenshot({ path: join(output, 'failure.png'), fullPage: true })
  throw error
} finally {
  await browser?.close()
  if (server) await new Promise(done => server.close(done))
  await closeDatabase()
}
