import assert from 'node:assert/strict'
import {mkdtemp,mkdir,writeFile} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join,resolve} from 'node:path'
import express from 'express'
import ExcelJS from 'exceljs'
import {chromium,expect} from '@playwright/test'
process.env.DATABASE_URL='';process.env.APP_MODE='test';process.env.LOCAL_DATABASE_DIR=await mkdtemp(join(tmpdir(),'sxb-imports-'));process.env.MEDIA_DIR=join(process.env.LOCAL_DATABASE_DIR,'media');process.env.SECRET_KEY='1'.repeat(64);process.env.ADMIN_PHONE='18600000000';process.env.ADMIN_PASSWORD='Import-fixture-42!'
const {db,closeDatabase}=await import('../apps/api/src/db.ts'),{seed}=await import('../apps/api/src/seed.ts'),{session,initSecrets}=await import('../apps/api/src/security.ts'),{api}=await import('../apps/api/src/routes.ts')
await initSecrets();await seed()
const actor=(await db.query("SELECT id FROM users WHERE account_kind='admin' LIMIT 1")).rows[0],token=await session(actor.id,'admin')
const app=express();app.use(express.json({limit:'40mb'}));app.use('/api',api);app.use((e,q,r,n)=>{console.error(e.message);r.status(e.status||500).json({message:e.message})});app.use(express.static(resolve('apps/admin/dist')))
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base='http://127.0.0.1:'+server.address().port
async function req(path,body,method){const r=await fetch(base+'/api'+path,{method:method||(body?'POST':'GET'),headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const json=await r.json();assert.ok(r.ok,JSON.stringify(json));return json}
async function upload(bytes,name='正式目录.xlsx'){const body=new FormData();body.append('file',new Blob([bytes]),name);const r=await fetch(base+'/api/admin/media/upload?kind=import&examId=junior-social-worker&contentId=import-fixture',{method:'POST',headers:{Authorization:'Bearer '+token},body});const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));return data}
async function template(typeId='',options){const query=new URLSearchParams({examId:'junior-social-worker',...(typeId?{typeId}:{}),...(options?{mode:options.mode,fields:options.fields.join(','),blankBehavior:options.blankBehavior}:{})});const r=await fetch(base+'/api/admin/import-jobs/template?'+query,{headers:{Authorization:'Bearer '+token}});assert.equal(r.status,200);const w=new ExcelJS.Workbook();await w.xlsx.load(Buffer.from(await r.arrayBuffer()));return w}
async function preview(asset,kind='structure',typeId,options){return req('/admin/import-jobs/preview',{examId:'junior-social-worker',assetId:asset.id,kind,typeId,isTest:false,...(options?{options}:{})})}
async function structureFile(options,rows,name='可选字段.xlsx'){const w=await template('',options);w.getWorksheet('知识目录').addRows(rows);return {w,asset:await upload(Buffer.from(await w.xlsx.writeBuffer()),name)}}
async function content(id){return (await db.query('SELECT * FROM content WHERE id=$1',[id])).rows[0]}
async function complete(job){do{job=await req('/admin/import-jobs/'+job.id+'/advance',{})}while(job.status!=='completed');return job}
let browser
try{
 const w=await template();assert.equal(w.getWorksheet('知识点对照表').getCell(1,1).value,'知识点ID');const s=w.getWorksheet('知识目录');s.addRow(['正式科目','第一章','第一节','知识点一']);s.addRow(['正式科目','第一章','第一节','知识点一']);s.addRow(['正式科目','第二章','第一节','知识点一']);s.addRow(['正式科目','','第三节','坏路径']);s.addRow(['正式科目','第三章','',''])
 const bytes=Buffer.from(await w.xlsx.writeBuffer()),a=await upload(bytes),a2=await upload(bytes);assert.notEqual(a.id,a2.id)
 const assets=(await db.query('SELECT disk_name FROM media_assets WHERE id=ANY($1::text[])',[[a.id,a2.id]])).rows;assert.equal(assets[0].disk_name,assets[1].disk_name)
 let job=await preview(a);assert.equal(job.counts.failed,1);job=await complete(job);assert.equal(job.counts.success,3);assert.equal(job.counts.skipped,1);assert.equal(job.counts.failed,1)
 const again=await complete(await preview(a2));assert.equal(again.counts.success,0);assert.equal(again.counts.skipped,4)
 const ids=job.rows.filter(r=>r.path?.length===4&&r.status==='success').map(r=>r.id);assert.equal(ids.length,2);assert.notEqual(ids[0],ids[1]);assert.equal((await req('/admin/content-origins/'+ids[0]))[0].asset_id,a2.id)
 const resource=await req('/admin/resources/'+a.id);assert.equal(resource.inUse,true);assert.ok(resource.references.some(r=>r.kind==='import-job'))
 let blocked=await fetch(base+'/api/admin/resources/'+a.id,{method:'DELETE',headers:{Authorization:'Bearer '+token}});assert.equal(blocked.status,409)
 // Same-name but different contents must have separate bytes.
 const other=await template();other.getWorksheet('知识目录').addRow(['另一个科目','','','']);const a3=await upload(Buffer.from(await other.xlsx.writeBuffer()));assert.notEqual((await db.query('SELECT disk_name FROM media_assets WHERE id=$1',[a3.id])).rows[0].disk_name,assets[0].disk_name)
 const failure=await fetch(base+'/api/admin/import-jobs/'+job.id+'/failures',{headers:{Authorization:'Bearer '+token}}),fw=new ExcelJS.Workbook();await fw.xlsx.load(Buffer.from(await failure.arrayBuffer()));assert.equal(fw.getWorksheet('知识目录').rowCount,2);assert.ok(fw.getWorksheet('失败原因'))
 const qw=await template('single'),qs=qw.getWorksheet('题目'),cols=qs.getRow(1).values.slice(1);const qvalues=cols.map(h=>h==='知识点ID（多个用逗号分隔）'?ids[0]:h==='题型'?'':h.includes('题干内容')?'导入题目唯一校验？':h.includes('正确答案')?'A':h.startsWith('选项 A')?'甲':h.startsWith('选项 B')?'乙':h.startsWith('选项 C')?'丙':h.startsWith('选项 D')?'丁':'');qs.addRow(qvalues)
 const qa=await upload(Buffer.from(await qw.xlsx.writeBuffer()),'题目.xlsx'),qj=await complete(await preview(qa,'question','single'));assert.equal(qj.counts.success,1,JSON.stringify(qj.rows));const qj2=await complete(await preview(qa,'question','single'));assert.equal(qj2.counts.skipped,1)
 const qid=qj.rows[0].id;assert.equal((await req('/admin/content?kind=question&search='+qid)).total,1)
 const p=(await db.query('SELECT * FROM content WHERE id=$1',[ids[0]])).rows[0];let result=await req('/admin/bulk-content/disable',{items:[{id:p.id,version:p.version}],testOnly:true});assert.equal(result.results[0].success,false)
 result=await req('/admin/bulk-content/disable',{items:[{id:p.id,version:p.version}]});assert.equal(result.results[0].success,true);assert.equal((await db.query('SELECT status FROM content WHERE id=$1',[p.id])).rows[0].status,'offline')
 const counts=job.counts;assert.deepEqual((await complete(job)).counts,counts);assert.equal(job.nodes.subject.created,1)
 // Actual import order survives a single transaction's identical timestamps / random IDs.
 await db.query("UPDATE content SET status='published' WHERE source='正式目录.xlsx'")
 const catalog=await req('/catalog/junior-social-worker');assert.deepEqual(catalog.knowledgeSubjects.find(s=>s.fullName==='正式科目').chapters.map(c=>c.name),['第一章','第二章','第三章'])
 // Same explicit question ID is safely skipped on reimport, not overwritten or duplicated.
 qs.getCell(2,1).value=qid;const exact=await upload(Buffer.from(await qw.xlsx.writeBuffer()),'含ID题目.xlsx');assert.equal((await complete(await preview(exact,'question','single'))).counts.skipped,1)
 // Deleting an unreferenced shared upload cannot delete the bytes used by an imported file.
 const extra=await upload(bytes,'同内容其他文件名.xlsx');await req('/admin/resources/'+extra.id,{},'DELETE');const ticket=await req('/admin/resources/'+a.id+'/preview',{});assert.equal((await fetch(base+ticket.downloadUrl)).status,200)
 // More than one chunk, concurrent retry, then resume: exactly one copy per path.
 const multi=await template();for(let n=0;n<20;n++)multi.getWorksheet('知识目录').addRow(['分批科目','章','节','知识点'+n]);const ma=await upload(Buffer.from(await multi.xlsx.writeBuffer()),'多行目录.xlsx');let mj=await preview(ma);const chunks=await Promise.all([req('/admin/import-jobs/'+mj.id+'/advance',{}),req('/admin/import-jobs/'+mj.id+'/advance',{})]);assert.ok(chunks.some(j=>j.status==='running'));mj=await complete(mj);assert.equal(mj.counts.success,20);assert.equal(mj.nodes.subject.created,1)
 // Selected fields create dynamic templates. Shared new parents receive a consistent value,
 // even when only a later row supplies the optional short title.
 const createOptions={mode:'create',fields:['stars','shortTitle','document'],blankBehavior:'keep'}
 const selected=await structureFile(createOptions,[['字段科目','章一','节一','点一',2,'','第一段\n第二段'],['字段科目','章一','节一','点二',4,'字段简称','正文二']]);assert.deepEqual(selected.w.getWorksheet('知识目录').getRow(1).values.slice(1),['科目名称','章名称','节名称','知识点名称','知识点星级','科目短标题','知识点正文']);assert.ok(selected.w.getWorksheet('节点对照表'))
 let selectedJob=await preview(selected.asset,'structure',undefined,createOptions);assert.equal(selectedJob.planned.create,2);selectedJob=await complete(selectedJob);assert.equal(selectedJob.counts.success,2,JSON.stringify(selectedJob.rows));const first=selectedJob.rows[0].id,second=selectedJob.rows[1].id,subject=selectedJob.rows[0].nodes[0].id
 assert.equal((await content(subject)).payload.shortTitle,'字段简称');assert.equal((await content(first)).payload.stars,2);assert.equal((await content(first)).payload.content,'第一段\n第二段')
 // Updating stars changes no other payload fields, status, source, ownership or test flags.
 const updateOptions={mode:'update',fields:['stars'],blankBehavior:'keep'},before=await content(first),secondBefore=await content(second)
 const starFile=await structureFile(updateOptions,[[first,5],[second,''],['mid-point-test',3],[first+'-missing',1],['',2],[second,6]],'星级更新.xlsx')
 assert.deepEqual(starFile.w.getWorksheet('知识目录').getRow(1).values.slice(1),['节点ID','知识点星级'])
 let stars=await preview(starFile.asset,'structure',undefined,updateOptions);assert.equal(stars.planned.update,1);assert.equal(stars.planned.unchanged,1);assert.equal(stars.counts.failed,4,JSON.stringify(stars.rows));assert.deepEqual(stars.rows[0].changes.map(c=>[c.label,c.before,c.after]),[['知识点星级',2,5]])
 stars=await complete(stars);assert.equal(stars.counts.success,1);assert.equal(stars.counts.skipped,1);const after=await content(first);assert.deepEqual(after.payload,{...before.payload,stars:5});assert.equal(after.version,before.version+1);for(const k of ['status','source','is_test_data','parent_id','exam_id'])assert.equal(after[k],before[k]);assert.deepEqual((await content(second)).payload,secondBefore.payload);assert.equal((await req('/admin/content-origins/'+first))[0].asset_id,starFile.asset.id)
 // Repeating the same updates is idempotent; no unnecessary revision increments.
 const repeated=await complete(await preview(starFile.asset,'structure',undefined,updateOptions));assert.equal(repeated.counts.success,0);assert.equal((await content(first)).version,after.version)
 // A mismatched selected-field template cannot silently drop columns.
 let invalid=await fetch(base+'/api/admin/import-jobs/preview',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({examId:'junior-social-worker',assetId:starFile.asset.id,kind:'structure',options:{...updateOptions,fields:['document']}})});assert.equal(invalid.status,400)
 // Empty values clear only after explicit opt-in; unselected body and short title survive.
 const clearOptions={...updateOptions,blankBehavior:'clear'},clearFile=await structureFile(clearOptions,[[first,'']]);let clearing=await preview(clearFile.asset,'structure',undefined,clearOptions);assert.equal(clearing.rows[0].changes[0].after,null);clearing=await complete(clearing);assert.equal(clearing.counts.success,1);const cleared=await content(first);assert.ok(!('stars' in cleared.payload));assert.deepEqual(cleared.payload.document,before.payload.document)
 // Body import preserves paragraphs, while leaving all other payload fields intact.
 const bodyOptions={...updateOptions,fields:['document']},bodyFile=await structureFile(bodyOptions,[[first,'新的正文\n下一段']]);const bodyJob=await complete(await preview(bodyFile.asset,'structure',undefined,bodyOptions));assert.equal(bodyJob.counts.success,1);assert.equal((await content(first)).payload.content,'新的正文\n下一段');assert.equal((await content(first)).payload.document.content.length,2)
 // Subject short title uses the subject ID. Fields for a different level fail per row.
 const shortOptions={...updateOptions,fields:['shortTitle']},shortFile=await structureFile(shortOptions,[[subject,'新简称'],[first,'错误层级']]);const shortJob=await complete(await preview(shortFile.asset,'structure',undefined,shortOptions));assert.equal(shortJob.counts.success,1);assert.equal(shortJob.counts.failed,1);assert.equal((await content(subject)).payload.shortTitle,'新简称')
 // Conflicting duplicate rows must fail together, never apply the first value silently.
 const conflictFile=await structureFile(updateOptions,[[first,1],[first,2]]);const conflict=await complete(await preview(conflictFile.asset,'structure',undefined,updateOptions));assert.equal(conflict.counts.failed,2);assert.equal(conflict.counts.success,0)
 const parentConflict=await structureFile(createOptions,[['冲突科目','章','节','点一',1,'简称一',''],['冲突科目','章','节','点二',1,'简称二','']]);assert.equal((await preview(parentConflict.asset,'structure',undefined,createOptions)).counts.failed,2)
 // Version changes after preview fail safely. Failed files retain the exact selected template.
 const staleFile=await structureFile(updateOptions,[[first,3]]);let stale=await preview(staleFile.asset,'structure',undefined,updateOptions);await db.query('UPDATE content SET payload=$2,version=version+1 WHERE id=$1',[first,JSON.stringify({...((await content(first)).payload),stars:4})]);stale=await complete(stale);assert.equal(stale.counts.failed,1);assert.match(stale.rows[0].message,/预览后内容已被修改/);assert.equal((await content(first)).payload.stars,4)
 const retryResponse=await fetch(base+'/api/admin/import-jobs/'+stale.id+'/failures',{headers:{Authorization:'Bearer '+token}}),retryBook=new ExcelJS.Workbook();await retryBook.xlsx.load(Buffer.from(await retryResponse.arrayBuffer()));assert.deepEqual(retryBook.getWorksheet('知识目录').getRow(1).values.slice(1),['节点ID','知识点星级']);assert.deepEqual(JSON.parse(retryBook.getWorksheet('导入设置').getCell(1,2).value),updateOptions);const retryAsset=await upload(Buffer.from(await retryBook.xlsx.writeBuffer()),'修正星级.xlsx');assert.equal((await complete(await preview(retryAsset,'structure',undefined,updateOptions))).counts.success,1)
 // Updating ignores the create-only test marker, preserving the real record's classification.
 const keepTestFile=await structureFile(updateOptions,[[first,2]]);const keepTest=await req('/admin/import-jobs/preview',{examId:'junior-social-worker',assetId:keepTestFile.asset.id,kind:'structure',isTest:true,options:updateOptions});assert.equal((await complete(keepTest)).counts.success,1);assert.equal((await content(first)).is_test_data,false)
 // Restarting seed after explicit maintenance must not recreate any demo content or templates.
 await db.query("INSERT INTO system_settings(key,value) VALUES('demo_seed_disabled','true') ON CONFLICT(key) DO UPDATE SET value='true'");await db.query("DELETE FROM message_templates WHERE id='weekly-plan'");await seed();assert.equal((await db.query("SELECT id FROM message_templates WHERE id='weekly-plan'")).rows.length,0)
 const out=resolve('.local/qa/import-workflow');await mkdir(out,{recursive:true});await writeFile(join(out,'fixture.xlsx'),bytes)
 browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1488,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(t=>sessionStorage.setItem('sxb-admin-token',t),token);await page.goto(base+'/#knowledge-graph');await page.locator('.grid button').filter({hasText:'初级社会工作师'}).click();await page.locator('.heading-actions').getByRole('button',{name:'导入',exact:true}).click();const dialog=page.locator('.el-dialog:visible');await expect(dialog.getByRole('heading',{name:'导入知识结构'})).toBeVisible();await expect(dialog.getByRole('combobox',{name:'考试项目'})).toBeDisabled();await dialog.locator('input[type=file]').setInputFiles(join(out,'fixture.xlsx'));await expect(dialog.getByText('确认导入有效内容')).toBeVisible();await page.screenshot({path:join(out,'preview.png'),animations:'disabled'});await dialog.getByRole('button',{name:'确认导入有效内容'}).click();await expect(dialog.getByRole('button',{name:'完成',exact:true})).toBeVisible();await page.screenshot({path:join(out,'result.png')});await dialog.getByRole('button',{name:'完成',exact:true}).click();await page.locator('.heading-actions').getByRole('button',{name:'批量操作'}).click();await expect(page.getByRole('button',{name:'停用全部筛选结果'})).toBeVisible();await page.screenshot({path:join(out,'bulk.png')});assert.deepEqual(errors,[])
 // Bulk UI defaults to all data, locks the current exam, and handles cancel/confirm/restore.
 await expect(dialog.getByRole('combobox',{name:'数据标记',exact:true})).toHaveAttribute('aria-expanded','false');await expect(dialog.getByRole('combobox',{name:'考试项目',exact:true})).toBeDisabled();await expect(dialog.getByText('全部内容',{exact:true})).toBeVisible()
 await dialog.getByPlaceholder('搜索标题或唯一 ID').fill(first);await dialog.getByRole('button',{name:'查询',exact:true}).click();await expect(dialog.getByText('当前筛选共 1 条',{exact:false})).toBeVisible()
 await dialog.getByRole('button',{name:'停用全部筛选结果'}).click();await page.getByRole('button',{name:'取消',exact:true}).click();assert.equal((await content(first)).status,'draft')
 await dialog.getByRole('button',{name:'停用全部筛选结果'}).click();await page.getByRole('button',{name:'确认停用',exact:true}).click();await expect(dialog.getByText('成功 1 条，失败 0 条')).toBeVisible();assert.equal((await content(first)).status,'offline')
 await expect(dialog.getByRole('combobox',{name:'批量操作类型'})).toBeEnabled();await dialog.locator('.bulk-buttons .el-select').click();for(const label of ['启用','停用','发布','转为草稿','提交审核'])await expect(page.getByRole('option',{name:label,exact:true})).toBeVisible();await expect(page.getByRole('option',{name:'上架',exact:true})).toHaveCount(0);await expect(page.getByRole('option',{name:'下架',exact:true})).toHaveCount(0);await page.getByRole('option',{name:'启用',exact:true}).click()
 await dialog.getByRole('button',{name:'启用全部筛选结果'}).click();await page.getByRole('button',{name:'确认启用',exact:true}).click();await expect(dialog.getByText('已启用（草稿）',{exact:true})).toBeVisible();assert.equal((await content(first)).status,'draft');await page.screenshot({path:join(out,'bulk-actions.png'),animations:'disabled'})
 // Browser field selection changes template columns and retains options when retrying.
 await dialog.locator('.el-dialog__headerbtn').click();await page.locator('.heading-actions').getByRole('button',{name:'导入',exact:true}).click();await dialog.getByText('更新已有内容',{exact:true}).click();await expect(dialog.getByRole('button',{name:'下载对应模板'})).toBeDisabled();await dialog.getByText('知识点星级',{exact:true}).click();await expect(dialog.locator('.template-columns')).toHaveText('本次模板列节点ID知识点星级');await expect(dialog.getByRole('button',{name:'下载对应模板'})).toBeEnabled();await expect(dialog.getByRole('checkbox',{name:'标记为测试内容'})).toHaveCount(0)
 const browserUpdateFile=join(out,'star-update.xlsx');await writeFile(browserUpdateFile,Buffer.from(await starFile.w.xlsx.writeBuffer()));await dialog.locator('input[type=file]').setInputFiles(browserUpdateFile);await expect(dialog.getByText('将更新选中字段')).toBeVisible();await expect(dialog.locator('.value-before').first()).toHaveText('原值：2');await expect(dialog.locator('.value-after').first()).toHaveText('新值：5');await page.screenshot({path:join(out,'selected-fields-preview.png'),animations:'disabled'});await dialog.getByRole('button',{name:'确认导入有效内容'}).click();await expect(dialog.getByRole('button',{name:'完成',exact:true})).toBeVisible();await dialog.getByRole('button',{name:'上传修正文件 / 重新导入'}).click();await expect(dialog.getByRole('radio',{name:'更新已有内容',exact:true})).toBeChecked();await expect(dialog.getByRole('checkbox',{name:'知识点星级',exact:true})).toBeChecked();await expect(dialog.getByRole('radio',{name:'保留原值（推荐）',exact:true})).toBeChecked();await page.screenshot({path:join(out,'selected-fields.png'),animations:'disabled'});assert.deepEqual(errors,[])
 console.log('PASS: import hierarchy, selected fields, safe updates, empty values, concurrent edits, sources, resources, failures, question imports, ID search, bulk safety, browser wizard')
}finally{await browser?.close();await new Promise(r=>server.close(r));await closeDatabase()}
