import 'dotenv/config'
import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { chromium, expect } from '@playwright/test'
// Live smoke check: no content/order/learning writes. Authentication uses the existing local admin.
const output=resolve('.local/qa/knowledge-live')
await mkdir(output,{recursive:true})
const browser=await chromium.launch({channel:'chrome',headless:true})
try{
  const page=await browser.newPage({viewport:{width:1657,height:1100}})
  const errors=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('http://127.0.0.1:5180/#knowledge-graph')
  await page.getByPlaceholder('请输入手机号').fill(process.env.ADMIN_PHONE)
  await page.getByPlaceholder('请输入密码').fill(process.env.ADMIN_PASSWORD)
  await page.getByRole('button',{name:'登录',exact:true}).click()
  const first=page.locator('.grid button').filter({hasText:'初级社会工作师'})
  await expect(first).toBeVisible()
  await first.click()
  await expect(page.getByRole('tab',{name:'列表管理'})).toHaveAttribute('aria-selected','true')
  await expect(page.locator('.el-table__row').first()).toBeVisible()
  assert.deepEqual(await page.locator('.el-alert--error:visible').allTextContents(),[])
  await expect(page.locator('.el-loading-mask:visible')).toHaveCount(0)
  await page.screenshot({path:resolve(output,'admin-live.png'),fullPage:true})
  const rows=await page.locator('.el-table__row').count()
  await page.locator('.el-table__row').first().getByRole('button',{name:'编辑内容'}).click()
  await expect(page.locator('.el-drawer:visible')).toContainText('课程管理')
  await page.getByRole('button',{name:'取消',exact:true}).click()
  await page.goto('http://127.0.0.1:5180/#exam-projects')
  await page.getByRole('button',{name:'新增考试项目',exact:true}).click()
  await expect(page.locator('.el-drawer:visible').getByRole('heading')).toHaveText('新增考试项目')
  await page.locator('.el-drawer:visible').getByRole('button',{name:'返回',exact:true}).click()
  await page.goto('http://127.0.0.1:5180/#exam-categories')
  await page.getByRole('button',{name:'新增分类',exact:true}).click()
  await expect(page.locator('.el-drawer:visible').getByRole('heading')).toHaveText('新增分类')
  assert.deepEqual(errors,[])
  const mobile=await browser.newPage({viewport:{width:390,height:844}})
  const mobileErrors=[];mobile.on('pageerror',e=>mobileErrors.push(e.message))
  await mobile.goto('http://127.0.0.1:5174/#/pages/knowledge/index')
  await expect(mobile.getByText('学习数据未能加载',{exact:true})).toHaveCount(0)
  const response=await mobile.request.get('http://127.0.0.1:4310/api/catalog/junior-social-worker')
  assert.equal(response.status(),200)
  const data=await response.json()
  assert(data.knowledgeSubjects.length)
  await expect(mobile.getByText(data.knowledgeSubjects[0].name,{exact:true}).first()).toBeVisible({timeout:20000})
  await expect(mobile.locator('uni-toast:visible')).toHaveCount(0)
  await mobile.screenshot({path:resolve(output,'mobile-live.png'),fullPage:true})
  assert.deepEqual(mobileErrors,[])
  console.log(JSON.stringify({status:'PASS',adminRowsOnPage:rows,publicSubjects:data.knowledgeSubjects.length,publicQuestions:data.practiceQuestions.length,publicCourses:data.courseCatalog.length,contentWrites:0}))
}finally{await browser.close()}
