import assert from 'node:assert/strict'
import {mkdir} from 'node:fs/promises'
import {execFileSync} from 'node:child_process'
import {chromium,expect} from '@playwright/test'
import {profileFixture} from './helpers/user-profile-fixture.ts'

const f=await profileFixture(),origin='http://127.0.0.1:5174'
let browser
try{
 await f.db.query("UPDATE content SET title=CASE id WHEN 'a-s' THEN '社会工作综合能力' WHEN 'a-c' THEN '社会工作服务的内涵' WHEN 'a-t' THEN '社会工作服务的目标与功能' WHEN 'a-k' THEN '社会工作服务的内涵与特征' WHEN 'a-k2' THEN '社会工作服务的基本目标' ELSE title END,payload=payload||'{\"no\":1,\"stars\":4}'::jsonb WHERE id=ANY($1::text[])",[['a-s','a-c','a-t','a-k','a-k2']])
 await f.db.query("UPDATE content SET payload=payload||$2::jsonb WHERE id=$1",['a-k',JSON.stringify({document:{type:'doc',content:[{type:'paragraph',content:[{type:'text',text:'社会工作是一种帮助人和解决社会问题的工作。以专业知识与方法，回应个人、家庭和社区的需要。'}]},{type:'heading',attrs:{level:2},content:[{type:'text',text:'把握三个关键词'}]},{type:'paragraph',content:[{type:'text',text:'助人自助、专业方法、人与环境。理解这些关键词，比孤立记忆定义更重要。'}]}]}})])
 for(const [id,type,title,parent] of [['detail-article','article','从生活情境理解社会工作','a-k'],['detail-video','video','社会工作核心概念精讲','a-k'],['detail-audio','audio','通勤听一遍：核心概念','a-k'],['detail-premium','article','第一节 · 社会工作目标与功能精讲','a-t']]){
  await f.db.query("INSERT INTO content(id,exam_id,kind,parent_id,title,status,payload) VALUES($1,$2,'course',$3,$4,'published',$5)",[id,f.exam,parent,title,JSON.stringify({type,totalMinutes:12,content:'配套图文课程正文：从社区服务案例理解助人自助。\n\n'+Array(8).fill('社会工作以专业知识与方法回应个人、家庭和社区的需要。服务过程中，既要帮助服务对象解决眼前的问题，也要尊重其意愿，支持其运用自身与环境中的资源，逐步形成自主解决问题的能力。').join('\n\n')})])
 }

 // Public metadata never leaks protected article text; draft/offline restores the saved original.
 const before=await f.call('/knowledge-content/a-k',200,'')
 assert.equal(before.bodySource,'supporting-article');assert.deepEqual(before.bodyCourseIds,['detail-article']);assert.deepEqual(before.blocks,[])
 assert.ok(!JSON.stringify(before).includes('配套图文课程正文'))
 await f.db.query("UPDATE content SET status='offline' WHERE id='detail-article'")
 const fallback=await f.call('/knowledge-content/a-k',200,'')
 assert.equal(fallback.bodySource,'knowledge');assert.ok(JSON.stringify(fallback.blocks).includes('把握三个关键词'))
 await f.db.query("UPDATE content SET status='published' WHERE id='detail-article'")
 const bodyRow=(await f.db.query("SELECT payload FROM content WHERE id='a-k'")).rows[0]
 assert.ok(JSON.stringify(bodyRow.payload).includes('把握三个关键词'))
 browser=await chromium.launch({channel:'chrome',headless:true})
 const context=await browser.newContext({viewport:{width:390,height:844},reducedMotion:'reduce'})
 await context.addInitScript(({token,exam})=>{localStorage.setItem('sxb-api-token',JSON.stringify({type:'string',data:token}));localStorage.setItem('sxb-current-exam',JSON.stringify({type:'object',data:{id:exam,name:'初级社会工作师'}}))},{token:f.student,exam:f.exam})
 await context.route('**/api/**',async route=>{const u=new URL(route.request().url());if(!u.pathname.startsWith('/api/'))return route.continue();await route.fulfill({response:await route.fetch({url:f.origin+u.pathname+u.search})})})
 await context.route('**/api/knowledge-content/a-k/member',async route=>{const r=await route.fetch({url:f.origin+'/api/knowledge-content/a-k/member'}),data=await r.json();await route.fulfill({json:{...data,handouts:[{assetId:'qa-locked-handout',title:'核心概念复习讲义',fileType:'PDF',sizeBytes:102400,locked:true}]}})})
 const page=await context.newPage(),errors=[]
 page.on('pageerror',e=>errors.push(e.message))
 page.on('console',m=>{if(m.type()==='error'&&/TypeError|Unhandled|Cannot .* null/.test(m.text()))errors.push(m.text())})
 const url=origin+'/#/pages/knowledge-detail/index?id=a-k'

 // Generate test media in memory; nothing is uploaded into the application database.
 const videoBytes=execFileSync('ffmpeg',['-hide_banner','-loglevel','error','-f','lavfi','-i','color=c=0x223d61:s=640x360:d=1','-c:v','libvpx','-f','webm','pipe:1'])
 const samples=8000*10,wav=Buffer.alloc(44+samples*2)
 wav.write('RIFF');wav.writeUInt32LE(36+samples*2,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(8000,24);wav.writeUInt32LE(16000,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(samples*2,40)
 await context.route('**/api/courses/detail-video',route=>route.fulfill({json:{id:'detail-video',type:'video',title:'视频课程',mediaUrl:'/qa/video.webm',handoutDownloadPath:'/courses/detail-video/handout'}}))
 await context.route('**/api/courses/detail-audio',route=>route.fulfill({json:{id:'detail-audio',type:'audio',title:'通勤听一遍：核心概念',mediaUrl:'/qa/audio.wav'}}))
 await context.route('**/qa/video.webm',route=>route.fulfill({contentType:'video/webm',body:Buffer.from(videoBytes)}))
 await context.route('**/qa/audio.wav',route=>route.fulfill({contentType:'audio/wav',body:wav}))
 await page.goto(url)
 await expect(page.locator('.reader-title')).toHaveText('社会工作服务的内涵与特征',{timeout:20000}).catch(async e=>{console.log(await page.locator('body').innerText(),errors);throw e})
 await expect(page.locator('.reader-hero')).not.toContainText('掌握')
 await expect(page.locator('.inline-course')).toHaveCount(3)
 await expect(page.locator('.reader-note,.pagination-title,.reader-nav .directory-button')).toHaveCount(0)
 await expect(page.locator('.premium-entry')).toHaveCount(1)
 await expect(page.locator('.reading-section')).toContainText('配套图文课程正文')
 await expect(page.locator('.reading-section')).not.toContainText('把握三个关键词')
 await expect(page.locator('.learning-tabs,.media-choices,.course-download')).toHaveCount(0)
 await expect(page.locator('.handout-pill')).toHaveText('下载讲义')
 assert.deepEqual((await page.locator('.course-tag').allTextContents()).sort(),['图文课','视频课','音频课'].sort())
 const mediaBox=await page.locator('.reader-media-top').boundingBox(),navBox=await page.locator('.reader-nav').boundingBox(),titleBox=await page.locator('.reader-title').boundingBox()
 assert.equal(mediaBox.y,0);assert.ok(navBox.y+navBox.height<mediaBox.y+mediaBox.height);assert.ok(titleBox.y>=mediaBox.y+mediaBox.height)
 await expect(page.locator('.reading-excerpt')).toHaveClass(/folded/)
 async function expectOneScreen(){
  await expect(page.locator('.reading-excerpt')).toHaveClass(/folded/)
  await expect.poll(()=>page.evaluate(()=>{
   const root=document.querySelector('.knowledge-reader').getBoundingClientRect(),extras=document.querySelector('.reading-extras').getBoundingClientRect(),footer=document.querySelector('.reader-tools').getBoundingClientRect()
   return Math.max(Math.abs(root.height-innerHeight),Math.abs(footer.top-extras.bottom-20))
  })).toBeLessThan(2)
 }
 await expectOneScreen()
 await page.locator('.excerpt-toggle').click();await expect(page.locator('.excerpt-toggle')).toHaveAttribute('aria-expanded','true')
 await page.locator('.excerpt-toggle').click();await expect(page.locator('.excerpt-toggle')).toHaveAttribute('aria-expanded','false')
 await expect(page.locator('.directory-button .reader-tool-art')).toHaveCount(1)
 await expect(page.locator('.note-button .reader-tool-art')).toHaveCount(1)
 await page.locator('.handout-pill').click()
 await expect(page.locator('.handout-choice')).toHaveCount(2)
 // Course handouts keep their protected endpoint and verification target.
 let downloadTarget='',downloadRequests=0
 await context.route('**/api/verification/challenge',route=>{downloadTarget=route.request().postDataJSON().target;return route.fulfill({json:{mode:'frontend',required:false}})})
 await context.route('**/api/courses/detail-video/handout',route=>{downloadRequests++;return route.fulfill({status:403,json:{message:'当前考试下载权限不足'}})})
 await page.locator('.handout-choice').filter({hasText:'视频课程 · 讲义'}).click()
 await expect(page.locator('.handout-error')).toHaveText('当前考试下载权限不足')
 assert.equal(downloadTarget,'course:detail-video');assert.equal(downloadRequests,1)
 await context.unroute('**/api/verification/challenge');await context.unroute('**/api/courses/detail-video/handout')
 // Cancelling verification is a normal dismissal, and must not trigger a download or error.
 await context.route('**/api/verification/challenge',route=>route.fulfill({json:{mode:'frontend',required:true}}))
 await context.route('**/api/courses/detail-video/handout',route=>{downloadRequests++;return route.fulfill({status:403,json:{message:'不应发起下载'}})})
 await page.locator('.handout-choice').filter({hasText:'视频课程 · 讲义'}).click()
 await page.locator('.verify-heading [aria-label="取消验证"]').click()
 await expect(page.locator('.verify-mask,.handout-error')).toHaveCount(0)
 assert.equal(downloadRequests,1)
 await context.unroute('**/api/verification/challenge');await context.unroute('**/api/courses/detail-video/handout')
 await page.locator('.handout-choice').filter({hasText:'核心概念复习讲义'}).click()
 await expect(page.locator('uni-modal')).toContainText('下载讲义需要对应考试的会员权限')
 await page.locator('.uni-modal__btn').filter({hasText:'取消'}).click()
 await expect(page.locator('uni-modal')).toBeHidden()
 await page.keyboard.press('Escape')
 await expect(page.locator('.reading-sheet')).toHaveCount(0)
 await expect(page.locator('.inline-course video')).toHaveCount(1).catch(async e=>{console.log('media bytes',videoBytes.length,await page.locator('.inline-course').allInnerTexts());throw e})
 await expect.poll(()=>page.locator('.inline-course video').evaluate(v=>v.readyState)).toBeGreaterThan(0)
 assert.equal(await page.locator('.inline-course video').evaluate(v=>v.paused),true)
 await expect(page.locator('.reading-audio')).toBeVisible()
 await page.getByRole('button',{name:'播放音频',exact:true}).click()
 await expect(page.getByRole('button',{name:'暂停音频',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'暂停音频',exact:true}).click()
 await expect(page.getByRole('button',{name:'播放音频',exact:true})).toBeVisible()
 // Save/read/remove use the real isolated backend, including a failed save retaining the draft.
 await page.locator('.note-button').click()
 await page.locator('.note-editor textarea').fill('用社区服务的案例记住助人自助。')
 await context.route('**/api/records/'+f.exam,route=>route.request().method()==='PUT'?route.fulfill({status:503,json:{message:'保存暂不可用'}}):route.fallback())
 await page.locator('.save-note').click()
 await expect(page.locator('.note-error')).toHaveText('保存暂不可用')
 await expect(page.locator('.note-editor textarea')).toHaveValue('用社区服务的案例记住助人自助。')
 await context.unroute('**/api/records/'+f.exam)
 await page.locator('.save-note').click()
 await expect(page.locator('.reading-sheet')).toHaveCount(0)
 await expect(page.locator('.note-dot')).toBeVisible()
 await page.locator('.favorite-button').click()
 await expect(page.locator('.favorite-button')).toHaveAttribute('aria-pressed','true')
 await page.reload()
 await expect(page.locator('.note-dot')).toBeVisible({timeout:20000})
 await page.locator('.note-button').click()
 await expect(page.locator('.note-editor textarea')).toHaveValue('用社区服务的案例记住助人自助。')
 await page.keyboard.press('Escape')
 await expect(page.locator('.favorite-button')).toHaveAttribute('aria-pressed','true')
 await page.locator('.favorite-button').click()
 await expect(page.locator('.favorite-button')).toHaveAttribute('aria-pressed','false')
 // All data must stay within this user's exam scope.
 const notes=(await f.db.query("SELECT exam_id,payload FROM user_records WHERE user_id=$1 AND kind='note' AND source_id='knowledge:a-k'",[f.uid])).rows
 assert.equal(notes.length,1);assert.equal(notes[0].exam_id,f.exam)
 await page.locator('.practice-button').click()
 await expect(page).toHaveURL(/practice-session.*knowledgePointId=a-k/)
 await page.locator('.session-top .back-button').click()
 await expect(page.locator('.reader-title')).toBeVisible()
 await page.locator('.premium-entry').click()
 await expect(page).toHaveURL(/course-detail.*detail-premium/)
 await page.goBack()
 await expect(page.locator('.reader-title')).toBeVisible()
 await page.locator('.directory-button').click()
 await expect(page.locator('.directory-point.current')).toContainText('社会工作服务的内涵与特征')
 await page.locator('.directory-point').filter({hasText:'社会工作服务的基本目标'}).click()
 await expect(page).toHaveURL(/id=a-k2/)
 await expect(page.locator('.reader-media')).toHaveCount(0)
 await page.reload()
 await expect(page.locator('.reader-title')).toHaveText('社会工作服务的基本目标',{timeout:20000})
 await expect(page.locator('.handout-pill')).toHaveCount(0)
 await expect(page.locator('.reader-nav-label')).toHaveText('知识点')
 await expect(page.locator('.knowledge-reader')).toHaveClass(/knowledge-only/)
 await page.screenshot({path:'.local/qa/knowledge-detail/reference-knowledge.png'})
 await page.locator('.previous-point').click()
 await expect(page).toHaveURL(/id=a-k$/)
 await expect(page.locator('.reader-title')).toHaveText('社会工作服务的内涵与特征')
 await mkdir('.local/qa/knowledge-detail',{recursive:true})
 for(const [width,height] of [[320,667],[375,667],[390,844],[430,932],[812,375]]){
  await page.setViewportSize({width,height})
  await page.evaluate(()=>window.scrollTo(0,0))
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal page overflow')
  const tools=await page.locator('.reader-tools').boundingBox();assert.ok(tools.y+tools.height<=height+1)
  await page.screenshot({path:'.local/qa/knowledge-detail/reader-'+width+'.png',fullPage:true})
 }
 await page.setViewportSize({width:390,height:844})
 // Verify the actual one-video/one-audio layouts as well as the no-media case.
 await f.db.query("UPDATE content SET status='offline' WHERE id='detail-audio'")
 await page.reload()
 await expect(page.locator('.reader-title')).toBeVisible({timeout:20000})
 await expect(page.locator('.handout-pill')).toBeVisible()
 await expect(page.locator('.reading-excerpt')).toHaveClass(/folded/)
 await expect(page.locator('uni-toast')).toBeHidden()
 await expectOneScreen()
 await page.screenshot({path:'.local/qa/knowledge-detail/reference-video.png'})
 const pillBox=await page.locator('.handout-pill').boundingBox(),infoBox=await page.locator('.reader-info-row').boundingBox()
 assert.ok(pillBox.width<130&&pillBox.x>infoBox.x+infoBox.width/2,'Download is a compact right-aligned pill')
 await f.db.query("UPDATE content SET status=CASE id WHEN 'detail-video' THEN 'offline' ELSE 'published' END WHERE id=ANY($1::text[])",[['detail-video','detail-audio']])
 await page.reload()
 await expect(page.locator('.reading-audio')).toBeVisible({timeout:20000})
 await expect(page.locator('.reading-excerpt')).toHaveClass(/folded/)
 await expect(page.locator('uni-toast')).toBeHidden()
 await expectOneScreen()
 await page.screenshot({path:'.local/qa/knowledge-detail/reference-audio.png'})
 await f.db.query("UPDATE content SET status='offline' WHERE id='detail-audio'")
 await page.reload()
 await expect(page.locator('.reader-title')).toBeVisible({timeout:20000})
 await expect(page.locator('.reader-media-top,.media-overlay')).toHaveCount(0)
 assert.ok(await page.locator('.reader-hero').evaluate(e=>getComputedStyle(e).backgroundImage.includes('reader-letter-texture.svg')))
 await expect(page.locator('.reader-nav-label')).toHaveText('图文课程')
 await expect(page.locator('.course-tag')).toHaveText(['图文课'])
 await expect(page.locator('.reading-excerpt')).toHaveClass(/folded/)
 await expect(page.locator('uni-toast')).toBeHidden()
 await expectOneScreen()
 await page.screenshot({path:'.local/qa/knowledge-detail/reference-article.png'})
 // Different screen heights should reveal more/less real content, keeping actions in the first screen.
 for(const [width,height] of [[320,568],[375,667],[390,844],[430,932],[430,1200]]){
  await page.setViewportSize({width,height});await expectOneScreen()
  await page.screenshot({path:'.local/qa/knowledge-detail/folded-'+width+'-'+height+'.png'})
 }
 await page.locator('.excerpt-toggle').click()
 await expect(page.locator('.excerpt-toggle')).toHaveAttribute('aria-expanded','true')
 assert.ok(await page.locator('.knowledge-reader').evaluate(e=>e.getBoundingClientRect().height>innerHeight))
 await page.locator('.excerpt-toggle').click()
 await expectOneScreen()
 await page.setViewportSize({width:390,height:844});await expectOneScreen()
 await f.db.query("UPDATE content SET payload=payload||$1::jsonb WHERE id='detail-article'",[JSON.stringify({content:'配套图文课程正文：从社区服务案例理解助人自助。'})])
 await page.reload()
 await expect(page.locator('.reading-section')).toContainText('配套图文课程正文')
 await expect(page.locator('.reading-excerpt')).not.toHaveClass(/folded/)
 await expect(page.locator('.excerpt-toggle')).toHaveCount(0)
 await f.db.query("UPDATE content SET status='published' WHERE id=ANY($1::text[])",[['detail-video','detail-audio']])
 await page.locator('.note-button').click()
 const closeBox=await page.locator('.sheet-close').boundingBox(),headingBox=await page.locator('.sheet-heading').boundingBox()
 assert.ok(Math.abs(closeBox.y+closeBox.height/2-headingBox.y-headingBox.height/2)<1,'Close button vertically centered')
 assert.equal(await page.locator('.sheet-close .uni-icons').evaluate(e=>getComputedStyle(e).fontSize),'19px')
 await page.screenshot({path:'.local/qa/knowledge-detail/note-sheet.png'})
 await page.keyboard.press('Escape')
 await expect(page.locator('.reading-sheet')).toHaveCount(0)
 await page.locator('.note-button').click()
 await page.locator('.delete-note').click()
 await page.locator('.uni-modal__btn').filter({hasText:'删除'}).click()
 await expect(page.locator('.note-summary')).toHaveCount(0)
 assert.equal((await f.db.query("SELECT id FROM user_records WHERE user_id=$1 AND kind='note' AND source_id='knowledge:a-k'",[f.uid])).rows.length,0)
 // Real API rejects courses without appropriate rights.
 await context.route('**/api/courses/detail-article',route=>route.fulfill({status:403,json:{message:'当前考试会员权限不足'}}))
 await page.reload()
 await expect(page.locator('.inline-article')).toContainText('当前考试会员权限不足',{timeout:20000})
 await expect(page.locator('.inline-article .study-content')).toHaveCount(0)
 const guest=await browser.newContext({viewport:{width:390,height:844}})
 await guest.route('**/api/**',async route=>{const u=new URL(route.request().url());if(!u.pathname.startsWith('/api/'))return route.continue();await route.fulfill({response:await route.fetch({url:f.origin+u.pathname+u.search})})})
 const guestPage=await guest.newPage()
 await guestPage.goto(url)
 await expect(guestPage.locator('.reader-title')).toBeVisible({timeout:20000})
 await expect(guestPage.locator('.inline-article')).toContainText('登录后查看')
 await guestPage.locator('.favorite-button').click()
 await expect(guestPage).toHaveURL(/pages\/login\/index/)
 await guestPage.getByRole('button',{name:'返回',exact:true}).click()
 await expect(guestPage.locator('.reader-title')).toBeVisible()
 await guest.unrouteAll({behavior:'wait'});await guest.close()
 assert.deepEqual(errors,[])
 console.log('PASS: viewport-sized collapsed reading across phone sizes, expand/collapse and short articles, article replacement and restoration, automatic media display without autoplay, audio play/pause, course permission failure, favorite persistence, note save/error retention, exam scope, practice/premium return, directory/deep-link reload, responsive layout and sheet keyboard dismissal')
 await context.unrouteAll({behavior:'wait'})
}finally{await browser?.close();await f.close()}
