import assert from 'node:assert/strict'
import {createServer} from 'node:http'
import {readFile,mkdir} from 'node:fs/promises'
import {resolve,extname,sep} from 'node:path'
import {chromium,expect} from '@playwright/test'
import {profileFixture} from './helpers/user-profile-fixture.ts'

// Isolated API fixture: never sends SMS or changes the developer's database.
const f=await profileFixture(),root=resolve('apps/user/dist/build/h5')
const server=createServer(async(req,res)=>{
 const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname)
 const file=resolve(root,'.'+(pathname==='/'?'/index.html':pathname))
 if(!file.startsWith(root+sep)){res.writeHead(403).end();return}
 try{const content=await readFile(file);res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.png':'image/png','.json':'application/json','.woff2':'font/woff2','.ttf':'font/ttf'})[extname(file)]||'application/octet-stream');res.end(content)}catch{res.writeHead(404).end()}
})
server.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r))
let browser
try {
 await f.db.query("UPDATE content SET title=CASE id WHEN 'a-s' THEN '社会工作综合能力' WHEN 'a-c' THEN '社会工作服务的内涵' WHEN 'a-t' THEN '社会工作服务的目标与功能' WHEN 'a-k' THEN '社会工作服务的内涵与特征' WHEN 'a-k2' THEN '对服务对象的功能：促进正常生活、恢复社会功能、促进人的发展' ELSE title END WHERE id=ANY($1::text[])",[['a-s','a-c','a-t','a-k','a-k2']])
 await f.db.query("UPDATE content SET payload=payload||'{\"stars\":4}'::jsonb WHERE id IN ('a-k','a-k2')")
 for(const [id,kind,parent,title,payload] of [
  ['layout-section','section','a-c','社会工作的主要领域',{}],
  ['layout-point','knowledge','layout-section','社会工作服务的主要领域',{stars:3}],
  ['layout-chapter','chapter','a-s','社会工作价值观与专业伦理',{}],
  ['layout-subject','subject',null,'社会工作实务',{}],
  ['layout-course','course','a-k','知识点配套课',{type:'video'}],
  ['layout-premium','course','a-t','节级精品课',{type:'video'}],
 ]) await f.db.query("INSERT INTO content(id,exam_id,kind,parent_id,title,status,payload) VALUES($1,$2,$3,$4,$5,'published',$6)",[id,f.exam,kind,parent,title,JSON.stringify(payload)])
 for(let i=3;i<=9;i++)await f.db.query("INSERT INTO content(id,exam_id,kind,parent_id,title,status,payload) VALUES($1,$2,'chapter','a-s',$3,'published','{}')",['layout-chapter-'+i,f.exam,'测试章节'+i])
 const saveShortTitle=async(shortTitle,status=200)=>{
  const row=(await f.db.query("SELECT * FROM content WHERE id='a-s'")).rows[0]
  const res=await fetch(f.origin+'/api/admin/content/a-s',{method:'PUT',headers:{Authorization:'Bearer '+f.token,'Content-Type':'application/json'},body:JSON.stringify({...row,source:'人工编辑',payload:{...row.payload,shortTitle}})})
  assert.equal(res.status,status,await res.text())
 }
 const catalogSubject=async()=>{const data=await f.call('/catalog/'+f.exam);return data.knowledgeSubjects.find(s=>s.id==='a-s')}
 await saveShortTitle('  综合能力  ')
 assert.equal((await catalogSubject()).name,'综合能力')
 assert.equal((await catalogSubject()).fullName,'社会工作综合能力')
 await saveShortTitle('一二三四五六七八九十一二三',400)
 assert.equal((await catalogSubject()).name,'综合能力')
 await saveShortTitle('')
 assert.equal((await catalogSubject()).name,'社会工作综合能力')
 await saveShortTitle('综合能力')
 browser=await chromium.launch({channel:'chrome',headless:true})
 const adminContext=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'})
 await adminContext.addInitScript(token=>sessionStorage.setItem('sxb-admin-token',token),f.token)
 await adminContext.route('**/api/**',async route=>{const u=new URL(route.request().url());if(!u.pathname.startsWith('/api/'))return route.continue();await route.fulfill({response:await route.fetch({url:f.origin+u.pathname+u.search})})})
 const adminPage=await adminContext.newPage()
 await adminPage.goto('http://127.0.0.1:5180/#knowledge-graph')
 await adminPage.locator('.grid button').filter({hasText:'初级社会工作师'}).click()
 const manager=adminPage.locator('.knowledge-list-manager')
 await manager.locator('.el-radio-button').filter({hasText:/^科目$/}).click()
 const adminRow=manager.locator('.el-table__row').filter({has:adminPage.getByRole('button',{name:'社会工作综合能力',exact:true})})
 await adminRow.getByRole('button',{name:'编辑内容',exact:true}).click()
 const drawer=adminPage.locator('.el-drawer:visible')
 await expect(drawer.getByRole('textbox',{name:'科目短标题',exact:true})).toHaveValue('综合能力')
 await drawer.getByRole('textbox',{name:'科目短标题',exact:true}).fill('综合能力新版')
 await drawer.getByRole('button',{name:'保存内容',exact:true}).click()
 await expect(drawer).toHaveCount(0)
 assert.equal((await catalogSubject()).name,'综合能力新版')
 await adminRow.getByRole('button',{name:'编辑内容',exact:true}).click()
 await expect(drawer.getByRole('textbox',{name:'科目短标题',exact:true})).toHaveValue('综合能力新版')
 await drawer.getByRole('textbox',{name:'科目短标题',exact:true}).fill('综合能力')
 await drawer.getByRole('button',{name:'保存内容',exact:true}).click()
 await expect(drawer).toHaveCount(0)
 await adminContext.unrouteAll({behavior:'wait'})
 await adminContext.close()
 const context=await browser.newContext({viewport:{width:375,height:812},hasTouch:true,reducedMotion:'reduce'})
 await context.addInitScript(({token,exam})=>{if(!localStorage.getItem('sxb-current-exam')){localStorage.setItem('sxb-api-token',JSON.stringify({type:'string',data:token}));localStorage.setItem('sxb-current-exam',JSON.stringify({type:'object',data:{id:exam,name:'初级社会工作师'}}))}},{token:f.student,exam:f.exam})
 await context.route('**/api/**',async route=>{const u=new URL(route.request().url());if(!u.pathname.startsWith('/api/'))return route.continue();await route.fulfill({response:await route.fetch({url:f.origin+u.pathname+u.search})})})
 const page=await context.newPage(),errors=[]
 page.on('pageerror',e=>errors.push(e.message))
 const url='http://127.0.0.1:'+server.address().port+'/#/pages/knowledge/index?mode=map'
 await page.goto(url)
 const subject=page.locator('.subject-tab').filter({has:page.getByText('综合能力',{exact:true})})
 await expect(subject).toBeVisible({timeout:20000})
 await subject.click()
 await expect(page.locator('.chapter-title')).toHaveText('第一章 社会工作服务的内涵')
 await expect(page.getByText('重点导图',{exact:true})).toHaveCount(0)
 await expect(page.getByText('全部章节',{exact:true})).toHaveCount(0)
 await expect(page.locator('.section-card')).toHaveCount(2)
 await expect(page.locator('.section-heading[aria-expanded="true"]')).toHaveCount(2)
 const point=page.locator('.point-row').filter({hasText:'社会工作服务的内涵与特征'})
 await expect(point.locator('.course-marker')).toHaveText('含课程')
 await expect(page.locator('.point-row').filter({hasText:'对服务对象'}).locator('.course-marker')).toHaveCount(0)
 await expect(point.locator('.point-stars')).toHaveAttribute('aria-label','4星知识点')
 await expect(point.locator('.question-count')).toHaveText('共 3 题')
 await expect(page.locator('.chapter-mastery')).toHaveText('掌握 50%')
 await expect(subject.locator('.tab-caption')).toHaveText('掌握 50%')
 await expect(page.locator('.section-list')).not.toContainText('掌握')
 await mkdir('.local/qa/knowledge-directory',{recursive:true})
 for(const [width,height] of [[375,812],[320,667],[430,932],[812,375]]){
  await page.setViewportSize({width,height})
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page overflow')
  await page.screenshot({path:'.local/qa/knowledge-directory/directory-'+width+'.png',fullPage:true})
 }
 await page.setViewportSize({width:375,height:812})
 const chapterScroll=page.locator('.tabs-compact.native-scroll-tabs')
 const before=await chapterScroll.evaluate(e=>e.scrollLeft)
 // Real mouse input: do not simulate dragging by assigning scrollLeft.
 const strip=await chapterScroll.boundingBox()
 const drag=async(from,to)=>{
  await page.mouse.move(strip.x+from,strip.y+strip.height/2)
  await page.mouse.down()
  await page.mouse.move(strip.x+to,strip.y+strip.height/2,{steps:12})
  await page.mouse.up()
 }
 await page.emulateMedia({reducedMotion:'no-preference'})
 await drag(270,60)
 await expect.poll(()=>chapterScroll.evaluate(e=>e.scrollLeft)).toBeGreaterThan(150)
 await expect(page.locator('.chapter-title')).toHaveText('第一章 社会工作服务的内涵')
 await drag(60,300)
 await expect.poll(()=>chapterScroll.evaluate(e=>e.scrollLeft)).toBeLessThan(2)
 await expect(page.locator('.chapter-title')).toHaveText('第一章 社会工作服务的内涵')
 await page.mouse.move(strip.x+180,strip.y+strip.height/2)
 await page.mouse.wheel(0,160)
 await expect.poll(()=>chapterScroll.evaluate(e=>e.scrollLeft)).toBeGreaterThan(100)
 await page.mouse.wheel(0,-300)
 await expect.poll(()=>chapterScroll.evaluate(e=>e.scrollLeft)).toBeLessThan(2)
 // Browser-native touch scrolling must still work on the same component.
 const cdp=await context.newCDPSession(page)
 const touch=async(type,x)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'?[]:[{x:strip.x+x,y:strip.y+strip.height/2}]})
 await touch('touchStart',280)
 for(const x of [250,210,170,130,90,50])await touch('touchMove',x)
 await touch('touchEnd',50)
 await expect.poll(()=>chapterScroll.evaluate(e=>e.scrollLeft)).toBeGreaterThan(100)
 await expect(page.locator('.chapter-title')).toHaveText('第一章 社会工作服务的内涵')
 await touch('touchStart',50)
 for(const x of [90,130,170,210,250,310])await touch('touchMove',x)
 await touch('touchEnd',310)
 await expect.poll(()=>chapterScroll.evaluate(e=>e.scrollLeft)).toBeLessThan(2)
 await cdp.detach()
 await page.emulateMedia({reducedMotion:'reduce'})
 const third=page.locator('.chapter-tab').filter({hasText:'第三章'})
 await third.click()
 await expect(page.locator('.chapter-title')).toHaveText('第三章 测试章节3')
 assert.ok(Math.abs(await chapterScroll.evaluate(e=>e.scrollLeft)-before)<2,'Selecting a visible chapter must not reposition the strip')
 await expect(page.locator('.slide-panel').last()).toHaveCSS('animation-name','none')
 const first=page.locator('.chapter-tab').filter({hasText:'第一章'})
 await expect(first).toBeInViewport()
 await first.click()
 await page.emulateMedia({reducedMotion:'no-preference'})
 await third.click()
 await expect(page.locator('.slide-panel').last()).toHaveCSS('animation-name',/panel-next/)
 await first.click()
 await expect(page.locator('.slide-panel').last()).toHaveCSS('animation-name',/panel-previous/)
 await page.emulateMedia({reducedMotion:'reduce'})
 await first.press('End')
 await expect(page.locator('.chapter-title')).toHaveText('第九章 测试章节9')
 await expect(page.locator('.chapter-tab').filter({hasText:'第九章'})).toBeInViewport()
 await chapterScroll.evaluate(e=>e.scrollLeft=0)
 await expect(first).toBeInViewport()
 await first.click()
 await first.press('End')
 await expect(page.locator('.chapter-tab').filter({hasText:'第九章'})).toBeInViewport()
 await chapterScroll.evaluate(e=>e.scrollLeft=0)
 await first.click()
 await page.emulateMedia({reducedMotion:'reduce'})
 const contentPanel=page.locator('.slide-viewport').last()
 const swipe=async(from,to)=>contentPanel.evaluate((el,{from,to})=>{
  const start=new Touch({identifier:1,target:el,clientX:from,clientY:350,pageX:from,pageY:350})
  const end=new Touch({identifier:1,target:el,clientX:to,clientY:355,pageX:to,pageY:355})
  el.dispatchEvent(new TouchEvent('touchstart',{bubbles:true,touches:[start],changedTouches:[start]}))
  el.dispatchEvent(new TouchEvent('touchend',{bubbles:true,touches:[],changedTouches:[end]}))
 },{from,to})
 await swipe(300,100)
 await expect(page.locator('.chapter-title')).toHaveText('第二章 社会工作价值观与专业伦理')
 await swipe(100,300)
 await expect(page.locator('.chapter-title')).toHaveText('第一章 社会工作服务的内涵')
 await page.locator('.section-heading').first().click()
 await expect(page.locator('.section-heading[aria-expanded="true"]')).toHaveCount(1)
 await page.locator('.chapter-tab').filter({hasText:'第二章'}).click()
 await expect(page.locator('.chapter-title')).toHaveText('第二章 社会工作价值观与专业伦理')
 await expect(page.getByText('本章暂无内容',{exact:true})).toBeVisible()
 await page.reload()
 await expect(page.locator('.chapter-title')).toHaveText('第二章 社会工作价值观与专业伦理',{timeout:20000})
 await page.emulateMedia({reducedMotion:'no-preference'})
 await page.locator('.subject-tab').filter({has:page.getByText('社会工作实务',{exact:true})}).click()
 await expect(page.getByText('本科目暂无章节',{exact:true})).toBeVisible()
 await expect(page.locator('.slide-panel').last()).toHaveCSS('animation-name',/panel-next/)
 await subject.click()
 await expect(page.locator('.slide-panel').last()).toHaveCSS('animation-name',/panel-previous/)
 await page.emulateMedia({reducedMotion:'reduce'})
 await expect(page.locator('.chapter-title')).toHaveText('第二章 社会工作价值观与专业伦理')
 await page.locator('.chapter-tab').filter({hasText:'第一章'}).click()
 await expect(page.locator('.section-heading[aria-expanded="false"]')).toHaveCount(1)
 await page.locator('.section-heading').first().click()
 await point.click()
 await expect(page).toHaveURL(/knowledge-detail/)
 await page.goBack()
 await expect(page.locator('.chapter-title')).toHaveText('第一章 社会工作服务的内涵')
 // Interrupt scrolling by replacing the subject strip and by leaving/reopening the page.
 // Keep animation enabled: reduced-motion alone misses scroll-view lifecycle races.
 await page.emulateMedia({reducedMotion:'no-preference'})
 const scrollErrors=[]
 page.on('console',message=>{if(/Cannot (?:set|read) properties of null|scrollLeft.*(?:Error|null)/.test(message.text()))scrollErrors.push(message.text())})
 for(let i=0;i<4;i++){
  await page.locator('.chapter-tab').first().press('End')
  await page.locator('.subject-tab').filter({has:page.getByText('社会工作实务',{exact:true})}).click()
  await subject.click()
  await expect(chapterScroll).toBeVisible()
  await page.getByRole('button',{name:'精讲课',exact:true}).click()
  await page.getByRole('button',{name:'知识图谱',exact:true}).click()
  await expect(chapterScroll).toBeVisible()
  await expect(page.locator('body')).not.toContainText("Cannot set properties of null")
 }
 assert.deepEqual(scrollErrors,[])
 await page.evaluate(exam=>localStorage.setItem('sxb-current-exam',JSON.stringify({type:'object',data:{id:exam,name:'中级社会工作师'}})),f.second)
 await page.reload()
 await expect(page.locator('.subject-tab').filter({hasText:'中级专属'})).toBeVisible({timeout:20000})
 await expect(subject).toHaveCount(0)
 assert.deepEqual(errors,[])
 console.log('PASS: mouse drag both directions without accidental selection, wheel, native touch scroll, short-title save/validation/fallback, visible chapter scroll retention (3→1), directional/reduced motion, subject/chapter selection, independent folding, stored state, exam isolation, unique-question mastery, supporting-course badges, responsive layout')
}finally{await browser?.close();await new Promise(r=>server.close(r));await f.close()}
