import assert from 'node:assert/strict'
import {mkdtemp,mkdir} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import express from 'express'
import {ZodError} from 'zod'
import {chromium,expect} from '@playwright/test'
process.env.APP_MODE='test';process.env.DATABASE_URL='';process.env.LOCAL_DATABASE_DIR=await mkdtemp(join(tmpdir(),'sxb-orders-ui-'));process.env.MEDIA_DIR=await mkdtemp(join(tmpdir(),'sxb-orders-media-'));process.env.SECRET_KEY='b'.repeat(64);process.env.ADMIN_PHONE='18600000000';process.env.ADMIN_PASSWORD='Orders-UI-42!'
const {db,closeDatabase}=await import('../apps/api/src/db.ts'),{seed}=await import('../apps/api/src/seed.ts'),{initSecrets,session}=await import('../apps/api/src/security.ts'),{api}=await import('../apps/api/src/routes.ts'),{rights}=await import('../apps/api/src/membership.ts')
await initSecrets();await seed()
const admin=(await db.query("SELECT id FROM users WHERE account_kind='admin' LIMIT 1")).rows[0],token=await session(admin.id,'admin'),exam='junior-social-worker',cycle=(await db.query('SELECT * FROM exam_cycles WHERE exam_id=$1 AND starts_at<=now() AND ends_at>now()',[exam])).rows[0]
const app=express();app.use(express.json({limit:'40mb'}));app.use('/api',api);app.use((e,_q,r,_n)=>r.status(e instanceof ZodError?400:e.status||500).json({message:e.message}))
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const origin='http://127.0.0.1:'+server.address().port
async function call(path,body,method='GET',auth=token){const r=await fetch(origin+'/api'+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+auth},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();assert.equal(r.status,200,JSON.stringify(d));return d}
await call('/admin/products/orders-ui',{version:0,config:{title:'2027 初级社会工作师 · 全考期学习套餐',type:'entitlement',examId:exam,cycleId:cycle.id,level:'vip',priceCents:59900,originalPriceCents:79900,status:'published',intro:'陪你完成这个考期的学习计划',document:{type:'doc',content:[{type:'heading',attrs:{level:2},content:[{type:'text',text:'从知识点到真题，系统备考'}]},{type:'paragraph',content:[{type:'text',text:'完整商品图文详情，版本变更后订单仍保留购买时的内容。'}]}]}}},'PUT')
const ids=[]
for(let i=0;i<3;i++){await db.query('INSERT INTO users(id,phone,nickname,invite_code) VALUES($1,$2,$3,$1)',['orders-ui-'+i,'1881111000'+i,['陈晓 · 订单回归','林悦 · 订单回归','吴同学 · 订单回归'][i]]);const userToken=await session('orders-ui-'+i),created=await call('/orders',{productId:'orders-ui'},'POST',userToken);ids.push(created.order.id);if(i!==2)await call('/orders/'+created.order.id+'/test-payment',{outcome:i===0?'success':'failure'},'POST',userToken)}
const browser=await chromium.launch({channel:'chrome',headless:true}),output='.local/qa/orders';await mkdir(output,{recursive:true});let page
try{
 page=await browser.newPage({viewport:{width:1733,height:1100},timezoneId:'Asia/Shanghai',reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.route('**/api/**',async route=>{const u=new URL(route.request().url());if(!u.pathname.startsWith('/api/'))return route.continue();await route.fulfill({response:await route.fetch({url:origin+u.pathname+u.search})})})
 await page.addInitScript(t=>sessionStorage.setItem('sxb-admin-token',t),token);await page.goto('http://127.0.0.1:5180/#orders')
 await page.getByRole('textbox',{name:'订单或用户',exact:true}).fill('订单回归');await page.getByRole('button',{name:'查询',exact:true}).click();await expect(page.locator('.orders-page tbody tr')).toHaveCount(3)
 const headers=await page.locator('.orders-page thead').innerText();assert(!headers.includes('权益档位'));assert(!headers.includes('考期'));await page.screenshot({path:output+'/list.png',animations:'disabled'})
 const paidRow=page.locator('.orders-page tbody tr').filter({hasText:'陈晓'});await paidRow.getByRole('button',{name:'订单详情',exact:true}).click();const drawer=page.locator('.order-drawer:visible');await expect(drawer).toContainText('2027 年考期 · VIP');await expect(drawer).toContainText('¥799.00');await expect(drawer).toContainText('完整商品图文详情');await page.screenshot({path:output+'/detail.png',animations:'disabled'})
 await drawer.getByRole('button',{name:'登记线下退款',exact:true}).click();const dialog=page.locator('.order-action-dialog:visible');await dialog.getByRole('button',{name:'登记线下退款',exact:true}).click();await expect(dialog).toContainText('请填写至少3个字');await dialog.getByRole('textbox',{name:'操作说明',exact:true}).fill('用户联系工作人员申请全额退款');await dialog.getByRole('button',{name:'登记线下退款',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(drawer).toContainText('待线下退款');assert.equal((await rights('orders-ui-0',exam)).level,'vip')
 await drawer.getByRole('button',{name:'确认已线下退款',exact:true}).click();await dialog.getByRole('textbox',{name:'操作说明',exact:true}).fill('已联系用户并完成线下转账');await dialog.getByRole('button',{name:'确认已线下退款',exact:true}).click();await expect(dialog).toContainText('请填写线下退款凭证');await dialog.getByRole('textbox',{name:'线下退款凭证',exact:true}).fill('BANK-20260916-001');await page.screenshot({path:output+'/refund.png',animations:'disabled'});await dialog.getByRole('button',{name:'确认已线下退款',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(drawer).toContainText('已退款');assert.equal((await rights('orders-ui-0',exam)).level,'free')
 await drawer.getByRole('tab',{name:'处理记录',exact:true}).click();await expect(drawer).toContainText('BANK-20260916-001');await expect(drawer).toContainText('最高管理员');await drawer.getByRole('button',{name:'关闭',exact:true}).click()
 const pending=page.locator('.orders-page tbody tr').filter({hasText:'吴同学'});await pending.getByRole('button',{name:'删除测试订单',exact:true}).click();await dialog.getByRole('textbox',{name:'操作说明',exact:true}).fill('移除无用测试订单');await dialog.getByRole('textbox',{name:'确认删除订单号',exact:true}).fill(ids[2]);await dialog.getByRole('button',{name:'删除测试订单',exact:true}).click();await expect(pending).toHaveCount(0)
 const failed=page.locator('.orders-page tbody tr').filter({hasText:'林悦'});await expect(failed).toContainText('支付失败');await failed.getByRole('button',{name:'订单详情',exact:true}).click();await drawer.getByRole('tab',{name:'支付记录',exact:true}).click();await expect(drawer).toContainText('测试支付失败');await page.setViewportSize({width:390,height:844});await page.screenshot({path:output+'/mobile-detail.png',animations:'disabled'});assert.equal(await drawer.evaluate(el=>el.scrollWidth>el.clientWidth),false);await drawer.getByRole('button',{name:'关闭',exact:true}).click();await page.setViewportSize({width:1733,height:1100})
 await page.goto('http://127.0.0.1:5180/#products');await page.getByRole('button',{name:'编辑商品',exact:true}).click();const productDrawer=page.locator('.product-drawer:visible');await expect(productDrawer.locator('.preview-original')).toHaveText('¥799.00');await expect(productDrawer.locator('.preview-document')).toContainText('完整商品图文详情');await productDrawer.getByRole('tab',{name:'商品详情',exact:true}).click();await productDrawer.getByRole('textbox',{name:'图文正文编辑器',exact:true}).fill('商品概览中的实时图文预览');await expect(productDrawer.locator('.preview-document')).toContainText('实时图文预览');await page.screenshot({path:output+'/product-preview.png',animations:'disabled'});await productDrawer.getByRole('button',{name:'取消',exact:true}).click()
 await page.getByRole('textbox',{name:'筛选商品名称',exact:true}).fill('不存在的商品');await expect(page.locator('.products-page .el-empty')).toBeVisible();await expect(page.locator('.products-page .el-empty button')).toHaveCount(0)
 assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',filters:true,snapshot:true,manualRefund:true,revocation:true,testDeletion:true,paymentFailure:true,mobile:true,productPreview:true,contentWritesToLive:0}))
}catch(e){await page?.screenshot({path:output+'/failure.png',animations:'disabled'});throw e}finally{for(const c of browser.contexts())for(const p of c.pages())await p.unrouteAll({behavior:'wait'});await browser.close();await new Promise(r=>server.close(r));await closeDatabase()}
