import assert from 'node:assert/strict'
import {mkdtemp,mkdir} from 'node:fs/promises'
import {join} from 'node:path'
import {tmpdir} from 'node:os'
import express from 'express'
import {ZodError} from 'zod'
import {chromium,expect} from '@playwright/test'
process.env.APP_MODE='test';process.env.DATABASE_URL='';process.env.LOCAL_DATABASE_DIR=await mkdtemp(join(tmpdir(),'sxb-products-ui-'));process.env.MEDIA_DIR=await mkdtemp(join(tmpdir(),'sxb-products-media-'));process.env.SECRET_KEY='b'.repeat(64);process.env.ADMIN_PHONE='18600000000';process.env.ADMIN_PASSWORD='Products-UI-42!'
const {db,closeDatabase}=await import('../apps/api/src/db.ts'),{seed}=await import('../apps/api/src/seed.ts'),{initSecrets,session}=await import('../apps/api/src/security.ts'),{api}=await import('../apps/api/src/routes.ts')
await initSecrets();await seed()
const admin=(await db.query("SELECT id FROM users WHERE account_kind='admin' LIMIT 1")).rows[0],adminToken=await session(admin.id,'admin')
await db.query("INSERT INTO users(id,phone,nickname,invite_code) VALUES('product-ui-student','18866660001','商品测试学员','product-ui-invite')")
const studentToken=await session('product-ui-student'),exam='junior-social-worker',cycle=(await db.query('SELECT * FROM exam_cycles WHERE exam_id=$1 AND starts_at<=now() AND ends_at>now()',[exam])).rows[0]
const app=express();app.use(express.json({limit:'40mb'}));app.use('/api',api);app.use((e,_q,r,_n)=>r.status(e instanceof ZodError?400:e.status||500).json({message:e.message}))
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const origin='http://127.0.0.1:'+server.address().port
async function call(path,body,method='GET',expected=200){const r=await fetch(origin+'/api'+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+adminToken},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();assert.equal(r.status,expected,JSON.stringify(data));return data}
const browser=await chromium.launch({channel:'chrome',headless:true}),output='.local/qa/products';await mkdir(output,{recursive:true})
const errors=[]
async function proxy(route){const u=new URL(route.request().url());if(!u.pathname.startsWith('/api/'))return route.continue();await route.fulfill({response:await route.fetch({url:origin+u.pathname+u.search})})}
let page,mobile
try{
 page=await browser.newPage({viewport:{width:1680,height:1100},timezoneId:'Asia/Shanghai'});page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/**',proxy);await page.addInitScript(t=>sessionStorage.setItem('sxb-admin-token',t),adminToken)
 await page.goto('http://127.0.0.1:5180/#products');await expect(page.getByText('等待开发',{exact:true})).toHaveCount(0);await expect(page.getByText('暂无商品，创建你的第一款权益商品')).toBeVisible();await page.locator('.heading-actions').getByRole('button',{name:'新增商品'}).click()
 const drawer=page.locator('.product-drawer:visible');await drawer.getByRole('button',{name:'保存商品'}).click();await expect(drawer.getByRole('alert')).toContainText('请填写前端商品名称')
 await drawer.getByPlaceholder('例如：2027 初级社会工作师 VIP 套餐').fill('2027 初级社工 · 36小时体验')
 await drawer.getByRole('textbox',{name:'前端商品名称',exact:true}).fill('安心备考 · 36小时体验');await expect(drawer.locator('.product-preview h2')).toHaveText('安心备考 · 36小时体验')
 await drawer.getByText('体验权益商品',{exact:true}).click();await drawer.locator('.el-select').filter({has:page.getByRole('combobox',{name:'商品所属考试'})}).click();await page.getByRole('option',{name:'初级社会工作师',exact:true}).click()
 await drawer.locator('.el-select').filter({has:page.getByRole('combobox',{name:'商品适用考期'})}).click();await page.getByRole('option',{name:cycle.year+' 年考期',exact:true}).click()
 await drawer.locator('.el-select').filter({has:page.getByRole('combobox',{name:'商品上架设置'})}).click();await page.getByRole('option',{name:'上架',exact:true}).click();await page.screenshot({path:output+'/editor-basic.png',animations:'disabled'})
 await drawer.getByRole('tab',{name:'售价与权益'}).click();await drawer.getByRole('spinbutton',{name:'商品售价'}).fill('9.90');await drawer.getByRole('spinbutton',{name:'体验时长',exact:true}).fill('36');await drawer.getByRole('spinbutton',{name:'最低可购买时长',exact:true}).fill('10');await drawer.getByText('SVIP',{exact:true}).click();await page.screenshot({path:output+'/editor-rules.png',animations:'disabled'})
 await drawer.getByRole('tab',{name:'商品详情'}).click();await drawer.getByRole('textbox',{name:'图文正文编辑器'}).fill('体验课程、学习报告与完整知识图谱。支付前核对实际可用时长。')
 const fixture=await browser.newPage({viewport:{width:480,height:640}});await fixture.setContent('<div style="height:600px;padding:20px;background:linear-gradient(145deg,#153965,#5779c7);color:white;font:28px sans-serif"><p>2027 备考计划</p><h1>让每一步学习<br>更有方向</h1><p>限时体验 · SVIP</p></div>');const png=await fixture.screenshot();await fixture.close()
 await drawer.locator('input[type=file]').first().setInputFiles({name:'商品封面.png',mimeType:'image/png',buffer:png});await expect(drawer.getByAltText('商品封面预览')).toBeVisible()
 await drawer.getByRole('button',{name:'插入图片',exact:true}).click();const upload=page.getByRole('dialog',{name:'插入资源'});await upload.locator('input[type=file]').setInputFiles({name:'商品详情.png',mimeType:'image/png',buffer:png});await upload.getByRole('button',{name:'插入正文'}).click();await expect(upload).toHaveCount(0)
 await drawer.getByRole('button',{name:'保存商品'}).click();await expect(drawer).toHaveCount(0);const row=page.locator('.products-page tbody tr').filter({hasText:'2027 初级社工 · 36小时体验'});await expect(row).toBeVisible();await expect(row).toContainText('¥9.90');await page.screenshot({path:output+'/list.png',animations:'disabled'})
 let product=(await call('/admin/products'))[0];assert.equal(product.config.trialHours,36);assert.equal(product.config.minimumHours,10);assert.equal(product.config.level,'svip')
 await row.getByRole('button',{name:'编辑商品',exact:true}).click();await drawer.getByPlaceholder('例如：2027 初级社会工作师 VIP 套餐').fill('修改后的体验商品');await drawer.getByRole('tab',{name:'商品详情'}).click();await drawer.getByRole('textbox',{name:'图文正文编辑器'}).fill('第二版正文');await drawer.getByRole('button',{name:'保存商品'}).click();await expect(drawer).toHaveCount(0)
 const resources=await call('/admin/resources?search='+encodeURIComponent('商品详情'));assert(resources.items.some(item=>item.references.some(r=>r.kind==='product')))
 await page.getByRole('button',{name:'历史版本',exact:true}).click();const history=page.locator('.product-history:visible');await expect(history.getByText('当前 V2')).toBeVisible();await history.getByRole('navigation').getByRole('button').filter({hasText:'V1'}).click();await expect(history).toContainText('36 / 10 小时');await page.screenshot({path:output+'/history.png',animations:'disabled'});await history.getByRole('button',{name:'恢复此版本'}).click();await page.getByRole('dialog',{name:'恢复历史版本',exact:true}).getByRole('button',{name:'恢复此版本'}).click();await expect(history.getByText('当前 V3')).toBeVisible();await history.getByRole('button',{name:'关闭',exact:true}).click();await expect(row).toBeVisible()
 await row.getByRole('button',{name:'编辑商品',exact:true}).click();await page.setViewportSize({width:390,height:844});await drawer.getByRole('tab',{name:'售价与权益'}).click();assert.equal(await drawer.evaluate(el=>el.scrollWidth>el.clientWidth),false);await page.screenshot({path:output+'/editor-mobile.png',animations:'disabled'});await drawer.getByRole('button',{name:'取消',exact:true}).click()
 await db.query("UPDATE exam_cycles SET ends_at=now()+interval '12 hours' WHERE id=$1",[cycle.id])
 mobile=await browser.newPage({viewport:{width:390,height:844},timezoneId:'Asia/Shanghai'});mobile.on('pageerror',e=>errors.push(e.message));mobile.on('console',m=>{if(m.type()==='error')console.log('BROWSER',m.text())});await mobile.route('**/api/**',proxy);await mobile.addInitScript(({token})=>{localStorage.setItem('sxb-api-token',JSON.stringify({type:'string',data:token}));localStorage.setItem('sxb-current-exam',JSON.stringify({type:'object',data:{id:'junior-social-worker',name:'初级社会工作师'}}))},{token:studentToken});await mobile.goto('http://127.0.0.1:5174/#/pages/products/index');await expect(mobile.getByText('安心备考 · 36小时体验',{exact:true})).toBeVisible({timeout:20000});await expect(mobile.getByText('加载中',{exact:true})).toBeHidden({timeout:15000});await mobile.screenshot({path:output+'/shop.png',fullPage:true,animations:'disabled'});await mobile.locator('.shop-product').filter({hasText:'安心备考 · 36小时体验'}).click();await expect(mobile.locator('.shop-rich')).toContainText('体验课程');await mobile.screenshot({path:output+'/detail.png',fullPage:true,animations:'disabled'});assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
 await mobile.locator('.shop-footer uni-button').click();await expect(mobile.getByText('体验时间提醒',{exact:true})).toBeVisible();await expect(mobile.getByText(/实际可用：/)).toBeVisible();await mobile.screenshot({path:output+'/short-confirmation.png',fullPage:true,animations:'disabled'});await mobile.getByText('确认支付',{exact:true}).click();await expect.poll(async()=>Number((await db.query("SELECT count(*)::int AS n FROM memberships WHERE user_id='product-ui-student'")).rows[0].n)).toBe(1)
 await mobile.goto('http://127.0.0.1:5174/#/pages/profile-center/index?mode=orders');await expect(mobile.locator('.order-title-line')).toContainText('安心备考 · 36小时体验');await expect(mobile.locator('.order-title-line')).not.toContainText('2027 初级社工')
 await mobile.unrouteAll({behavior:'wait'});assert.deepEqual(errors,[]);console.log(JSON.stringify({status:'PASS',create:true,validation:true,images:true,restore:true,resourceHistory:true,responsive:true,frontendPurchase:true,shortTrialConfirmation:true,contentWritesToLive:0}))
}catch(e){if(mobile){console.log('MOBILE',mobile.url(),(await mobile.locator('body').innerText()).slice(0,2000),errors);await mobile.screenshot({path:output+'/failure-mobile.png',fullPage:true,animations:'disabled'})}await page?.screenshot({path:output+'/failure.png',fullPage:true,animations:'disabled'});throw e}finally{for(const context of browser.contexts())for(const openPage of context.pages())await openPage.unrouteAll({behavior:'wait'});await browser.close();await new Promise(r=>server.close(r));await closeDatabase()}
