import 'dotenv/config'
import assert from 'node:assert/strict'
import {mkdir,mkdtemp} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {chromium,expect} from '@playwright/test'
import express from 'express'
import {ZodError} from 'zod'
import {newField,initialValues} from '../apps/shared/question-types.ts'
// Browser interactions run against an isolated API/database, never writing test rows to the live database.
process.env.APP_MODE='test';process.env.DATABASE_URL='';process.env.LOCAL_DATABASE_DIR=await mkdtemp(join(tmpdir(),'sxb-types-browser-'));process.env.SECRET_KEY='b'.repeat(64);process.env.ADMIN_PHONE='18600000000';process.env.ADMIN_PASSWORD='Browser-Question-Types-42!'
const {db,closeDatabase}=await import('../apps/api/src/db.ts')
const {seed}=await import('../apps/api/src/seed.ts')
const {initSecrets,session}=await import('../apps/api/src/security.ts')
const {api}=await import('../apps/api/src/routes.ts')
await initSecrets();await seed()
const admin=(await db.query("SELECT id FROM users WHERE account_kind='admin' LIMIT 1")).rows[0]
const token=await session(admin.id,'admin')
const app=express();app.use(express.json({limit:'16mb'}));app.use('/api',api);app.use((e,_q,r,_n)=>r.status(e instanceof ZodError?400:e.status||500).json({message:e.message}))
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const apiOrigin='http://127.0.0.1:'+server.address().port
const output='.local/qa/question-types';await mkdir(output,{recursive:true})
const browser=await chromium.launch({channel:'chrome',headless:true})
try{
  const page=await browser.newPage({viewport:{width:1733,height:1100},reducedMotion:'reduce'})
  const errors=[];page.on('pageerror',e=>errors.push(e.message))
  await page.route('**/api/**',async route=>{const url=new URL(route.request().url());if(!url.pathname.startsWith('/api/'))return route.continue();const response=await route.fetch({url:apiOrigin+url.pathname+url.search});await route.fulfill({response})})
  await page.addInitScript(t=>sessionStorage.setItem('sxb-admin-token',t),token)
  await page.goto('http://127.0.0.1:5180/#question-types')
  await expect(page.locator('.qt-card')).toHaveCount(4)
  await expect(page.getByText('等待开发',{exact:true})).toHaveCount(0)
  await page.screenshot({path:output+'/library.png',fullPage:true})
  await page.getByRole('button',{name:'编辑多选题',exact:true}).click()
  await expect(page.locator('.qt-builder')).toBeVisible()
  await page.screenshot({path:output+'/designer.png',fullPage:true})
  await page.getByRole('tab',{name:'录入与答题预览',exact:true}).click()
  await expect(page.locator('.qt-phone')).toBeVisible()
  await page.locator('.qp-option').first().click()
  await expect(page.locator('.qp-option').first()).toHaveAttribute('aria-pressed','true')
  await page.screenshot({path:output+'/preview.png',fullPage:true})
  await page.getByRole('button',{name:'返回题型列表',exact:true}).click()
  await page.getByRole('button',{name:'新建题型',exact:true}).click()
  await page.getByPlaceholder('例如：材料分析题').fill('浏览器组合题')
  await page.locator('.qt-palette button').filter({hasText:'公共材料'}).click()
  await page.locator('.qt-palette button').filter({hasText:'共用选项'}).click()
  await page.locator('.qt-palette button').filter({hasText:'小题组'}).click()
  await page.locator('.qt-palette button').filter({hasText:'主观作答'}).click()
  await expect(page.locator('.qt-block')).toHaveCount(5)
  await expect(page.getByRole('switch',{name:'AI 判分',exact:true})).not.toBeChecked()
  await page.locator('.qt-grading-option .el-switch').click()
  await page.getByRole('button',{name:'保存题型',exact:true}).click()
  await expect(page.getByText('题型已保存，已有题目保持原版本',{exact:true})).toBeVisible()
  await page.reload();await expect(page.locator('.qt-card')).toHaveCount(5)
  await page.getByRole('button',{name:'编辑浏览器组合题',exact:true}).click()
  await expect(page.locator('.qt-block')).toHaveCount(5)
  await page.getByRole('button',{name:'配置主观作答',exact:true}).click()
  await expect(page.getByRole('switch',{name:'AI 判分',exact:true})).toBeChecked()
  await page.screenshot({path:output+'/ai-grading-option.png',fullPage:true})
  await page.locator('.qt-grading-option .el-switch').click()
  await page.getByRole('tab',{name:'考试评分配置',exact:true}).click()
  await page.locator('.qt-rule-add .el-select').click()
  await page.getByRole('option',{name:'初级社会工作师',exact:true}).click()
  await page.getByRole('button',{name:'添加考试规则',exact:true}).click()
  await expect(page.locator('.qt-rule-card')).toHaveCount(1)
  await page.getByRole('button',{name:'保存题型',exact:true}).click()
  await expect(page.getByText('当前 v2 · 保存为新版本，不改变已有题目',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'返回题型列表',exact:true}).click()
  await page.goto('http://127.0.0.1:5180/#question')
  await page.getByRole('button',{name:'新增题目',exact:true}).click()
  const drawer=page.locator('.el-drawer').filter({has:page.getByText('新增题目',{exact:true})})
  await expect(drawer.locator('.qf-field')).toHaveCount(1)
  await drawer.getByPlaceholder('用于题目列表检索；各小题内容在下方录入').fill('浏览器实际录题')
  await drawer.getByRole('button',{name:'选择知识点',exact:true}).click()
  const pointPicker=page.getByRole('dialog',{name:'选择关联知识点',exact:true})
  await pointPicker.locator('.kp-option').first().click()
  await pointPicker.getByRole('button',{name:'确认选择（1）',exact:true}).click()
  await drawer.getByPlaceholder('填写题目内容').fill('以下哪项正确？')
  await drawer.getByRole('textbox',{name:'题目选项A',exact:true}).fill('正确选项')
  await drawer.getByRole('textbox',{name:'题目选项B',exact:true}).fill('错误选项')
  await drawer.locator('.qf-option').first().locator('.el-radio').click()
  await drawer.getByRole('button',{name:'保存题目',exact:true}).click()
  await expect(drawer).not.toBeVisible()
  await expect(page.getByRole('button',{name:'浏览器实际录题',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'浏览器实际录题',exact:true}).click()
  await expect(page.getByRole('textbox',{name:'题目选项A',exact:true})).toHaveValue('正确选项')
  await page.locator('.el-drawer').getByRole('button',{name:'取消',exact:true}).click()
  await page.getByRole('button',{name:'导出题库',exact:true}).click()
  const download=page.waitForEvent('download')
  await page.getByRole('button',{name:'导出 Excel',exact:true}).click()
  const downloaded=await download;assert(downloaded.suggestedFilename().endsWith('.xlsx'))
  await page.locator('.el-dialog').getByRole('button',{name:'取消',exact:true}).click()
  await page.goto('http://127.0.0.1:5180/#question-types')
  await expect(page.locator('.qt-card')).toHaveCount(5)
  await page.setViewportSize({width:1100,height:900})
  await page.getByRole('button',{name:'编辑单选题',exact:true}).click()
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Tablet overflow')
  await page.screenshot({path:output+'/designer-1100.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  assert(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Mobile overflow')
  await page.screenshot({path:output+'/designer-mobile.png',fullPage:true})
  assert.deepEqual(errors,[])
  // Exercise the real H5 renderer against the same isolated database.
  const adminCall=async(path,body,method='POST')=>{const r=await fetch(apiOrigin+'/api'+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)});const data=await r.json();assert.equal(r.status,200,JSON.stringify(data));return data}
  const point=(await db.query("SELECT * FROM knowledge_nodes WHERE kind='knowledge' AND exam_id='junior-social-worker' ORDER BY id LIMIT 1")).rows[0]
  const material=newField('material','case'),choice=newField('single','choice'),written=newField('text','written'),group=newField('group','group');group.children=[choice,written]
  const definition={fields:[material,group],examRules:{}}
  await adminCall('/admin/question-types/browser-case',{name:'移动端案例题',description:'测试',definition},'PUT')
  const values=initialValues(definition);values.case='服务对象在社区中遇到困难。';values.choice={prompt:'以下哪种服务方式更合适？',options:['尊重自主决定','替代所有决定'],answer:[0],reference:'',rubric:'',explanation:'尊重服务对象的自主性。'};values.written={prompt:'请说明专业服务的依据。',options:[],answer:[],reference:'尊重与助人自助。',rubric:'结合专业价值观说明。',explanation:''}
  const qid='browser-mobile-case',q={id:qid,kind:'question',exam_id:point.exam_id,parent_id:point.id,title:'案例分析：专业服务',status:'draft',source:'test',is_test_data:true,payload:{type:'configured',templateId:'browser-case',templateVersion:1,stem:'案例分析：专业服务',knowledgePointId:point.id,values}}
  await adminCall('/admin/content/'+qid,q,'PUT')
  for(const status of ['review','published']){const current=(await db.query('SELECT * FROM content WHERE id=$1',[qid])).rows[0];await adminCall('/admin/content/'+qid,{...current,status},'PUT')}
  const student=(await db.query("SELECT * FROM users WHERE account_kind='student' LIMIT 1")).rows[0],studentToken=await session(student.id,'student')
  const mobile=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'})
  const mobileErrors=[];mobile.on('pageerror',e=>mobileErrors.push(e.message))
  mobile.on('console',msg=>{if(msg.type()==='error')console.log('H5 console',msg.text())});mobile.on('response',r=>{if(r.status()>=400)console.log('H5 bad response',r.status(),r.url())})
  await mobile.route('**/api/**',async route=>{const url=new URL(route.request().url());if(!url.pathname.startsWith('/api/'))return route.continue();const response=await route.fetch({url:apiOrigin+url.pathname+url.search});await route.fulfill({response})})
  await mobile.addInitScript(({token,user,examId})=>{localStorage.setItem('sxb-api-token',token);localStorage.setItem('sxb-login',JSON.stringify({type:'object',data:{...user,loggedAt:Date.now()}}));localStorage.setItem('sxb-current-exam',JSON.stringify({type:'object',data:{id:examId,name:'初级社会工作师',daysLeft:100}}))},{token:studentToken,user:{id:student.id,nickname:student.nickname},examId:point.exam_id})
  await mobile.goto('http://127.0.0.1:5174/#/pages/practice-session/index?knowledgePointId='+point.id+'&questionId='+qid)
  try{await expect(mobile.locator('.cq')).toBeVisible({timeout:15000})}catch(e){await mobile.screenshot({path:output+'/mobile-failure.png',fullPage:true});console.log('Mobile failure',mobile.url(),mobileErrors,await mobile.locator('body').innerText());throw e}
  await expect(mobile.locator('.cq-field')).toHaveCount(4)
  await mobile.locator('.cq-option').first().click()
  await mobile.locator('.cq-answer textarea').fill('尊重服务对象自主决定，支持其发展能力。')
  await mobile.screenshot({path:output+'/mobile-answer.png',fullPage:true})
  await mobile.getByText('提交作答',{exact:true}).click()
  await expect(mobile.getByText('请对照参考答案完成自评',{exact:true})).toBeVisible()
  await expect(mobile.getByText('参考答案：尊重与助人自助。',{exact:true})).toBeVisible()
  await mobile.screenshot({path:output+'/mobile-pending.png',fullPage:true})
  assert.equal((await db.query('SELECT result FROM question_submissions WHERE question_id=$1',[qid])).rows[0].result.score,null)
  await mobile.locator('.cq-self-controls input').fill('8')
  await mobile.getByText('保存自评',{exact:true}).click()
  await expect(mobile.getByText('自评分 8 / 10',{exact:true})).toBeVisible()
  await expect(mobile.getByText('参考总分（含自评）：9 / 11',{exact:true})).toBeVisible()
  await mobile.reload()
  await expect(mobile.getByText('自评分 8 / 10',{exact:true})).toBeVisible({timeout:15000})
  await mobile.screenshot({path:output+'/mobile-self-score.png',fullPage:true})
  written.aiGrading=true
  await adminCall('/admin/question-types/browser-case',{name:'移动端案例题',description:'测试',definition,version:1},'PUT')
  const aiQid='browser-mobile-ai',aiRow={...q,id:aiQid,payload:{...q.payload,templateVersion:2}}
  await adminCall('/admin/content/'+aiQid,aiRow,'PUT')
  for(const status of ['review','published']){const current=(await db.query('SELECT * FROM content WHERE id=$1',[aiQid])).rows[0];await adminCall('/admin/content/'+aiQid,{...current,status},'PUT')}
  await mobile.goto('http://127.0.0.1:5174/#/pages/practice-session/index?knowledgePointId='+point.id+'&questionId='+aiQid)
  await mobile.reload()
  await expect(mobile.getByText('本题含 AI 判分，提交后将依据参考答案和评分要点评分。',{exact:true})).toBeVisible()
  await mobile.locator('.cq-option').first().click()
  await mobile.locator('.cq-answer textarea').fill('尊重服务对象自主权。')
  await mobile.getByText('提交作答',{exact:true}).click()
  await expect(mobile.getByText('作答已保存，AI 判分失败',{exact:true})).toBeVisible()
  await mobile.getByText('重试 AI 判分',{exact:true}).click()
  await expect(mobile.getByText('作答已保存，AI 判分失败',{exact:true})).toBeVisible()
  await expect(mobile.locator('.cq-self-controls')).toHaveCount(0)
  await mobile.reload()
  await expect(mobile.getByText('作答已保存，AI 判分失败',{exact:true})).toBeVisible({timeout:15000})
  await expect(mobile.locator('.cq-answer textarea')).toHaveValue('尊重服务对象自主权。')
  await mobile.screenshot({path:output+'/mobile-ai-retry.png',fullPage:true})
  const {runSubmissionGrading}=await import('../apps/api/src/question-grading.ts')
  const submission=(await db.query('SELECT id FROM question_submissions WHERE question_id=$1',[aiQid])).rows[0]
  await runSubmissionGrading(student.id,submission.id,async()=>({id:'browser-fixture',mode:'live',status:'success',result:JSON.stringify({fields:[{id:'written',score:7.5,feedback:'指出自主权，尚需展开助人自助的具体做法。'}]}),error:'',inputTokens:0,outputTokens:0,cachedTokens:0,estimatedCost:0,durationMs:0}))
  await mobile.reload()
  await expect(mobile.getByText('AI 评分 7.5 / 10',{exact:true})).toBeVisible({timeout:15000})
  await expect(mobile.getByText('AI 评分结果：8.5 / 11',{exact:true})).toBeVisible()
  await mobile.screenshot({path:output+'/mobile-ai-result.png',fullPage:true})
  assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'Student mobile overflow')
  assert.deepEqual(mobileErrors,[])
  console.log('Question-type browser checks passed: designer persistence, composite structure, rules, preview, authoring, export and responsive layout.')
}finally{await browser.close();await new Promise(r=>server.close(r));await closeDatabase()}
