import 'dotenv/config'
import assert from 'node:assert/strict'
import {mkdir,mkdtemp} from 'node:fs/promises'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {chromium,expect} from '@playwright/test'
import express from 'express'
import {ZodError} from 'zod'
import ExcelJS from 'exceljs'
import {newField} from '../apps/shared/question-types.ts'
process.env.APP_MODE='test';process.env.DATABASE_URL='';process.env.LOCAL_DATABASE_DIR=await mkdtemp(join(tmpdir(),'sxb-question-list-'));process.env.SECRET_KEY='c'.repeat(64);process.env.ADMIN_PHONE='18600000000';process.env.ADMIN_PASSWORD='Browser-Question-List-42!'
const {db,closeDatabase}=await import('../apps/api/src/db.ts')
const {seed}=await import('../apps/api/src/seed.ts')
const {initSecrets,session}=await import('../apps/api/src/security.ts')
const {api}=await import('../apps/api/src/routes.ts')
await initSecrets();await seed()
const admin=(await db.query("SELECT id FROM users WHERE account_kind='admin' LIMIT 1")).rows[0],token=await session(admin.id,'admin')
const app=express();app.use(express.json({limit:'16mb'}));app.use('/api',api);app.use((e,_q,r,_n)=>r.status(e instanceof ZodError?400:e.status||500).json({message:e.message}))
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const origin='http://127.0.0.1:'+server.address().port
const call=async(path,body,method='PUT')=>{const r=await fetch(origin+'/api'+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify(body)});const result=await r.json();assert.equal(r.status,200,JSON.stringify(result));return result}
const source=(await db.query("SELECT * FROM content WHERE kind='question' AND payload->>'type'='single' LIMIT 1")).rows[0]
const points=(await db.query("SELECT * FROM knowledge_nodes WHERE kind='knowledge' AND exam_id=$1 ORDER BY id LIMIT 2",[source.exam_id])).rows
const longName='跨章节服务对象权益保护与多部门协作中的社会工作专业价值伦理原则和综合实务方法完整知识点名称'
await db.query('UPDATE knowledge_nodes SET title=$2 WHERE id=$1',[points[1].id,longName])
const longTitle='浏览器筛选验证：'+('社会工作者应当如何协调服务对象需求和社区资源，维护合法权益并制定适当的服务计划？').repeat(3)
await call('/admin/content/browser-question-list',{...source,id:'browser-question-list',version:undefined,status:'draft',title:longTitle,parent_id:points[0].id,payload:{...source.payload,stem:longTitle,knowledgePointId:points[0].id,knowledgePointIds:points.map(p=>p.id)}})
const f=newField('single','response');f.minOptions=5;f.maxOptions=7
await call('/admin/question-types/browser-five',{name:'浏览器五选项',description:'',definition:{fields:[f],examRules:{}}})
const output='.local/qa/question-management';await mkdir(output,{recursive:true})
const browser=await chromium.launch({channel:'chrome',headless:true})
try{
  const page=await browser.newPage({viewport:{width:1733,height:1100},reducedMotion:'reduce'}),errors=[]
  page.on('pageerror',e=>errors.push(e.message))
  await page.route('**/api/**',async route=>{const u=new URL(route.request().url());if(!u.pathname.startsWith('/api/'))return route.continue();const response=await route.fetch({url:origin+u.pathname+u.search});await route.fulfill({response})})
  await page.addInitScript(t=>sessionStorage.setItem('sxb-admin-token',t),token)
  await page.goto('http://127.0.0.1:5180/#question')
  const manager=page.locator('.question-manager')
  await expect(page.locator('.heading-actions .el-button')).toHaveText(['','新增题目','导入','导出'])
  await expect(manager.locator('thead th .cell')).toHaveText(['标题','知识点','题型','状态','更新时间','操作'])
  await expect(manager.locator('.el-select__selected-item').filter({hasText:'全部题型'})).toBeVisible()
  const sizes=await manager.locator('.admin-filters .el-input__wrapper,.admin-filters .el-select__wrapper').evaluateAll(nodes=>nodes.map(n=>Math.round(n.getBoundingClientRect().height)))
  assert.ok(sizes.every(h=>h===40),JSON.stringify(sizes))
  await manager.getByRole('textbox',{name:'筛选标题'}).fill('浏览器筛选验证')
  await manager.getByRole('button',{name:'查询',exact:true}).click()
  await expect(manager.locator('tbody tr')).toHaveCount(1)
  const title=manager.locator('.question-title');assert.ok([...await title.innerText()].length<=53)
  assert.equal(await title.evaluate(n=>getComputedStyle(n).whiteSpace),'nowrap')
  await manager.getByRole('button',{name:'查看关联的2个知识点'}).click()
  await expect(page.locator('.question-points-detail').getByText(longName,{exact:true})).toBeVisible()
  await page.screenshot({path:output+'/linked-points.png',fullPage:true})
  await manager.getByRole('button',{name:'查看关联的2个知识点'}).click()
  await manager.getByRole('combobox',{name:'筛选知识点'}).fill(longName)
  await page.getByRole('option').filter({hasText:longName}).click()
  await expect(manager.locator('tbody tr')).toHaveCount(1)
  await manager.getByRole('combobox',{name:'筛选题型'}).click()
  await page.getByRole('option',{name:'单选题',exact:true}).click()
  await expect(manager.locator('tbody tr')).toHaveCount(1)
  await manager.getByRole('button',{name:'停用',exact:true}).click()
  await page.locator('.el-message-box').getByRole('button',{name:'停用',exact:true}).click()
  await expect(manager.getByRole('button',{name:'启用',exact:true})).toHaveClass(/el-button--success/)
  await manager.locator('.el-select').filter({has:page.getByRole('combobox',{name:'筛选状态'})}).click();await page.getByRole('option',{name:'停用',exact:true}).click()
  await expect(manager.locator('tbody tr')).toHaveCount(1)
  await manager.getByRole('button',{name:'启用',exact:true}).click();await page.locator('.el-message-box').getByRole('button',{name:'启用',exact:true}).click()
  await expect(manager.locator('.el-table__empty-text')).toBeVisible()
  await manager.getByRole('button',{name:'重置',exact:true}).click()
  await expect(manager.locator('tbody tr').first()).toBeVisible()
  await page.screenshot({path:output+'/question-list.png',fullPage:true})
  await manager.getByRole('button',{name:'编辑题目'}).first().click()
  await expect(page.locator('.el-drawer').getByText('编辑题目',{exact:true})).toBeVisible()
  const editor=page.locator('.editor-drawer:visible')
  const association=editor.locator('.el-form-item').filter({has:page.locator('.el-form-item__label',{hasText:'关联知识点'})})
  await association.getByRole('button',{name:'移除关联：'+longName,exact:true}).click()
  await editor.getByRole('button',{name:'保存题目',exact:true}).click()
  await expect(editor).toBeHidden()
  let saved=(await db.query("SELECT * FROM content WHERE id='browser-question-list'")).rows[0]
  assert.equal(saved.payload.type,'configured');assert.deepEqual(saved.payload.knowledgePointIds,[points[0].id])
  assert.deepEqual(saved.payload.values.response.options,source.payload.options)
  assert.deepEqual(saved.payload.values.response.answer,source.payload.answer)
  await manager.getByRole('button',{name:'编辑题目'}).first().click()
  await expect(editor.locator('.qe-content')).toBeVisible()
  await association.getByRole('button',{name:'选择知识点',exact:true}).click()
  const picker=page.getByRole('dialog',{name:'选择关联知识点',exact:true})
  await picker.getByRole('textbox',{name:'搜索知识点名称或目录'}).fill(longName)
  await picker.locator('.kp-option').filter({hasText:longName}).click()
  await expect(picker.locator('.kp-selected').getByText(longName,{exact:true})).toBeVisible()
  await picker.getByRole('button',{name:'取消',exact:true}).click()
  await expect(association.getByText(longName,{exact:true})).toHaveCount(0)
  await association.getByRole('button',{name:'选择知识点',exact:true}).click()
  await picker.getByRole('textbox',{name:'搜索知识点名称或目录'}).fill(longName)
  await picker.locator('.kp-option').filter({hasText:longName}).click()
  await picker.getByRole('textbox',{name:'搜索知识点名称或目录'}).fill('不存在的知识点')
  await expect(picker.getByText('没有匹配的知识点，请调整筛选条件')).toBeVisible()
  await expect(picker.locator('.kp-selected').getByText(longName,{exact:true})).toBeVisible()
  await picker.getByRole('button',{name:'重置筛选',exact:true}).click()
  const sec=(await db.query('SELECT * FROM knowledge_nodes WHERE id=$1',[points[1].parent_id])).rows[0]
  const chap=(await db.query('SELECT * FROM knowledge_nodes WHERE id=$1',[sec.parent_id])).rows[0]
  const sub=(await db.query('SELECT * FROM knowledge_nodes WHERE id=$1',[chap.parent_id])).rows[0]
  async function selectDirectory(label,title){await picker.locator('.el-select').filter({has:page.getByRole('combobox',{name:label,exact:true})}).click();await page.getByRole('option',{name:title,exact:true}).first().click()}
  await selectDirectory('选择器科目',sub.title);await selectDirectory('选择器章',chap.title);await selectDirectory('选择器节',sec.title)
  await expect(picker.locator('.kp-option').filter({hasText:longName})).toBeVisible()
  await picker.getByRole('textbox',{name:'搜索知识点名称或目录'}).fill(longName)
  assert.equal(await picker.locator('.kp-option .el-checkbox__label').first().evaluate(n=>getComputedStyle(n).whiteSpace),'normal')
  await page.screenshot({path:output+'/knowledge-picker.png',fullPage:true})
  await page.setViewportSize({width:1280,height:900})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
  await page.screenshot({path:output+'/knowledge-picker-1280.png',fullPage:true})
  await page.setViewportSize({width:1733,height:1100})
  await picker.getByRole('button',{name:'确认选择（2）',exact:true}).click()
  await editor.getByPlaceholder('用于题目列表检索；各小题内容在下方录入').fill(longTitle+'已编辑')
  await editor.getByRole('button',{name:'保存题目',exact:true}).click()
  await expect(editor).toBeHidden()
  saved=(await db.query("SELECT * FROM content WHERE id='browser-question-list'")).rows[0]
  assert.deepEqual(new Set(saved.payload.knowledgePointIds),new Set(points.map(p=>p.id)))
  assert.equal(saved.title,longTitle+'已编辑');assert.deepEqual(saved.payload.values.response.answer,source.payload.answer)
  const multiOptions=['标准性实验设计','访问提纲','资料整理分析','操作化为具体指标','协作伙伴工作关系']
  await call('/admin/content/browser-multiple-save',{...source,id:'browser-multiple-save',version:undefined,status:'draft',title:'社会工作研究方法保存验证',parent_id:points[0].id,payload:{type:'multiple',stem:'关于社会工作研究方法的说法，正确的有（）。',options:multiOptions,answer:[2,3,4],explanation:'多选题原有解析',knowledgePointId:points[0].id,knowledgePointIds:[points[0].id]}})
  await manager.getByRole('textbox',{name:'筛选标题'}).fill('社会工作研究方法保存验证')
  await manager.getByRole('button',{name:'查询',exact:true}).click()
  await expect(manager.locator('tbody tr')).toHaveCount(1)
  await manager.getByRole('button',{name:'编辑题目'}).click()
  await expect(editor.getByRole('textbox',{name:'题目选项E',exact:true})).toHaveValue(multiOptions[4])
  await association.getByRole('button',{name:'选择知识点',exact:true}).click()
  await picker.getByRole('textbox',{name:'搜索知识点名称或目录'}).fill(longName)
  await picker.locator('.kp-option').filter({hasText:longName}).click()
  await picker.getByRole('button',{name:'确认选择（2）',exact:true}).click()
  await editor.getByRole('textbox',{name:'题目选项A',exact:true}).fill('更新后的标准性实验设计')
  await editor.getByRole('button',{name:'保存题目',exact:true}).click()
  await expect(editor).toBeHidden()
  const multiple=(await db.query("SELECT * FROM content WHERE id='browser-multiple-save'")).rows[0]
  assert.equal(multiple.payload.type,'configured');assert.deepEqual(multiple.payload.values.response.answer,[2,3,4])
  assert.equal(multiple.payload.values.response.options[0],'更新后的标准性实验设计')
  assert.equal(multiple.payload.values.response.explanation,'多选题原有解析')
  assert.deepEqual(new Set(multiple.payload.knowledgePointIds),new Set(points.map(p=>p.id)))
  await manager.getByRole('button',{name:'编辑题目'}).click()
  await expect(editor.getByRole('textbox',{name:'题目选项A',exact:true})).toHaveValue('更新后的标准性实验设计')
  await expect(editor.getByRole('checkbox',{name:'题目正确答案C',exact:true})).toBeChecked()
  await page.screenshot({path:output+'/multiple-saved-and-reopened.png',fullPage:true})
  await editor.getByRole('textbox',{name:'题目选项A',exact:true}).fill('未保存的内容')
  await editor.getByRole('button',{name:'取消',exact:true}).click()
  await manager.getByRole('button',{name:'编辑题目'}).click()
  await expect(editor.getByRole('textbox',{name:'题目选项A',exact:true})).toHaveValue('更新后的标准性实验设计')
  await editor.getByRole('button',{name:'取消',exact:true}).click()
  await manager.getByRole('button',{name:'重置',exact:true}).click()
  await page.locator('.heading-actions').getByRole('button',{name:'导入题库'}).click()
  const dialog=page.locator('.el-dialog').filter({hasText:'按题型导入题目'})
  await dialog.locator('.el-select').nth(1).click();await page.getByRole('option',{name:'浏览器五选项',exact:true}).click()
  await expect(dialog.getByText('主观题',{exact:true})).toHaveCount(0)
  await expect(dialog.getByText(/前 5 列必填/)).toBeVisible()
  const [download]=await Promise.all([page.waitForEvent('download'),dialog.getByRole('button',{name:'下载对应模板'}).click()])
  const w=new ExcelJS.Workbook();await w.xlsx.readFile(await download.path());const headers=w.getWorksheet('题目').getRow(1).values
  assert.equal(headers.filter(h=>String(h).includes('选项 ')&&String(h).includes('必填')).length,5)
  await page.screenshot({path:output+'/dynamic-template.png',fullPage:true})
  await dialog.getByRole('button',{name:'取消',exact:true}).click()
  await page.setViewportSize({width:1280,height:900})
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)
  await page.screenshot({path:output+'/question-list-1280.png',fullPage:true})
  assert.deepEqual(errors,[])
  console.log('Question management browser passed: public controls, 6 columns, title truncation, all filters, secondary knowledge link, full-name popover, edit, disable/enable, dynamic Excel download, 1280 layout.')
}finally{await browser.close();await new Promise(r=>server.close(r));await closeDatabase()}
