import 'dotenv/config'
import assert from 'node:assert/strict'
import {mkdir} from 'node:fs/promises'
import {chromium,expect} from '@playwright/test'
import QRCode from 'qrcode'
import {profileFixture} from './helpers/user-profile-fixture.ts'

const f=await profileFixture();let browser
try{
 await f.db.query("UPDATE content SET title='搜索验收知识点' WHERE id='a-k'")
 for(const [id,kind,parent,title] of [['search-main','course','a-t','搜索验收精品课'],['search-support','course','a-k','搜索验收配套课'],['search-faq','faq',null,'搜索验收常见问题']])await f.db.query("INSERT INTO content(id,exam_id,kind,parent_id,title,status,payload) VALUES($1,$2,$3,$4,$5,'published',$6)",[id,kind==='faq'?null:f.exam,kind,parent,title,JSON.stringify({type:'article',content:'搜索验收正文',article:{scope:'all',examIds:[]}})])
 browser=await chromium.launch({channel:'chrome',headless:true})
 const context=await browser.newContext({viewport:{width:1600,height:1080},reducedMotion:'reduce'}),errors=[]
 context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)))
 await context.route('**/api/**',async route=>{const u=new URL(route.request().url());if(!u.pathname.startsWith('/api/'))return route.continue();await route.fulfill({response:await route.fetch({url:f.origin+u.pathname+u.search})})})
 await context.addInitScript(t=>{if(location.port==='5180')sessionStorage.setItem('sxb-admin-token',t)},f.token)
 const admin=await context.newPage();await admin.goto('http://127.0.0.1:5180/#settings')
 const root=admin.locator('.site-settings')
 await expect(root.getByRole('tab')).toHaveText(['基本设置','接口配置','AI员工','搜索设置','协议管理','客服设置','关于平台'])
 await root.getByRole('tab',{name:'接口配置',exact:true}).click()
 await expect(root.locator('.interface-card')).toHaveCount(6)
 await expect(root.locator('.interface-grid')).toContainText('阿里云短信')
 await expect(root.locator('.settings-savebar')).toHaveCount(0)
 await root.getByRole('tab',{name:'AI员工',exact:true}).click()
 await expect(root.getByText('等待开发',{exact:true})).toBeVisible()
 await root.getByRole('tab',{name:'基本设置',exact:true}).click()
 await expect(root.getByLabel('平台名称',{exact:true})).toHaveValue('上行宝')
 await root.getByLabel('平台名称',{exact:true}).fill('星河学习')
 const png=await QRCode.toBuffer('https://example.com/support',{width:240,margin:2})
 await root.locator('input[type=file]').first().setInputFiles({name:'平台标识.png',mimeType:'image/png',buffer:png})
 const save=async()=>{await expect(root.getByRole('button',{name:'保存草稿',exact:true})).toBeEnabled();await root.getByRole('button',{name:'保存草稿',exact:true}).click();await expect(root.getByRole('button',{name:'保存草稿',exact:true})).toBeDisabled()}
 const publish=async name=>{await expect(root.getByRole('button',{name,exact:true})).toBeEnabled();await root.getByRole('button',{name,exact:true}).click();await admin.getByRole('button',{name:'确认发布',exact:true}).click();await expect(root.getByRole('button',{name,exact:true})).toBeDisabled()}
 await save()
 assert.equal((await(await fetch(f.origin+'/api/site-settings')).json()).basic.name,'上行宝')
 await publish('发布配置')
 await root.getByRole('tab',{name:'客服设置',exact:true}).click()
 await root.getByLabel('客服名称',{exact:true}).fill('学习顾问')
 await root.getByLabel('联系方式',{exact:true}).fill('400-100-2000')
 await root.getByLabel('服务时间',{exact:true}).fill('工作日 09:00—18:00')
 await root.locator('input[type=file]').setInputFiles({name:'客服二维码.png',mimeType:'image/png',buffer:png})
 await save();await publish('发布配置')
 await root.getByRole('tab',{name:'协议管理',exact:true}).click()
 await root.getByRole('textbox',{name:'图文正文编辑器'}).fill('新版用户服务协议：请合理使用平台学习资源。')
 await save();await publish('发布新版本')
 await expect(root.locator('.protocol-editor-heading')).toContainText('V2')
 await root.getByRole('button',{name:'版本历史',exact:true}).click()
 await expect(admin.locator('.protocol-history')).toContainText('V2')
 await admin.mouse.click(20,500);await expect(admin.locator('.protocol-history')).toBeVisible()
 await admin.getByRole('button',{name:'关闭',exact:true}).last().click()
 await mkdir('.local/qa/site-settings',{recursive:true})
 await admin.screenshot({path:'.local/qa/site-settings/admin-protocols.png',animations:'disabled'})
 await root.getByRole('tab',{name:'搜索设置',exact:true}).click();await expect(root.getByText('热门词',{exact:true})).toHaveCount(0)
 await root.getByRole('tab',{name:'基本设置',exact:true}).click()
 await admin.screenshot({path:'.local/qa/site-settings/admin-basic.png',animations:'disabled'})

 const user=await context.newPage();await user.setViewportSize({width:390,height:844})
 await user.goto('http://127.0.0.1:5174/#/pages/login/index')
 await expect(user.locator('.brand-name')).toHaveText('星河学习')
 await expect(user.locator('.brand-logo img')).toBeVisible()
 await user.locator('.field input').nth(0).fill('18800007890')
 const codeResponse=user.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/code')
 await user.locator('.code-button').click();const code=(await(await codeResponse).json()).testCode
 await user.locator('.field input').nth(1).fill(code)
 await user.locator('.login-button').click()
 const dialog=user.locator('.protocol-dialog');await expect(dialog).toBeVisible()
 await expect(dialog.locator('.protocol-tabs')).toContainText('V2')
 assert.equal(await user.evaluate(()=>Boolean(uni.getStorageSync('sxb-api-token'))),false)
 await expect(dialog.locator('.primary')).toHaveAttribute('disabled','true')
 await user.screenshot({path:'.local/qa/site-settings/consent.png',animations:'disabled'})
 await dialog.locator('uni-checkbox').click()
 await dialog.locator('.primary').click();await expect(dialog).toBeHidden()
 await expect.poll(()=>user.evaluate(()=>Boolean(uni.getStorageSync('sxb-api-token')))).toBe(true)
 await expect(user.locator('.home.page')).toBeVisible()
 await user.goto('http://127.0.0.1:5174/#/pages/profile/index')
 await user.locator('.menu-row').filter({hasText:'联系客服'}).click()
 await expect(user.locator('.customer-title')).toHaveText('学习顾问');await expect(user.locator('.customer-qr img')).toBeVisible();await expect(user.locator('.customer-contact')).toContainText('400-100-2000')
 await user.screenshot({path:'.local/qa/site-settings/customer.png',animations:'disabled'})
 await user.locator('.customer-close').click()
 await user.goto('http://127.0.0.1:5174/#/pages/search/index')
 await user.locator('.search-input input').fill('搜索验收')
 await user.locator('.submit-search').click();await expect(user.locator('.result')).toHaveCount(3)
 await expect(user.locator('.result').filter({hasText:'配套课'})).toHaveCount(0)
 await user.screenshot({path:'.local/qa/site-settings/search.png',animations:'disabled'})
 await user.locator('.result').filter({hasText:'搜索验收知识点'}).click()
 await expect(user.locator('.hero-title')).toHaveText('搜索验收知识点')
 await user.goto('http://127.0.0.1:5174/#/pages/search/index')
 await user.locator('.search-input input').fill('搜索验收');await user.locator('.submit-search').click()
 await expect(user.locator('.result')).toHaveCount(3)
 await user.locator('.result').filter({hasText:'搜索验收常见问题'}).click()
 await expect(user.locator('.fold-content')).toHaveText('搜索验收正文')
 assert.equal(await user.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)
 await user.goto('http://127.0.0.1:5174/#/pages/profile-center/index?mode=agreement')
 await expect(user.locator('.article-version')).toContainText('V2')
 await expect(user.locator('.protocol-article')).toContainText('新版用户服务协议')
 await admin.goto('http://127.0.0.1:5180/#media')
 await admin.getByRole('textbox',{name:'文件名称',exact:true}).fill('平台标识')
 await admin.getByRole('button',{name:'查询',exact:true}).click()
 await expect(admin.locator('.resource-management tbody tr')).toHaveCount(1)
 await admin.locator('.resource-reference>button').first().click()
 await expect(admin.locator('.site-settings')).toBeVisible()
 await admin.locator('.site-settings').getByRole('tab',{name:'协议管理',exact:true}).click()
 await admin.getByRole('textbox',{name:'图文正文编辑器'}).fill('再次更新的用户服务协议。')
 await save();await publish('发布新版本')
 await user.evaluate(async()=>{const token=uni.getStorageSync('sxb-api-token');await fetch('/api/auth/logout',{method:'POST',headers:{Authorization:'Bearer '+token}});uni.removeStorageSync('sxb-api-token')})
 await user.goto('http://127.0.0.1:5174/?protocol-update=1#/pages/login/index')
 await user.locator('.field input').nth(0).fill('18800007890')
 // Successful login consumes the OTP, but the SMS cooldown must still survive it.
 await f.db.query("UPDATE sms_deliveries SET created_at=now()-interval '2 minutes' WHERE phone='18800007890'")
 const nextCode=user.waitForResponse(r=>new URL(r.url()).pathname==='/api/auth/code');await user.locator('.code-button').click()
 await user.locator('.field input').nth(1).fill((await(await nextCode).json()).testCode)
 await user.locator('.login-button').click();await expect(user.locator('.protocol-dialog')).toBeVisible()
 await expect(user.locator('.protocol-tabs')).toContainText('V3');await expect(user.locator('.protocol-actions .primary')).toHaveAttribute('disabled','true')
 await user.locator('.protocol-actions uni-button').first().click();await expect(user.locator('.protocol-dialog')).toHaveCount(0)
 assert.equal(await user.evaluate(()=>Boolean(uni.getStorageSync('sxb-api-token'))),false)
 assert.deepEqual(errors,[])
 console.log(JSON.stringify({status:'PASS',adminTabs:true,registeredUploads:true,draftPublish:true,protocolHistory:true,explicitConsent:true,renewedConsent:true,declineDoesNotLogin:true,brandAndCustomer:true,liveSearch:true,faqDeepLink:true,resourceNavigation:true}))
}finally{await browser?.close();await f.close()}
