<script setup lang="ts">
import { ref, computed } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { examCategories } from '@/mock/data'
import { useAppStore } from '@/store/app'
import uniIcons from '@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue'
import { backOrFallback } from '@/utils/navigation'

const { exam, selectExam } = useAppStore()
const activeCategory = ref(examCategories[0].id)
const keyword = ref('')
const active = computed(() => examCategories.find(item => item.id === activeCategory.value) || examCategories[0])
const filteredGroups = computed(() => active.value.groups.map(group => ({ ...group, exams: group.exams.filter(item => !keyword.value || `${item.name}${item.subtitle}`.includes(keyword.value)) })).filter(group => group.exams.length))
const choose = async (id: string) => { uni.showLoading({ title: '切换中' }); try { await selectExam(id); uni.reLaunch({ url: '/pages/index/index' }) } catch (e) { uni.showToast({ title: e instanceof Error ? e.message : '切换失败', icon: 'none' }) } finally { uni.hideLoading() } }
const goBack = () => backOrFallback('/pages/index/index')
onShow(() => { activeCategory.value = examCategories.find(category => category.groups.some(group => group.exams.some(item => item.id === exam.value.id)))?.id || examCategories[0].id })
</script>

<template>
  <view class="switch-page safe-top"><view class="switch-top"><view class="back" @tap="goBack"><uni-icons type="back" size="24" color="#344652" /></view><view><text class="switch-title">选择考试项目</text><text class="switch-subtitle">切换后，学习内容会同步切换</text></view></view><view class="search-box"><uni-icons type="search" size="20" color="#6f7f96" /><input v-model="keyword" placeholder="搜索考试名称，例如：建造师" /></view><view class="switch-layout"><scroll-view scroll-y class="category-list" :show-scrollbar="false"><view v-for="category in examCategories" :key="category.id" class="category" :class="{ active: category.id === activeCategory }" @tap="activeCategory = category.id"><uni-icons :type="category.icon" size="20" :color="category.id === activeCategory ? '#3569e8' : '#8c99a4'" /><text>{{ category.name }}</text></view></scroll-view><scroll-view scroll-y class="exam-list" :show-scrollbar="false"><view v-for="group in filteredGroups" :key="group.title" class="exam-group"><view class="group-title"><text>{{ group.title }}</text><text>{{ group.exams.length }} 个项目</text></view><view class="exam-grid"><view v-for="item in group.exams" :key="item.id" class="exam-card" :class="{ selected: item.id === exam.id }" @tap="choose(item.id)"><view class="exam-card-icon"><uni-icons type="medal" size="20" color="#6949df" /></view><text class="exam-card-name">{{ item.name }}</text><text class="exam-card-subtitle">{{ item.subtitle }}</text><view v-if="item.id === exam.id" class="selected-mark">✓</view></view></view></view><view v-if="!filteredGroups.length" class="empty">没有找到相关考试</view></scroll-view></view></view>
</template>

<style lang="scss">
.switch-page{min-height:100vh;background:#fff;padding:42rpx 26rpx 0;}.switch-top{display:flex;align-items:center;gap:14rpx;}.back{width:52rpx;height:52rpx;border-radius:10rpx;background:#f1f4f5;display:flex;align-items:center;justify-content:center;flex:none;}.switch-top>view:last-child{display:flex;flex-direction:column;gap:6rpx;}.switch-title{font-size: 35rpx;font-weight:850;}.switch-subtitle{font-size: 21rpx;color:#84909c;}.search-box{height:72rpx;background:#f2f5f7;border-radius:12rpx;margin:26rpx 0 18rpx;display:flex;align-items:center;gap:12rpx;padding:0 18rpx;}.search-box input{height:72rpx;flex:1;font-size: 22rpx;}.switch-layout{display:flex;height:calc(100vh - 190rpx);}.category-list{width:164rpx;background:#f5f7f8;border-radius:10rpx 0 0 10rpx;scrollbar-width:none;}.category-list::-webkit-scrollbar,.exam-list::-webkit-scrollbar{display:none;width:0;height:0;}.category{height:104rpx;padding:0 14rpx;display:flex;align-items:center;gap:8rpx;color:#7f8a95;font-size: 21rpx;position:relative;}.category.active{background:#fff;color:#197b74;font-weight:800;}.category.active:before{content:"";position:absolute;left:0;top:28rpx;bottom:28rpx;width:5rpx;background:#00b18d;border-radius:0 5rpx 5rpx 0;}.exam-list{flex:1;padding:0 0 80rpx 20rpx;scrollbar-width:none;}.exam-group{margin-bottom:28rpx;}.group-title{display:flex;align-items:center;justify-content:space-between;margin:8rpx 0 16rpx;}.group-title text:first-child{font-size: 25rpx;font-weight:850;}.group-title text:last-child{font-size: 19rpx;color:#a0aab3;}.exam-grid{display:grid;grid-template-columns:1fr 1fr;gap:12rpx;}.exam-card{min-height:154rpx;padding:17rpx 14rpx;background:#f7f8f9;border:2rpx solid transparent;border-radius:12rpx;display:flex;flex-direction:column;gap:7rpx;position:relative;}.exam-card.selected{background:#f0fbf8;border-color:#00b18d;box-shadow:0 8rpx 18rpx rgba(0,177,141,.12);}.exam-card-icon{width:40rpx;height:40rpx;border-radius:10rpx;background:#fff;display:flex;align-items:center;justify-content:center;}.exam-card-name{font-size: 22rpx;font-weight:800;line-height:1.3;}.exam-card-subtitle{font-size: 19rpx;color:#8a96a1;}.selected-mark{position:absolute;right:0;top:0;width:34rpx;height:34rpx;background:#00b18d;color:#fff;border-radius:0 10rpx 0 10rpx;display:flex;align-items:center;justify-content:center;font-size: 21rpx;}.empty{text-align:center;color:#9aa5ae;font-size: 22rpx;padding-top:100rpx;}
.switch-page{min-height:100vh;background:#f5f7fb;padding:42rpx 26rpx 0;}.switch-top{display:flex;align-items:center;gap:14rpx;}.back{width:52rpx;height:52rpx;border-radius:12rpx;background:#e9efff;display:flex;align-items:center;justify-content:center;flex:none;}.switch-top>view:last-child{display:flex;flex-direction:column;gap:6rpx;}.switch-title{color:#152238;font-size: 35rpx;font-weight:850;}.switch-subtitle{font-size: 21rpx;color:#84909c;}.search-box{height:72rpx;background:#fff;border:1rpx solid #e1e7f1;border-radius:12rpx;margin:26rpx 0 18rpx;display:flex;align-items:center;gap:12rpx;padding:0 18rpx;box-shadow:0 6rpx 18rpx rgba(40,58,91,.04);}.search-box input{height:72rpx;flex:1;font-size: 22rpx;}.switch-layout{display:flex;height:calc(100vh - 190rpx);background:#fff;border:1rpx solid #e3e8f1;border-radius:12rpx;overflow:hidden;}.category-list{width:164rpx;background:#eef2f8;border-radius:0;scrollbar-width:none;}.category-list::-webkit-scrollbar,.exam-list::-webkit-scrollbar{display:none;width:0;height:0;}.category{height:104rpx;padding:0 14rpx;display:flex;align-items:center;gap:8rpx;color:#7f8a95;font-size: 21rpx;position:relative;}.category.active{background:#fff;color:#3569e8;font-weight:800;}.category.active:before{content:"";position:absolute;left:0;top:28rpx;bottom:28rpx;width:5rpx;background:linear-gradient(180deg,#3569e8,#7655df);border-radius:0 5rpx 5rpx 0;}.exam-list{flex:1;padding:0 14rpx 80rpx 20rpx;scrollbar-width:none;}.exam-group{margin-bottom:28rpx;}.group-title{display:flex;align-items:center;justify-content:space-between;margin:18rpx 0 16rpx;}.group-title text:first-child{color:#1c2d45;font-size: 25rpx;font-weight:850;}.group-title text:last-child{font-size: 19rpx;color:#a0aab3;}.exam-grid{display:grid;grid-template-columns:1fr 1fr;gap:12rpx;}.exam-card{min-height:154rpx;padding:17rpx 14rpx;background:#f7f9fc;border:2rpx solid transparent;border-radius:12rpx;display:flex;flex-direction:column;gap:7rpx;position:relative;}.exam-card.selected{background:#f1efff;border-color:#7655df;box-shadow:0 8rpx 18rpx rgba(105,73,223,.14);}.exam-card-icon{width:40rpx;height:40rpx;border-radius:10rpx;background:#eeeaff;display:flex;align-items:center;justify-content:center;}.exam-card-name{color:#1d2d43;font-size: 22rpx;font-weight:800;line-height:1.3;}.exam-card-subtitle{font-size: 19rpx;color:#8a96a1;}.selected-mark{position:absolute;right:0;top:0;width:34rpx;height:34rpx;background:#7655df;color:#fff;border-radius:0 10rpx 0 10rpx;display:flex;align-items:center;justify-content:center;font-size: 21rpx;}.empty{text-align:center;color:#9aa5ae;font-size: 22rpx;padding-top:100rpx;}
</style>
