<script setup lang="ts">
import { ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import uniIcons from '@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue'
import { api, selectedExamId } from '@/services/api'
import { backOrFallback } from '@/utils/navigation'
const items=ref<any[]>([]),busy=ref(false),error=ref('')
const date=(v:string)=>new Date(v).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'})
async function load(){busy.value=true;error.value='';items.value=[];const exam=selectedExamId();try{const data=await api(`/cheatsheets/${exam}`);if(exam===selectedExamId())items.value=data}catch(e:any){error.value=e.message}finally{busy.value=false}}
onShow(load)
const open=(id:string)=>uni.navigateTo({url:`/pages/cheatsheet-detail/index?id=${encodeURIComponent(id)}`})
</script>
<template><view class="sheets-page safe-top"><view class="sheets-top"><button aria-label="返回" @tap="backOrFallback('/pages/index/index')"><uni-icons type="back" size="22" /></button><text>考前小抄</text></view><view v-if="busy" class="sheets-state">正在加载…</view><view v-else-if="error" class="sheets-state"><text>{{ error }}</text><button @tap="load">重试</button></view><view v-else-if="!items.length" class="sheets-state">当前考试暂未发布考前小抄</view><view v-for="item in items" :key="item.id" class="sheet-row"><view class="sheet-state" :class="item.state">{{ item.state==='open'?'已开放':item.state==='upcoming'?'即将开放':'已结束' }}<text v-if="item.isTestData"> · 测试内容</text></view><button class="sheet-title" @tap="open(item.id)">{{ item.title }}<uni-icons type="right" size="18" color="#66768c" /></button><text class="sheet-intro">{{ item.intro }}</text><text class="sheet-date">{{ item.state==='upcoming'?`${date(item.opensAt)} 开放`:`开放至 ${date(item.closesAt)}` }}</text></view></view></template>
<style scoped>.sheets-page{max-width:430px;min-height:100vh;margin:auto;padding:12px 20px 40px;box-sizing:border-box;background:#fff}.sheets-top{display:flex;align-items:center;gap:12px;font-size:18px;font-weight:700;color:#24364d;padding:8px 0 20px}.sheets-top button{display:grid;place-items:center;width:44px;height:44px;margin:0;padding:0;background:transparent}.sheets-top button::after,.sheet-title::after{display:none}.sheet-row{padding:24px 0;border-bottom:1px solid #e4e9f0}.sheet-state{font-size:13px;color:#69788c}.sheet-state.open{color:#207e67}.sheet-state.upcoming{color:#3569e8}.sheet-title{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:8px 0;padding:0;min-height:44px;text-align:left;font-size:18px;line-height:1.6;font-weight:700;color:#24364d;background:transparent;border:0}.sheet-intro{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden;color:#53647b;font-size:16px;line-height:1.8}.sheet-date{display:block;font-size:14px;color:#69788c;margin-top:12px}.sheets-state{padding:48px 0;text-align:center;font-size:16px;color:#53647b}.sheets-state button{margin-top:16px;font-size:16px;color:#3569e8}</style>
