<script setup lang="ts">
import { ref } from 'vue'
import { onLoad, onShow } from '@dcloudio/uni-app'
import uniIcons from '@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue'
import StudyContent from '@/components/StudyContent.vue'
import { api, token, selectedExamId } from '@/services/api'
import { backOrFallback } from '@/utils/navigation'
const id=ref(''),item=ref<any>(),busy=ref(false),error=ref('')
const date=(v:string)=>new Date(v).toLocaleString('zh-CN',{hour12:false})
onLoad(o=>{id.value=o?.id||''})
async function load(){if(!id.value)return;busy.value=true;error.value='';item.value=null;try{if(token())item.value=await api(`/cheatsheet/${encodeURIComponent(id.value)}`);else {const rows=await api(`/cheatsheets/${selectedExamId()}`);const row=rows.find((r:any)=>r.id===id.value);if(!row)throw new Error('内容不存在或已下架');item.value={...row,locked:true,blocks:[]}}if(item.value.examId!==selectedExamId())throw new Error('请切换到该资料所属考试后查看')}catch(e:any){item.value=null;error.value=e.message}finally{busy.value=false}}
onShow(load)
function unlock(){uni.navigateTo({url:token()?'/pages/profile-center/index?mode=rights':`/pages/login/index?redirect=${encodeURIComponent(`/pages/cheatsheet-detail/index?id=${id.value}`)}`})}
</script>
<template><view class="sheet-detail safe-top"><view class="sheet-header"><button aria-label="返回" @tap="backOrFallback('/pages/cheatsheets/index')"><uni-icons type="back" size="22" /></button><text>考前小抄</text></view><view v-if="busy" class="sheet-message">正在加载…</view><view v-else-if="error" class="sheet-message"><text>{{ error }}</text><button @tap="load">重试</button></view><template v-else-if="item"><text v-if="item.isTestData" class="test-mark">测试内容</text><h1>{{ item.title }}</h1><text class="sheet-meta">上行宝 · {{ date(item.updatedAt) }} 更新</text><text class="sheet-intro">{{ item.intro }}</text><view v-if="item.locked" class="sheet-lock"><uni-icons type="locked" size="30" color="#3569e8" /><text class="lock-title">{{ item.state==='upcoming'?'尚未开放':item.state==='expired'?'本次开放已结束':'当前考试 SVIP 专属' }}</text><text class="lock-meta">{{ item.state==='upcoming'?`${date(item.opensAt)} 开放`:item.state==='expired'?`${date(item.closesAt)} 已关闭`:'开通对应考试权益后，即可阅读完整资料' }}</text><button v-if="item.state==='open'" @tap="unlock">{{ token()?'查看会员权益':'登录后查看' }}</button></view><StudyContent v-else :blocks="item.blocks" /></template></view></template>
<style scoped>.sheet-detail{max-width:430px;min-height:100vh;box-sizing:border-box;margin:auto;padding:12px 20px 48px;background:#fff}.sheet-header{display:flex;gap:12px;align-items:center;font-size:18px;font-weight:700;color:#26384d;margin-bottom:24px}.sheet-header button{display:grid;place-items:center;width:44px;height:44px;padding:0;margin:0;background:none}.sheet-header button::after{display:none}h1{font-size:24px;line-height:1.5;font-weight:700;color:#24364d;margin:12px 0}.sheet-meta{display:block;color:#68778b;font-size:13px;line-height:1.6}.sheet-intro{display:block;color:#52647c;font-size:16px;line-height:1.8;padding:20px 0;border-bottom:1px solid #e3e9f1}.test-mark{font-size:13px;color:#957015}.sheet-lock{padding:40px 12px;text-align:center}.lock-title{display:block;margin:16px 0 8px;font-size:18px;font-weight:700;color:#293e5b}.lock-meta{display:block;font-size:15px;color:#60718a;line-height:1.8}.sheet-lock button,.sheet-message button{min-height:44px;margin-top:24px;background:#3569e8;color:white;font-size:16px;border-radius:6px}.sheet-message{padding:48px 0;text-align:center;font-size:16px;color:#60718a}</style>
