<script setup lang="ts">
import { onShow } from '@dcloudio/uni-app'
import { courses } from '@/mock/data'
import { useAppStore } from '@/store/app'
const { state } = useAppStore()
onShow(() => { state.selectedTab = 2 })
const toast = (title: string) => uni.showToast({ title, icon: 'none' })
</script>

<template>
  <view class="page safe-top learning-page"><view class="eyebrow">LEARNING SPACE</view><view class="heading">把知识学成自己的</view><text class="muted intro">知识图谱、课程与智能背题，随时从你需要的地方开始</text>
    <view class="learning-feature panel"><view><text class="feature-label">重点知识图谱</text><text class="feature-title">看见知识之间的联系</text><text class="muted">按科目梳理章节与知识点，快速找到薄弱环节</text></view><view class="map-orbit"><view class="orbit-line"></view><view class="orbit-node node-a">社工</view><view class="orbit-node node-b">伦理</view><view class="orbit-node node-c">实务</view></view></view>
    <view class="learn-actions"><view class="learn-action panel" @tap="toast('知识图谱即将打开')"><view class="action-symbol graph">⌘</view><text class="action-title">知识图谱</text><text class="muted">梳理重点脉络</text></view><view class="learn-action panel" @tap="toast('智能背题已准备好')"><view class="action-symbol recall">✦</view><text class="action-title">智能背题</text><text class="muted">今日待背 16 条</text></view></view>
    <view class="section-head"><text class="section-title">课程内容</text><text class="section-link" @tap="toast('课程筛选即将上线')">筛选 ›</text></view><view class="course-list"><view v-for="course in courses" :key="course.id" class="course panel" @tap="toast(`${course.title} 即将打开`)"><view class="course-type" :class="course.type === '视频' ? 'video' : course.type === '音频' ? 'audio' : 'article'">{{ course.type }}</view><view class="course-main"><text class="course-title">{{ course.title }}</text><text class="muted">{{ course.meta }}</text><view class="course-progress"><view :style="{ width: `${course.progress}%` }"></view></view></view><text class="course-percent">{{ course.progress ? `${course.progress}%` : '开始' }}</text></view></view>
  </view>
</template>

<style scoped lang="scss">
.learning-page{padding-top:calc(env(safe-area-inset-top) + 42rpx);}.intro{display:block;margin-top:12rpx;line-height:1.55;}.learning-feature{margin-top:32rpx;padding:28rpx;display:flex;align-items:center;justify-content:space-between;min-height:250rpx;overflow:hidden;background:#eaf4f1;border-color:#d4e8e3;}.learning-feature>view:first-child{display:flex;flex-direction:column;gap:10rpx;max-width:58%;}.feature-label{color:#197b74;font-size: var(--sxb-text-body);font-weight:700;}.feature-title{font-size: var(--sxb-text-heading);font-weight:700;color:#182230;}.map-orbit{position:relative;width:220rpx;height:190rpx;}.orbit-line{position:absolute;inset:20rpx;border:2rpx dashed #a8d1c9;border-radius:50%;transform:rotate(-20deg);}.orbit-node{position:absolute;padding:13rpx 15rpx;border-radius:12rpx;background:#fff;color:#197b74;font-size: var(--sxb-text-body);font-weight:700;box-shadow:0 6rpx 16rpx rgba(25,123,116,.1);}.node-a{left:68rpx;top:62rpx;background:#197b74;color:#fff;}.node-b{right:0;top:18rpx;}.node-c{left:12rpx;bottom:14rpx;}.learn-actions{display:grid;grid-template-columns:1fr 1fr;gap:18rpx;margin-top:18rpx;}.learn-action{padding:22rpx;display:flex;flex-direction:column;gap:8rpx;}.action-symbol{width:56rpx;height:56rpx;display:flex;align-items:center;justify-content:center;border-radius:16rpx;font-size: var(--sxb-text-heading);font-weight:700;margin-bottom:2rpx;}.graph{background:#e7eff9;color:#4d7cae;}.recall{background:#f3eadf;color:#bd7735;}.action-title{font-size: var(--sxb-text-title);font-weight:700;}.course-list{display:flex;flex-direction:column;gap:14rpx;}.course{padding:22rpx;display:flex;align-items:center;gap:18rpx;}.course-type{width:68rpx;height:68rpx;border-radius:16rpx;display:flex;align-items:center;justify-content:center;font-size: var(--sxb-text-body);font-weight:700;}.video{background:#e5f3ee;color:#197b74;}.audio{background:#fbeadb;color:#bc6f30;}.article{background:#e9eef8;color:#5473a0;}.course-main{display:flex;flex-direction:column;gap:7rpx;flex:1;min-width:0;}.course-title{font-size: var(--sxb-text-title);font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;}.course-main .muted{font-size: var(--sxb-text-body);}.course-progress{height:8rpx;background:#eef1f2;border-radius:20rpx;overflow:hidden;margin-top:4rpx;}.course-progress view{height:100%;background:#73b1a6;border-radius:20rpx;}.course-percent{font-size: var(--sxb-text-body);color:#197b74;font-weight:700;}

@import '@/styles/content-system.scss';
</style>
