<script setup lang="ts">
import {watch} from 'vue'
import {siteSettings,refreshSiteSettings} from '@/services/site-settings'
const props=defineProps<{modelValue:boolean}>(),emit=defineEmits<{ 'update:modelValue':[boolean] }>()
watch(()=>props.modelValue,v=>{if(v)void refreshSiteSettings().catch(()=>{})})
const close=()=>emit('update:modelValue',false)
const copy=()=>uni.setClipboardData({data:siteSettings.customer.contact})
</script>
<template><view v-if="modelValue" class="customer-mask" @tap="close"><view class="customer-dialog" role="dialog" aria-modal="true" :aria-label="siteSettings.customer.name" @tap.stop><text class="customer-title">{{siteSettings.customer.name}}</text><text v-if="siteSettings.error" class="customer-description">{{siteSettings.error}}</text><template v-else><image v-if="siteSettings.customer.qrCode" :src="siteSettings.customer.qrCode" class="customer-qr" mode="aspectFit" alt="客服二维码"/><text v-else-if="!siteSettings.customer.contact" class="customer-empty">客服信息暂未配置</text><text v-if="siteSettings.customer.description" class="customer-description">{{siteSettings.customer.description}}</text><button v-if="siteSettings.customer.contact" class="customer-contact" @tap="copy">{{siteSettings.customer.contact}} · 复制</button><text v-if="siteSettings.customer.hours" class="customer-hours">{{siteSettings.customer.hours}}</text></template><button class="customer-close" @tap="close">关闭</button></view></view></template>
<style scoped>.customer-mask{position:fixed;z-index:150;inset:0;background:rgba(20,31,51,.48);display:flex;align-items:center;justify-content:center;padding:24px}.customer-dialog{width:100%;max-width:350px;max-height:85vh;overflow:auto;background:white;border-radius:18px;padding:26px;text-align:center;box-sizing:border-box}.customer-title{display:block;font-size:20px;font-weight:700;color:#22354d}.customer-qr{display:block;width:220px;height:220px;max-width:100%;margin:20px auto}.customer-description,.customer-hours,.customer-empty{display:block;font-size:14px;color:#607087;line-height:1.8;white-space:pre-wrap;margin:14px 0}.customer-empty{padding:30px 0;background:#f5f7fb;border-radius:10px}.customer-contact,.customer-close{font-size:14px;line-height:1.6;min-height:44px;display:flex;align-items:center;justify-content:center;border-radius:9px;margin-top:16px}.customer-contact{background:#e8f4ef;color:#187653;overflow-wrap:anywhere}.customer-close{background:#f1f3f6;color:#52647c}.customer-dialog button:after{border:0}</style>
