<script setup lang="ts">
import StudyContent from './StudyContent.vue'
import uniIcons from '@dcloudio/uni-ui/lib/uni-icons/uni-icons.vue'
defineProps<{title:string;path:string[];stars?:number;questionTotal:number;questionDone?:number;mastery?:number;blocks?:any[];busy?:boolean;error?:string;heading?:string;preview?:boolean;showBody?:boolean}>()
defineEmits<{retry:[]}>()
</script>
<template>
 <view class="crumb"><template v-for="(name,index) in path" :key="index"><uni-icons v-if="index" type="forward" size="13" color="#9ba6b5"/><text>{{name}}</text></template></view>
 <view class="point-hero"><view class="hero-top"><view class="hero-icon"><uni-icons type="map" size="24" color="#fff"/></view><view class="hero-title-wrap"><text class="hero-title">{{title}}</text><view v-if="stars||mastery!=null" class="hero-tags"><text v-if="stars" class="star-tag">{{stars}}星</text><text v-if="mastery!=null" class="mastery-tag">掌握 {{mastery}}%</text></view></view></view><view class="hero-stats" :class="{'preview-stats':preview}"><view><text>{{questionTotal}}</text><text>包含题目</text></view><template v-if="!preview"><view><text>{{questionDone||0}}</text><text>已做题目</text></view><view><text>{{questionTotal?Math.round((questionDone||0)/questionTotal*100):0}}%</text><text>完成进度</text></view></template></view></view>
 <view v-if="showBody!==false" class="content-card"><view class="card-title"><view class="title-bar"/><text>{{heading||'知识点内容'}}</text></view><text v-if="busy" class="content-text">正在加载…</text><view v-else-if="error"><text class="content-text">{{error}}</text><button @tap="$emit('retry')">重试</button></view><StudyContent v-else-if="blocks" :blocks="blocks" :preview="preview"/></view>
</template>
<style scoped>
.crumb{display:flex;align-items:center;gap:4rpx;margin-top:18rpx;overflow:hidden;color:#8b96a5;font-size:var(--sxb-text-meta);white-space:nowrap}.crumb text{overflow:hidden;text-overflow:ellipsis}.point-hero{margin-top:17rpx;padding:22rpx;color:#fff;background:linear-gradient(135deg,#1d3558,#3a4b93);border-radius:15rpx;box-shadow:0 12rpx 26rpx rgba(43,58,113,.18)}.hero-top{display:flex;align-items:flex-start;gap:12rpx}.hero-icon{width:48rpx;height:48rpx;display:flex;align-items:center;justify-content:center;flex:none;background:rgba(255,255,255,.14);border-radius:13rpx}.hero-title-wrap{flex:1;min-width:0}.hero-title{display:block;font-size:var(--sxb-text-item);line-height:1.5;font-weight:700;overflow-wrap:anywhere}.hero-tags{display:flex;align-items:center;gap:7rpx;margin-top:9rpx}.star-tag,.mastery-tag{display:inline-block;padding:4rpx 8rpx;border-radius:5rpx;font-size:var(--sxb-text-meta);font-weight:700}.star-tag{color:#d47a25;background:#fff2df}.mastery-tag{color:#d8e4ff;background:rgba(255,255,255,.12)}.hero-stats{display:grid;grid-template-columns:repeat(3,1fr);margin-top:20rpx;padding-top:17rpx;border-top:1rpx solid rgba(255,255,255,.15)}.hero-stats view{display:flex;flex-direction:column;align-items:center;gap:4rpx;border-right:1rpx solid rgba(255,255,255,.14)}.hero-stats view:last-child{border:0}.hero-stats text:first-child{font-size:var(--sxb-text-title);font-weight:700}.hero-stats text:last-child{color:#becbe2;font-size:var(--sxb-text-meta)}.preview-stats{grid-template-columns:1fr}.preview-stats view{flex-direction:row;gap:12rpx;justify-content:flex-start}.content-card{margin-top:16rpx;padding:19rpx;background:#fff;border:1rpx solid #e0e6f0;border-radius:13rpx;box-shadow:0 7rpx 19rpx rgba(51,74,115,.04)}.card-title{display:flex;align-items:center;gap:8rpx;color:#22354e;font-size:var(--sxb-text-body);font-weight:700}.title-bar{width:5rpx;height:24rpx;background:#3569e8;border-radius:5rpx}.content-text{display:block;margin-top:15rpx;color:#4b5c72;font-size:var(--sxb-text-body);line-height:1.75}
</style>
