<script setup lang="ts">
import {ref,watch} from 'vue'
import type {PublishedProtocol} from '@/services/site-settings'
const props=defineProps<{protocols:PublishedProtocol[];busy?:boolean;error?:string}>()
defineEmits<{confirm:[];cancel:[]}>()
const agreed=ref(false),active=ref('agreement')
watch(()=>props.protocols,()=>{agreed.value=false;active.value=props.protocols[0]?.kind||'agreement'},{deep:true})
</script>
<template><view class="protocol-mask"><view class="protocol-dialog" role="dialog" aria-modal="true" aria-label="请确认最新协议"><text class="protocol-title">请确认最新协议</text><text class="protocol-hint">首次登录或协议更新后，需要阅读并重新勾选确认。未确认前不会完成登录。</text><view class="protocol-tabs"><button v-for="p in protocols" :key="p.kind" :class="{active:active===p.kind}" @tap="active=p.kind">{{p.title}}<text>V{{p.version}}</text></button></view><scroll-view scroll-y class="protocol-body"><template v-for="p in protocols" :key="p.kind"><view v-if="p.kind===active"><text class="protocol-date">V{{p.version}} · {{new Date(p.publishedAt).toLocaleDateString('zh-CN')}}</text><rich-text :nodes="p.html"/></view></template></scroll-view><text v-if="error" class="protocol-error" role="alert">{{error}}</text><checkbox-group @change="agreed=($event.detail.value||[]).includes('agree')"><label class="protocol-check"><checkbox value="agree" :checked="agreed" :disabled="busy" color="#3569e8"/><text>我已阅读并同意以上协议的当前版本</text></label></checkbox-group><view class="protocol-actions"><button :disabled="busy" @tap="$emit('cancel')">暂不同意</button><button :disabled="!agreed||busy" :loading="busy" class="primary" @tap="$emit('confirm')">同意并继续登录</button></view></view></view></template>
<style scoped>.protocol-mask{position:fixed;inset:0;z-index:200;display:flex;align-items:center;justify-content:center;padding:18px;background:rgba(16,30,54,.55)}.protocol-dialog{width:100%;max-width:410px;max-height:calc(100dvh - 36px);overflow:auto;box-sizing:border-box;border-radius:18px;background:white;padding:22px}.protocol-title{display:block;color:#21334e;font-size:20px;font-weight:700}.protocol-hint{display:block;color:#617187;font-size:13px;line-height:1.7;margin:10px 0 16px}.protocol-tabs{display:flex;gap:8px;margin-bottom:12px}.protocol-tabs button{flex:1;min-width:0;font-size:13px;padding:8px 4px;line-height:1.6;margin:0;background:#f4f6fa;color:#52647c;border-radius:8px}.protocol-tabs button.active{background:#eaf0ff;color:#3569e8}.protocol-tabs text{display:block;font-size:12px}.protocol-body{height:min(34vh,280px);padding:0 2px;font-size:14px;line-height:1.85;color:#33445d}.protocol-date{display:block;font-size:12px;color:#66768b;margin-bottom:12px}.protocol-check{display:flex;align-items:flex-start;gap:8px;font-size:13px;line-height:1.7;margin:18px 0;color:#33445d}.protocol-check checkbox{flex:none}.protocol-actions{display:flex;gap:10px}.protocol-actions button{font-size:14px;line-height:1.6;min-height:44px;padding:10px;margin:0;flex:1;background:#f0f3f8;color:#52647c;border-radius:9px}.protocol-actions .primary{background:#3569e8;color:white;flex:1.5}.protocol-actions button[disabled]{opacity:.5}.protocol-dialog button:after{border:0}.protocol-error{display:block;color:#b42318;font-size:13px;line-height:1.6;margin-top:10px}</style>
